// Course catalog with GEM attributes and prerequisites
// Based on Berea College course offerings

import type { Course } from "./types";

export const COURSE_CATALOG: Record<string, Course> = {
  // CSC Courses
  "CSC 110": {
    code: "CSC 110",
    name: "Craft of Computing",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 111": {
    code: "CSC 111",
    name: "Storytelling-Comp Animation",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 114": {
    code: "CSC 114",
    name: "Business App & Programming",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 121": {
    code: "CSC 121",
    name: "Introduction to Game Design",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts", "Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 124": {
    code: "CSC 124",
    name: "Building Better Apps",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 126": {
    code: "CSC 126",
    name: "Intro to Robotics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 127": {
    code: "CSC 127",
    name: "Intro to Web Design",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts", "Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 226": {
    code: "CSC 226",
    name: "Software Design & Implement",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 236": {
    code: "CSC 236",
    name: "Data Structures",
    credits: 1,
    prerequisites: ["CSC 226"],
    waysOfKnowing: ["Applied Studies", "Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "CSC 246": {
    code: "CSC 246",
    name: "Scalable Algorithms & Objects",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies", "Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "CSC 300": {
    code: "CSC 300",
    name: "Embedded Systems",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 301": {
    code: "CSC 301",
    name: "Human-Centered Computing",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies", "Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "CSC 303": {
    code: "CSC 303",
    name: "Theory of Computation",
    credits: 1,
    prerequisites: ["CSC 236", "MAT 216"],
    waysOfKnowing: ["Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "CSC 330": {
    code: "CSC 330",
    name: "Database Systems",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 335": {
    code: "CSC 335",
    name: "Computer Organization",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 410": {
    code: "CSC 410",
    name: "Computational Intelligence",
    credits: 1,
    prerequisites: ["CSC 236", "MAT 216"],
    waysOfKnowing: ["Applied Studies", "Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "CSC 412": {
    code: "CSC 412",
    name: "Networking",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 420": {
    code: "CSC 420",
    name: "Programming Languages",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 425": {
    code: "CSC 425",
    name: "Operating Systems & VMs",
    credits: 1,
    prerequisites: ["CSC 335"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 426": {
    code: "CSC 426",
    name: "Open Source Software Engineering",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 433": {
    code: "CSC 433",
    name: "Numerical Analysis",
    credits: 1,
    prerequisites: ["MAT 225", "CSC 236"],
    waysOfKnowing: ["Quantitative Focus", "Applied Studies"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "CSC 440": {
    code: "CSC 440",
    name: "Design & Analysis of Algorithms",
    credits: 1,
    prerequisites: ["CSC 246", "MAT 216"],
    waysOfKnowing: ["Quantitative Focus", "Applied Studies"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "CSC 445": {
    code: "CSC 445",
    name: "Computational Complexity & Modeling",
    credits: 1,
    prerequisites: ["CSC 246", "MAT 216"],
    waysOfKnowing: ["Quantitative Focus", "Applied Studies"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "CSC 450": {
    code: "CSC 450",
    name: "Computer Security",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 493": {
    code: "CSC 493",
    name: "Computing Design Practicum",
    credits: 1,
    prerequisites: ["CSC 246"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 495": {
    code: "CSC 495",
    name: "Internship",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // Math Courses
  "MAT 105": {
    code: "MAT 105",
    name: "Intro to Discrete Math",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "MAT 115": {
    code: "MAT 115",
    name: "College Algebra with Modeling",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "MAT 135": {
    code: "MAT 135",
    name: "Calculus I",
    credits: 1,
    prerequisites: ["MAT 115"],
    waysOfKnowing: ["Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "MAT 216": {
    code: "MAT 216",
    name: "Discrete Mathematics",
    credits: 1,
    prerequisites: ["MAT 115"],
    waysOfKnowing: ["Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "MAT 225": {
    code: "MAT 225",
    name: "Calculus II",
    credits: 1,
    prerequisites: ["MAT 135"],
    waysOfKnowing: ["Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "MAT 312": {
    code: "MAT 312",
    name: "Operations Research",
    credits: 1,
    prerequisites: ["MAT 216"],
    waysOfKnowing: ["Quantitative Focus", "Applied Studies"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "MAT 415": {
    code: "MAT 415",
    name: "Combinatorics",
    credits: 1,
    prerequisites: ["MAT 216"],
    waysOfKnowing: ["Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },

  // Biology Courses
  "BIO 100": {
    code: "BIO 100",
    name: "Introduction to Biology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 110": {
    code: "BIO 110",
    name: "Modern Biology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 113": {
    code: "BIO 113",
    name: "Experimental Zoology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 114": {
    code: "BIO 114",
    name: "Botany",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 207": {
    code: "BIO 207",
    name: "Pathophysiology: Altered Health",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },
  "BIO 220": {
    code: "BIO 220",
    name: "Comparative Vertebrate Anatomy",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 222": {
    code: "BIO 222",
    name: "Microbiology",
    credits: 1,
    prerequisites: ["BIO 110", "CHM 131"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 306": {
    code: "BIO 306",
    name: "Histology and Histotechnique",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 310": {
    code: "BIO 310",
    name: "Ecology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "BIO 323": {
    code: "BIO 323",
    name: "Principles of Physiology",
    credits: 1,
    prerequisites: ["BIO 110", "CHM 131"],
    waysOfKnowing: ["Natural Science"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },
  "BIO 324": {
    code: "BIO 324",
    name: "Parasitology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 325": {
    code: "BIO 325",
    name: "Neurobiology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 327": {
    code: "BIO 327",
    name: "Herpetology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 330": {
    code: "BIO 330",
    name: "Genetics",
    credits: 1,
    prerequisites: ["BIO 110", "CHM 131"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 331": {
    code: "BIO 331",
    name: "Developmental Biology",
    credits: 1,
    prerequisites: ["BIO 110", "BIO 330"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 332": {
    code: "BIO 332",
    name: "Mammalogy",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 338": {
    code: "BIO 338",
    name: "Ornithology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 342": {
    code: "BIO 342",
    name: "Field Botany",
    credits: 1,
    prerequisites: ["BIO 114"],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "BIO 344": {
    code: "BIO 344",
    name: "Dendrology & Forest Ecology",
    credits: 1,
    prerequisites: ["BIO 114"],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "BIO 346": {
    code: "BIO 346",
    name: "Conservation Biology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "BIO 441": {
    code: "BIO 441",
    name: "Cell and Molecular Biology",
    credits: 1,
    prerequisites: ["BIO 330", "CHM 221"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 494": {
    code: "BIO 494",
    name: "Evolution",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // Chemistry Courses
  "CHM 131": {
    code: "CHM 131",
    name: "Accelerated General Chemistry",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 221": {
    code: "CHM 221",
    name: "Organic Chemistry I",
    credits: 1,
    prerequisites: ["CHM 131"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 222": {
    code: "CHM 222",
    name: "Organic Chemistry II",
    credits: 1,
    prerequisites: ["CHM 221"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 340": {
    code: "CHM 340",
    name: "Biochemistry I",
    credits: 1,
    prerequisites: ["CHM 222", "BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 345": {
    code: "CHM 345",
    name: "Introduction to Biochemistry",
    credits: 1,
    prerequisites: ["CHM 222"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 440": {
    code: "CHM 440",
    name: "Biochemistry II",
    credits: 1,
    prerequisites: ["CHM 340"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // Psychology Courses
  "PSY 100": {
    code: "PSY 100",
    name: "General Psychology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 207": {
    code: "PSY 207",
    name: "Principles of Learning w/ Lab",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 208": {
    code: "PSY 208",
    name: "Cognitive Psychology with Lab",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 209": {
    code: "PSY 209",
    name: "Social Psychology w/ Lab",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "PSY 210": {
    code: "PSY 210",
    name: "Ind/Org Psychology with Lab",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 212": {
    code: "PSY 212",
    name: "Behavioral Neuroscience w/ Lab",
    credits: 1,
    prerequisites: ["PSY 100", "BIO 110"],
    waysOfKnowing: ["Social Science", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 214": {
    code: "PSY 214",
    name: "Ethology with Lab",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 225": {
    code: "PSY 225",
    name: "Stats & Research Methods I",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science", "Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "PSY 244": {
    code: "PSY 244",
    name: "Developmental Psychology with Lab",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 325": {
    code: "PSY 325",
    name: "Stats & Research Methods II",
    credits: 1,
    prerequisites: ["PSY 225"],
    waysOfKnowing: ["Social Science", "Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "PSY 424": {
    code: "PSY 424",
    name: "Senior Research",
    credits: 1,
    prerequisites: ["PSY 325"],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // African American Studies Courses
  "AFR 100": {
    code: "AFR 100",
    name: "Models & Mentors for Success",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 103": {
    code: "AFR 103",
    name: "Survey of African History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["International"],
    additional: [],
  },
  "AFR 132": {
    code: "AFR 132",
    name: "Intro to Race in America",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 135": {
    code: "AFR 135",
    name: "African-Amer Women Writers",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: ["Writing"],
    additional: [],
  },
  "AFR 136": {
    code: "AFR 136",
    name: "African Traditional Religion",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Seeking Meaning", "Beyond the Borders"],
    richnesses: ["International"],
    additional: [],
  },
  "AFR 138": {
    code: "AFR 138",
    name: "Black Music Ensemble",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts", "Cultural & Ethnic Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "AFR 141": {
    code: "AFR 141",
    name: "African-American Literature",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: ["Writing"],
    additional: [],
  },
  "AFR 165": {
    code: "AFR 165",
    name: "Intro to African-Amer History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 200": {
    code: "AFR 200",
    name: "Readings in Black Psychology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 201": {
    code: "AFR 201",
    name: "Food/Agriculture Africa",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: ["Beyond the Borders", "Sustainability"],
    richnesses: ["International"],
    additional: [],
  },
  "AFR 202": {
    code: "AFR 202",
    name: "Women African-Amer Politics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 204": {
    code: "AFR 204",
    name: "African Amer Intellectual Thought",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 212": {
    code: "AFR 212",
    name: "Literature of Caribbean Women",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity", "Beyond the Borders"],
    richnesses: ["Writing", "International"],
    additional: [],
  },
  "AFR 222": {
    code: "AFR 222",
    name: "Intro to African-American Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 225": {
    code: "AFR 225",
    name: "Environmental Justice",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: ["Power & Equity", "Sustainability"],
    richnesses: [],
    additional: [],
  },
  "AFR 230": {
    code: "AFR 230",
    name: "African Amer in Appalachia",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 234": {
    code: "AFR 234",
    name: "African-Amer Music: Overview",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts", "Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 238": {
    code: "AFR 238",
    name: "African Amer Religious Traditions",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Seeking Meaning", "Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 242": {
    code: "AFR 242",
    name: "African American Cinema",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts", "Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 245": {
    code: "AFR 245",
    name: "Black Urban History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 255": {
    code: "AFR 255",
    name: "Readings Moorish History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["International"],
    additional: [],
  },
  "AFR 350": {
    code: "AFR 350",
    name: "Sem in Afr & Afr-Amer Studies",
    credits: 1,
    prerequisites: ["AFR 222"],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 356": {
    code: "AFR 356",
    name: "Sem African-Amer History",
    credits: 1,
    prerequisites: ["AFR 165"],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 450": {
    code: "AFR 450",
    name: "Sem in Afr & Afr-Amer Studies II",
    credits: 1,
    prerequisites: ["AFR 350"],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },

  // Physics
  "PHY 127": {
    code: "PHY 127",
    name: "General Physics I",
    credits: 1,
    prerequisites: ["MAT 115"],
    waysOfKnowing: ["Natural Science", "Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "PHY 221": {
    code: "PHY 221",
    name: "Intro Physics I with Calculus",
    credits: 1,
    prerequisites: ["MAT 135"],
    waysOfKnowing: ["Natural Science", "Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "PHY 340": {
    code: "PHY 340",
    name: "Biophysics",
    credits: 1,
    prerequisites: ["PHY 221", "BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // Other
  "SENS 226": {
    code: "SENS 226",
    name: "Coral Reef Ecosystems",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability", "Beyond the Borders"],
    richnesses: ["International"],
    additional: [],
  },
  "SENS 320": {
    code: "SENS 320",
    name: "Intro to GIS",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies", "Quantitative Focus"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
  "ANR 310": {
    code: "ANR 310",
    name: "Nutritional Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },
  "CFS 221": {
    code: "CFS 221",
    name: "Fundamentals of Nutrition",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },
  "ECO 250": {
    code: "ECO 250",
    name: "Applied Statistics",
    credits: 1,
    prerequisites: ["MAT 115"],
    waysOfKnowing: ["Quantitative Focus", "Social Science"],
    values: [],
    richnesses: ["Quantitative"],
    additional: [],
  },
};