// Course catalog with GEM attributes and prerequisites
// Based on Berea College course offerings

import type { Course } from "./types";

export const COURSE_CATALOG: Record<string, Course> = {
  // CSC Courses
  "CSC 110": {
    code: "CSC 110",
    name: "Craft of Computing",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 111": {
    code: "CSC 111",
    name: "Storytelling-Comp Animation",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 114": {
    code: "CSC 114",
    name: "Business App & Programming",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 121": {
    code: "CSC 121",
    name: "Introduction to Game Design",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts", "Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 124": {
    code: "CSC 124",
    name: "Building Better Apps",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 126": {
    code: "CSC 126",
    name: "Intro to Robotics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 127": {
    code: "CSC 127",
    name: "Intro to Web Design",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts", "Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 226": {
    code: "CSC 226",
    name: "Software Design & Implement",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 236": {
    code: "CSC 236",
    name: "Data Structures",
    credits: 1,
    prerequisites: ["CSC 226"],
    waysOfKnowing: ["Applied Studies", "Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "CSC 246": {
    code: "CSC 246",
    name: "Scalable Algorithms & Objects",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies", "Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "CSC 300": {
    code: "CSC 300",
    name: "Embedded Systems",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 301": {
    code: "CSC 301",
    name: "Human-Centered Computing",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies", "Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "CSC 303": {
    code: "CSC 303",
    name: "Theory of Computation",
    credits: 1,
    prerequisites: ["CSC 236", "MAT 216"],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "CSC 330": {
    code: "CSC 330",
    name: "Database Systems",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 335": {
    code: "CSC 335",
    name: "Computer Organization",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 410": {
    code: "CSC 410",
    name: "Computational Intelligence",
    credits: 1,
    prerequisites: ["CSC 236", "MAT 216"],
    waysOfKnowing: ["Applied Studies", "Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "CSC 412": {
    code: "CSC 412",
    name: "Networking",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 420": {
    code: "CSC 420",
    name: "Programming Languages",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 425": {
    code: "CSC 425",
    name: "Operating Systems & VMs",
    credits: 1,
    prerequisites: ["CSC 335"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 426": {
    code: "CSC 426",
    name: "Open Source Software Engineering",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 433": {
    code: "CSC 433",
    name: "Numerical Analysis",
    credits: 1,
    prerequisites: ["MAT 225", "CSC 236"],
    waysOfKnowing: ["Quantitative Reasoning", "Applied Studies"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "CSC 440": {
    code: "CSC 440",
    name: "Design & Analysis of Algorithms",
    credits: 1,
    prerequisites: ["CSC 246", "MAT 216"],
    waysOfKnowing: ["Quantitative Reasoning", "Applied Studies"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "CSC 445": {
    code: "CSC 445",
    name: "Computational Complexity & Modeling",
    credits: 1,
    prerequisites: ["CSC 246", "MAT 216"],
    waysOfKnowing: ["Quantitative Reasoning", "Applied Studies"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "CSC 450": {
    code: "CSC 450",
    name: "Computer Security",
    credits: 1,
    prerequisites: ["CSC 236"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 493": {
    code: "CSC 493",
    name: "Computing Design Practicum",
    credits: 1,
    prerequisites: ["CSC 246"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CSC 495": {
    code: "CSC 495",
    name: "Internship",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // Math Courses
  "MAT 105": {
    code: "MAT 105",
    name: "Intro to Discrete Math",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "MAT 115": {
    code: "MAT 115",
    name: "College Algebra with Modeling",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "MAT 135": {
    code: "MAT 135",
    name: "Calculus I",
    credits: 1,
    prerequisites: ["MAT 115"],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "MAT 216": {
    code: "MAT 216",
    name: "Discrete Mathematics",
    credits: 1,
    prerequisites: ["MAT 115"],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "MAT 225": {
    code: "MAT 225",
    name: "Calculus II",
    credits: 1,
    prerequisites: ["MAT 135"],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "MAT 312": {
    code: "MAT 312",
    name: "Operations Research",
    credits: 1,
    prerequisites: ["MAT 216"],
    waysOfKnowing: ["Quantitative Reasoning", "Applied Studies"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "MAT 415": {
    code: "MAT 415",
    name: "Combinatorics",
    credits: 1,
    prerequisites: ["MAT 216"],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },

  // Biology Courses
  "BIO 100": {
    code: "BIO 100",
    name: "Introduction to Biology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 110": {
    code: "BIO 110",
    name: "Modern Biology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 113": {
    code: "BIO 113",
    name: "Experimental Zoology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 114": {
    code: "BIO 114",
    name: "Botany",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 207": {
    code: "BIO 207",
    name: "Pathophysiology: Altered Health",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },
  "BIO 220": {
    code: "BIO 220",
    name: "Comparative Vertebrate Anatomy",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 222": {
    code: "BIO 222",
    name: "Microbiology",
    credits: 1,
    prerequisites: ["BIO 110", "CHM 131"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 306": {
    code: "BIO 306",
    name: "Histology and Histotechnique",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 310": {
    code: "BIO 310",
    name: "Ecology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "BIO 323": {
    code: "BIO 323",
    name: "Principles of Physiology",
    credits: 1,
    prerequisites: ["BIO 110", "CHM 131"],
    waysOfKnowing: ["Natural Science"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },
  "BIO 324": {
    code: "BIO 324",
    name: "Parasitology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 325": {
    code: "BIO 325",
    name: "Neurobiology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 327": {
    code: "BIO 327",
    name: "Herpetology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 330": {
    code: "BIO 330",
    name: "Genetics",
    credits: 1,
    prerequisites: ["BIO 110", "CHM 131"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 331": {
    code: "BIO 331",
    name: "Developmental Biology",
    credits: 1,
    prerequisites: ["BIO 110", "BIO 330"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 332": {
    code: "BIO 332",
    name: "Mammalogy",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 338": {
    code: "BIO 338",
    name: "Ornithology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 342": {
    code: "BIO 342",
    name: "Field Botany",
    credits: 1,
    prerequisites: ["BIO 114"],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "BIO 344": {
    code: "BIO 344",
    name: "Dendrology & Forest Ecology",
    credits: 1,
    prerequisites: ["BIO 114"],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "BIO 346": {
    code: "BIO 346",
    name: "Conservation Biology",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "BIO 441": {
    code: "BIO 441",
    name: "Cell and Molecular Biology",
    credits: 1,
    prerequisites: ["BIO 330", "CHM 221"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 494": {
    code: "BIO 494",
    name: "Evolution",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // Chemistry Courses
  "CHM 131": {
    code: "CHM 131",
    name: "Accelerated General Chemistry",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 221": {
    code: "CHM 221",
    name: "Organic Chemistry I",
    credits: 1,
    prerequisites: ["CHM 131"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 222": {
    code: "CHM 222",
    name: "Organic Chemistry II",
    credits: 1,
    prerequisites: ["CHM 221"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 340": {
    code: "CHM 340",
    name: "Biochemistry I",
    credits: 1,
    prerequisites: ["CHM 222", "BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 345": {
    code: "CHM 345",
    name: "Introduction to Biochemistry",
    credits: 1,
    prerequisites: ["CHM 222"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 440": {
    code: "CHM 440",
    name: "Biochemistry II",
    credits: 1,
    prerequisites: ["CHM 340"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // Psychology Courses
  "PSY 100": {
    code: "PSY 100",
    name: "General Psychology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 207": {
    code: "PSY 207",
    name: "Principles of Learning w/ Lab",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 208": {
    code: "PSY 208",
    name: "Cognitive Psychology with Lab",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 209": {
    code: "PSY 209",
    name: "Social Psychology w/ Lab",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "PSY 210": {
    code: "PSY 210",
    name: "Ind/Org Psychology with Lab",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 212": {
    code: "PSY 212",
    name: "Behavioral Neuroscience w/ Lab",
    credits: 1,
    prerequisites: ["PSY 100", "BIO 110"],
    waysOfKnowing: ["Social Science", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 214": {
    code: "PSY 214",
    name: "Ethology with Lab",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science", "Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 225": {
    code: "PSY 225",
    name: "Stats & Research Methods I",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science", "Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "PSY 244": {
    code: "PSY 244",
    name: "Developmental Psychology with Lab",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSY 325": {
    code: "PSY 325",
    name: "Stats & Research Methods II",
    credits: 1,
    prerequisites: ["PSY 225"],
    waysOfKnowing: ["Social Science", "Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "PSY 424": {
    code: "PSY 424",
    name: "Senior Research",
    credits: 1,
    prerequisites: ["PSY 325"],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // African American Studies Courses
  "AFR 100": {
    code: "AFR 100",
    name: "Models & Mentors for Success",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 103": {
    code: "AFR 103",
    name: "Survey of African History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "AFR 132": {
    code: "AFR 132",
    name: "Intro to Race in America",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 135": {
    code: "AFR 135",
    name: "African-Amer Women Writers",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: ["Writing"],
    additional: [],
  },
  "AFR 136": {
    code: "AFR 136",
    name: "African Traditional Religion",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Seeking Meaning", "Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "AFR 138": {
    code: "AFR 138",
    name: "Black Music Ensemble",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts", "Cultural & Ethnic Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "AFR 141": {
    code: "AFR 141",
    name: "African-American Literature",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: ["Writing"],
    additional: [],
  },
  "AFR 165": {
    code: "AFR 165",
    name: "Intro to Afr-Amer History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 167": {
    code: "AFR 167",
    name: "Survey Africana Womanism",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Beyond the Borders"],
    richnesses: [],
    additional: [],
  },
  "AFR 186": {
    code: "AFR 186",
    name: "Intro to Africana Womanism",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "AFR 200": {
    code: "AFR 200",
    name: "Readings in Black Psychology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 201": {
    code: "AFR 201",
    name: "Food/Agriculture Africa",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: ["Beyond the Borders", "Sustainability"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "AFR 202": {
    code: "AFR 202",
    name: "Women African-Amer Politics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 204": {
    code: "AFR 204",
    name: "African Amer Intellectual Thought",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: ["Writing", "Internationally Rich"],
    additional: [],
  },
  "AFR 215": {
    code: "AFR 215",
    name: "Black Popular Culture & Media",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 212": {
    code: "AFR 212",
    name: "Literature of Caribbean Women",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity", "Beyond the Borders"],
    richnesses: ["Writing", "Internationally Rich"],
    additional: [],
  },
  "AFR 222": {
    code: "AFR 222",
    name: "Intro to African-American Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 225": {
    code: "AFR 225",
    name: "Environmental Justice",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: ["Power & Equity", "Sustainability"],
    richnesses: [],
    additional: [],
  },
  "AFR 230": {
    code: "AFR 230",
    name: "African Amer in Appalachia",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 234": {
    code: "AFR 234",
    name: "African-Amer Music: Overview",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts", "Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 238": {
    code: "AFR 238",
    name: "African Amer Religious Traditions",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Seeking Meaning", "Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 286": {
    code: "AFR 286",
    name: "Black Girlhood Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 242": {
    code: "AFR 242",
    name: "African American Cinema",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts", "Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 245": {
    code: "AFR 245",
    name: "Black Urban History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 255": {
    code: "AFR 255",
    name: "Afr. Muslims in Europe Med Era",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "AFR 350": {
    code: "AFR 350",
    name: "Sem in Afr & Afr-Amer Studies",
    credits: 1,
    prerequisites: ["AFR 222"],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 356": {
    code: "AFR 356",
    name: "Sem African-Amer History",
    credits: 1,
    prerequisites: ["AFR 165"],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 207": {
    code: "AFR 207",
    name: "Black Education",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 248": {
    code: "AFR 248",
    name: "Black & Indigenous Approaches",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "AFR 306": {
    code: "AFR 306",
    name: "Black Resistance-Black Futures",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: ["ALE"],
  },
  "AFR 309": {
    code: "AFR 309",
    name: "Civil Rights Seminar",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Power & Equity"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "AFR 450": {
    code: "AFR 450",
    name: "Sem in Afr & Afr-Amer Studies II",
    credits: 1,
    prerequisites: ["AFR 350"],
    waysOfKnowing: ["Applied Studies"],
    values: ["Power & Equity"],
    richnesses: ["Writing"],
    additional: [],
  },

  // Agriculture & Natural Resources Courses
  "AGR 100": {
    code: "AGR 100",
    name: "Introduction to Agriculture & Natural Resources",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "AGR 130": {
    code: "AGR 130",
    name: "Plant Science",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: [],
    richnesses: [],
    additional: [],
  },
  "AGR 201": {
    code: "AGR 201",
    name: "Food & Agriculture in Africa",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: ["Power & Equity"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },

  // Physics
  "PHY 127": {
    code: "PHY 127",
    name: "General Physics I",
    credits: 1,
    prerequisites: ["MAT 115"],
    waysOfKnowing: ["Natural Science", "Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "PHY 221": {
    code: "PHY 221",
    name: "Intro Physics I with Calculus",
    credits: 1,
    prerequisites: ["MAT 135"],
    waysOfKnowing: ["Natural Science", "Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "PHY 340": {
    code: "PHY 340",
    name: "Biophysics",
    credits: 1,
    prerequisites: ["PHY 221", "BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // Other
  "SENS 226": {
    code: "SENS 226",
    name: "Coral Reef Ecosystems",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability", "Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "SENS 320": {
    code: "SENS 320",
    name: "Intro to GIS",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies", "Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "ANR 310": {
    code: "ANR 310",
    name: "Nutritional Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },
  "CFS 221": {
    code: "CFS 221",
    name: "Fundamentals of Nutrition",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },
  "ECO 250": {
    code: "ECO 250",
    name: "Applied Statistics",
    credits: 1,
    prerequisites: ["MAT 115"],
    waysOfKnowing: ["Quantitative Reasoning", "Social Science"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },

  // ── ANR (Agriculture & Natural Resources) ───────────────────────────
  "ANR 100": {
    code: "ANR 100",
    name: "Introduction to Agriculture",
    credits: 0.5,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ANR 110": {
    code: "ANR 110",
    name: "Intro to Natural Resources",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ANR 240": {
    code: "ANR 240",
    name: "Ecology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "ANR 265": {
    code: "ANR 265",
    name: "Sustainable Food Systems",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "ANR 330": {
    code: "ANR 330",
    name: "Natural Resource Management",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ANR 375": {
    code: "ANR 375",
    name: "Agroecology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },

  // ── APS (Appalachian Studies) ────────────────────────────────────────
  "APS 100": {
    code: "APS 100",
    name: "Introduction to Appalachian Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "APS 140": {
    code: "APS 140",
    name: "Appalachian Literature",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Power & Equity"],
    richnesses: ["Writing"],
    additional: [],
  },
  "APS 210": {
    code: "APS 210",
    name: "Appalachian Society",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "APS 224": {
    code: "APS 224",
    name: "Appalachian Arts & Culture",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "APS 225": {
    code: "APS 225",
    name: "Appalachian Environment & Culture",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },

  // ── ARH (Art History) ────────────────────────────────────────────────
  "ARH 121": {
    code: "ARH 121",
    name: "Survey of Art History I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ARH 130": {
    code: "ARH 130",
    name: "Survey of Non-Western Art",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "ARH 239": {
    code: "ARH 239",
    name: "Art & Religion",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities", "Social Science"],
    values: ["Seeking Meaning"],
    richnesses: [],
    additional: [],
  },
  "ARH 255": {
    code: "ARH 255",
    name: "Contemporary Art & Social Justice",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Power & Equity"],
    richnesses: ["Writing"],
    additional: [],
  },
  "ARH 262": {
    code: "ARH 262",
    name: "Asian Art History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "ARH 263": {
    code: "ARH 263",
    name: "African Art History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "ARH 265": {
    code: "ARH 265",
    name: "Latin American Art History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },

  // ── ART (Studio Art) ────────────────────────────────────────────────
  "ART 134": {
    code: "ART 134",
    name: "Drawing I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 135": {
    code: "ART 135",
    name: "Painting I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 136": {
    code: "ART 136",
    name: "Sculpture I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 137": {
    code: "ART 137",
    name: "Printmaking I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 200C": {
    code: "ART 200C",
    name: "Ceramics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 200F": {
    code: "ART 200F",
    name: "Fiber Arts",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 211": {
    code: "ART 211",
    name: "Drawing II",
    credits: 1,
    prerequisites: ["ART 134"],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 216": {
    code: "ART 216",
    name: "Painting II",
    credits: 1,
    prerequisites: ["ART 135"],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 225": {
    code: "ART 225",
    name: "Photography I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 230": {
    code: "ART 230",
    name: "Digital Art",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 411": {
    code: "ART 411",
    name: "Advanced Drawing",
    credits: 1,
    prerequisites: ["ART 211"],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 416": {
    code: "ART 416",
    name: "Advanced Painting",
    credits: 1,
    prerequisites: ["ART 216"],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 425": {
    code: "ART 425",
    name: "Advanced Photography",
    credits: 1,
    prerequisites: ["ART 225"],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ART 430": {
    code: "ART 430",
    name: "Advanced Digital Art",
    credits: 1,
    prerequisites: ["ART 230"],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── AST (Asian Studies) ──────────────────────────────────────────────
  "AST 122": {
    code: "AST 122",
    name: "Introduction to Asian Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "AST 132": {
    code: "AST 132",
    name: "Asian Religions",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: ["Seeking Meaning"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "AST 229": {
    code: "AST 229",
    name: "East Asian Literature",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["Writing", "Internationally Rich"],
    additional: [],
  },
  "AST 271": {
    code: "AST 271",
    name: "Asian Philosophy",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: ["Seeking Meaning"],
    richnesses: ["Writing", "Internationally Rich"],
    additional: [],
  },
  "AST 325J": {
    code: "AST 325J",
    name: "Japanese Culture & Society",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["Writing", "Internationally Rich"],
    additional: [],
  },
  "AST 401": {
    code: "AST 401",
    name: "Advanced Topics in Asian Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── BIO (additional courses) ─────────────────────────────────────────
  "BIO 202": {
    code: "BIO 202",
    name: "Genetics",
    credits: 1,
    prerequisites: ["BIO 110"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BIO 286": {
    code: "BIO 286",
    name: "Environmental Biology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── BUS (Business) ───────────────────────────────────────────────────
  "BUS 114": {
    code: "BUS 114",
    name: "Introduction to Business",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BUS 120": {
    code: "BUS 120",
    name: "Financial Accounting",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "BUS 130": {
    code: "BUS 130",
    name: "Managerial Accounting",
    credits: 1,
    prerequisites: ["BUS 120"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "BUS 240": {
    code: "BUS 240",
    name: "Principles of Management",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BUS 315": {
    code: "BUS 315",
    name: "Business Law",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BUS 324": {
    code: "BUS 324",
    name: "Marketing",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BUS 326": {
    code: "BUS 326",
    name: "Finance",
    credits: 1,
    prerequisites: ["BUS 120"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "BUS 336": {
    code: "BUS 336",
    name: "Organizational Behavior",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BUS 346": {
    code: "BUS 346",
    name: "Operations Management",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "BUS 363": {
    code: "BUS 363",
    name: "Human Resource Management",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "BUS 366": {
    code: "BUS 366",
    name: "Investments",
    credits: 1,
    prerequisites: ["BUS 326"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "BUS 371": {
    code: "BUS 371",
    name: "International Business",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "BUS 475": {
    code: "BUS 475",
    name: "Business Analytics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── CFS (Child & Family Studies) ────────────────────────────────────
  "CFS 130": {
    code: "CFS 130",
    name: "Introduction to Child Development",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },
  "CFS 145": {
    code: "CFS 145",
    name: "Family Resource Management",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "CFS 207": {
    code: "CFS 207",
    name: "Family Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CFS 210": {
    code: "CFS 210",
    name: "Parenting",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CFS 300": {
    code: "CFS 300",
    name: "Diversity in Families",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CFS 317": {
    code: "CFS 317",
    name: "Child Guidance",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CFS 350": {
    code: "CFS 350",
    name: "Children & Social Policy",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "CFS 366": {
    code: "CFS 366",
    name: "Global Perspectives on Families",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: [],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "CFS 441": {
    code: "CFS 441",
    name: "Advanced Topics in Child & Family Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CFS 480": {
    code: "CFS 480",
    name: "Family Policy & Advocacy",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },

  // ── CHI (Chinese) ────────────────────────────────────────────────────
  "CHI 101": {
    code: "CHI 101",
    name: "Elementary Chinese I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHI 103": {
    code: "CHI 103",
    name: "Elementary Chinese II",
    credits: 1,
    prerequisites: ["CHI 101"],
    waysOfKnowing: ["Applied Studies"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },

  // ── CHM (additional courses) ─────────────────────────────────────────
  "CHM 101": {
    code: "CHM 101",
    name: "Introduction to Chemistry",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 311": {
    code: "CHM 311",
    name: "Organic Chemistry I",
    credits: 1,
    prerequisites: ["CHM 222"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 362": {
    code: "CHM 362",
    name: "Biochemistry",
    credits: 1,
    prerequisites: ["CHM 311"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 370": {
    code: "CHM 370",
    name: "Chemistry Research I",
    credits: 0.5,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "CHM 470": {
    code: "CHM 470",
    name: "Chemistry Research II",
    credits: 0.5,
    prerequisites: ["CHM 370"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── CLS (Classical Studies) ──────────────────────────────────────────
  "CLS 222": {
    code: "CLS 222",
    name: "Classical Mythology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Seeking Meaning"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },

  // ── COM (Communication) ──────────────────────────────────────────────
  "COM 100": {
    code: "COM 100",
    name: "Introduction to Communication",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "COM 104": {
    code: "COM 104",
    name: "Public Speaking",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "COM 113": {
    code: "COM 113",
    name: "Interpersonal Communication",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },
  "COM 207": {
    code: "COM 207",
    name: "Intercultural Communication",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: [],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "COM 211": {
    code: "COM 211",
    name: "Media Production",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies", "Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "COM 220": {
    code: "COM 220",
    name: "Mass Media & Society",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "COM 302": {
    code: "COM 302",
    name: "Community Media",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies", "Social Science"],
    values: [],
    richnesses: [],
    additional: ["ALE"],
  },
  "COM 410": {
    code: "COM 410",
    name: "Communication Research",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },

  // ── CSC (additional courses) ─────────────────────────────────────────
  "CSC 186": {
    code: "CSC 186",
    name: "Discrete Mathematics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "CSC 336": {
    code: "CSC 336",
    name: "Technology & Society",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── ECO (additional courses) ─────────────────────────────────────────
  "ECO 101": {
    code: "ECO 101",
    name: "Principles of Macroeconomics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "ECO 102": {
    code: "ECO 102",
    name: "Principles of Microeconomics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ECO 302": {
    code: "ECO 302",
    name: "Intermediate Macroeconomics",
    credits: 1,
    prerequisites: ["ECO 101"],
    waysOfKnowing: ["Social Science", "Quantitative Reasoning"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ECO 332": {
    code: "ECO 332",
    name: "Labor Economics",
    credits: 1,
    prerequisites: ["ECO 102"],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ECO 341": {
    code: "ECO 341",
    name: "Public Finance",
    credits: 1,
    prerequisites: ["ECO 102"],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "ECO 347": {
    code: "ECO 347",
    name: "Economic Development",
    credits: 1,
    prerequisites: ["ECO 102"],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "ECO 350": {
    code: "ECO 350",
    name: "Econometrics",
    credits: 1,
    prerequisites: ["ECO 250"],
    waysOfKnowing: ["Applied Studies", "Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich", "Writing"],
    additional: [],
  },

  // ── EDS (Education Studies) ──────────────────────────────────────────
  "EDS 150": {
    code: "EDS 150",
    name: "Introduction to Education",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "EDS 227": {
    code: "EDS 227",
    name: "Foundations of Education",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: [],
    richnesses: [],
    additional: [],
  },
  "EDS 228": {
    code: "EDS 228",
    name: "Educational Psychology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: [],
    richnesses: [],
    additional: [],
  },
  "EDS 324": {
    code: "EDS 324",
    name: "Teaching Reading & Writing",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "EDS 325": {
    code: "EDS 325",
    name: "Teaching Science",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "EDS 330": {
    code: "EDS 330",
    name: "Teaching Social Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "EDS 335": {
    code: "EDS 335",
    name: "Teaching Mathematics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "EDS 340": {
    code: "EDS 340",
    name: "Classroom Management",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "EDS 346": {
    code: "EDS 346",
    name: "Special Education",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "EDS 349": {
    code: "EDS 349",
    name: "Education & Society",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "EDS 471": {
    code: "EDS 471",
    name: "Student Teaching Seminar",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "EDS 472": {
    code: "EDS 472",
    name: "Student Teaching",
    credits: 3,
    prerequisites: ["EDS 471"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "EDS 479": {
    code: "EDS 479",
    name: "Teaching Internship",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "EDS 481": {
    code: "EDS 481",
    name: "Curriculum Design",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "EDS 482": {
    code: "EDS 482",
    name: "Advanced Student Teaching",
    credits: 3,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "EDS 487": {
    code: "EDS 487",
    name: "Secondary Student Teaching",
    credits: 3,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "EDS 488": {
    code: "EDS 488",
    name: "Education Capstone",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── ENG (English) ────────────────────────────────────────────────────
  "ENG 103": {
    code: "ENG 103",
    name: "World Literature",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "ENG 110": {
    code: "ENG 110",
    name: "College Writing",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "ENG 124": {
    code: "ENG 124",
    name: "Creative Writing I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "ENG 140": {
    code: "ENG 140",
    name: "Introduction to Literary Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Power & Equity"],
    richnesses: ["Writing"],
    additional: [],
  },
  "ENG 200E": {
    code: "ENG 200E",
    name: "Survey of English Literature",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "ENG 205": {
    code: "ENG 205",
    name: "American Literature I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ENG 210": {
    code: "ENG 210",
    name: "American Literature II",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ENG 225": {
    code: "ENG 225",
    name: "African American Literature",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "ENG 240": {
    code: "ENG 240",
    name: "Literature & Social Justice",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ENG 270": {
    code: "ENG 270",
    name: "Topics in Literature",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "ENG 282P": {
    code: "ENG 282P",
    name: "Creative Writing: Poetry",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "ENG 305": {
    code: "ENG 305",
    name: "Advanced Literary Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "ENG 340": {
    code: "ENG 340",
    name: "Topics in American Literature",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "ENG 382": {
    code: "ENG 382",
    name: "Advanced Creative Writing",
    credits: 1,
    prerequisites: ["ENG 124"],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ENG 470": {
    code: "ENG 470",
    name: "Senior Seminar in English",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },

  // ── ETAD (Educational Technology & Applied Design) ───────────────────
  "ETAD 118": {
    code: "ETAD 118",
    name: "Introduction to Design Thinking",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ETAD 130": {
    code: "ETAD 130",
    name: "Technology for Learning",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ETAD 140": {
    code: "ETAD 140",
    name: "Community Design",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts", "Applied Studies"],
    values: [],
    richnesses: [],
    additional: ["ALE"],
  },
  "ETAD 180": {
    code: "ETAD 180",
    name: "Digital Media Production",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts", "Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ETAD 202": {
    code: "ETAD 202",
    name: "Instructional Design",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ETAD 245": {
    code: "ETAD 245",
    name: "Data Visualization",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "ETAD 265": {
    code: "ETAD 265",
    name: "Applied Data Science",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies", "Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "ETAD 275": {
    code: "ETAD 275",
    name: "Environmental Data Analysis",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "ETAD 340": {
    code: "ETAD 340",
    name: "Advanced Digital Media",
    credits: 1,
    prerequisites: ["ETAD 180"],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ETAD 345": {
    code: "ETAD 345",
    name: "UX/UI Design",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ETAD 386": {
    code: "ETAD 386",
    name: "Technology & Education",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "ETAD 455": {
    code: "ETAD 455",
    name: "Advanced Data Analytics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "ETAD 470": {
    code: "ETAD 470",
    name: "Capstone in Applied Design",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── FRN (French) ─────────────────────────────────────────────────────
  "FRN 101": {
    code: "FRN 101",
    name: "Elementary French I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "FRN 103": {
    code: "FRN 103",
    name: "Elementary French II",
    credits: 1,
    prerequisites: ["FRN 101"],
    waysOfKnowing: ["Applied Studies"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "FRN 160": {
    code: "FRN 160",
    name: "Intermediate French I",
    credits: 1,
    prerequisites: ["FRN 103"],
    waysOfKnowing: [],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "FRN 260": {
    code: "FRN 260",
    name: "Intermediate French II",
    credits: 1,
    prerequisites: ["FRN 160"],
    waysOfKnowing: [],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "FRN 311": {
    code: "FRN 311",
    name: "Advanced French",
    credits: 1,
    prerequisites: ["FRN 260"],
    waysOfKnowing: [],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },

  // ── GEO (Geography) ──────────────────────────────────────────────────
  "GEO 101": {
    code: "GEO 101",
    name: "Physical Geography",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },

  // ── GST (General Studies) ────────────────────────────────────────────
  "GST 110A": {
    code: "GST 110A",
    name: "First Year Seminar",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "GST 167": {
    code: "GST 167",
    name: "Career Exploration",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── HHP (Health, Human Performance & Physical Education) ─────────────
  "HHP 125": {
    code: "HHP 125",
    name: "Personal Health",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },
  "HHP 244": {
    code: "HHP 244",
    name: "Community Health",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies", "Social Science"],
    values: [],
    richnesses: ["Writing"],
    additional: ["ALE"],
  },
  "HHP 248": {
    code: "HHP 248",
    name: "Global Health",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "HHP 249": {
    code: "HHP 249",
    name: "Health & Human Performance Topics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: [],
    richnesses: [],
    additional: [],
  },
  "HHP 254": {
    code: "HHP 254",
    name: "Kinesiology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "HHP 262": {
    code: "HHP 262",
    name: "Exercise Science",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "HHP 305": {
    code: "HHP 305",
    name: "Sport & Culture",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "HHP 345": {
    code: "HHP 345",
    name: "Research Methods in HHP",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "HHP 492": {
    code: "HHP 492",
    name: "Senior Capstone in HHP",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },

  // ── HIS (History) ────────────────────────────────────────────────────
  "HIS 122": {
    code: "HIS 122",
    name: "World History to 1500",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "HIS 124": {
    code: "HIS 124",
    name: "World History since 1500",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "HIS 126": {
    code: "HIS 126",
    name: "World History: Global Issues",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "HIS 161": {
    code: "HIS 161",
    name: "US History I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Power & Equity"],
    richnesses: ["Writing"],
    additional: [],
  },
  "HIS 165": {
    code: "HIS 165",
    name: "US History II",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Humanities"],
    values: ["Power & Equity"],
    richnesses: ["Writing"],
    additional: [],
  },
  "HIS 175": {
    code: "HIS 175",
    name: "History of Africa",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "HIS 200": {
    code: "HIS 200",
    name: "Historical Methods",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities", "Social Science"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "HIS 229": {
    code: "HIS 229",
    name: "History of Asia",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["Writing", "Internationally Rich"],
    additional: [],
  },
  "HIS 286": {
    code: "HIS 286",
    name: "Environmental History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Power & Equity", "Sustainability"],
    richnesses: [],
    additional: [],
  },
  "HIS 320": {
    code: "HIS 320",
    name: "Colonial & Post-Colonial History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["Writing", "Internationally Rich"],
    additional: [],
  },
  "HIS 335": {
    code: "HIS 335",
    name: "Modern European History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["Writing", "Internationally Rich"],
    additional: [],
  },
  "HIS 406": {
    code: "HIS 406",
    name: "Senior Seminar in History",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },

  // ── HLT (Health) ─────────────────────────────────────────────────────
  "HLT 109": {
    code: "HLT 109",
    name: "Introduction to Health Sciences",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "HLT 200": {
    code: "HLT 200",
    name: "Public Health",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: ["Holistic Wellness"],
    richnesses: ["Writing"],
    additional: [],
  },
  "HLT 210": {
    code: "HLT 210",
    name: "Epidemiology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "HLT 236": {
    code: "HLT 236",
    name: "Health Equity",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "HLT 400": {
    code: "HLT 400",
    name: "Advanced Public Health",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: ["Sustainability"],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },

  // ── JPN (Japanese) ───────────────────────────────────────────────────
  "JPN 101": {
    code: "JPN 101",
    name: "Elementary Japanese I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "JPN 103": {
    code: "JPN 103",
    name: "Elementary Japanese II",
    credits: 1,
    prerequisites: ["JPN 101"],
    waysOfKnowing: ["Applied Studies"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },

  // ── L&I (Learning & Inquiry) ─────────────────────────────────────────
  "L&I 100": {
    code: "L&I 100",
    name: "L&I: Explorations",
    credits: 1,
    prerequisites: [],
    learningInquiryCore: "Explorations",
    waysOfKnowing: [],
    values: [],
    richnesses: [],
    additional: [],
  },
  "L&I 200": {
    code: "L&I 200",
    name: "L&I: Discoveries",
    credits: 1,
    prerequisites: ["L&I 100"],
    learningInquiryCore: "Discoveries",
    waysOfKnowing: [],
    values: [],
    richnesses: [],
    additional: [],
  },
  "L&I 300": {
    code: "L&I 300",
    name: "L&I: Intersectional Justice in U.S.",
    credits: 1,
    prerequisites: ["L&I 200"],
    learningInquiryCore: "Intersectional Justice in U.S.",
    waysOfKnowing: [],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── LAT (Latin) ──────────────────────────────────────────────────────
  "LAT 101": {
    code: "LAT 101",
    name: "Elementary Latin I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── LES (Legal Studies) ──────────────────────────────────────────────
  "LES 370": {
    code: "LES 370",
    name: "Constitutional Law",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
  "LES 371": {
    code: "LES 371",
    name: "Civil Rights Law",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },

  // ── MAT (additional courses) ─────────────────────────────────────────
  "MAT 104": {
    code: "MAT 104",
    name: "Quantitative Reasoning",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "MAT 125": {
    code: "MAT 125",
    name: "Pre-Calculus",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "MAT 186": {
    code: "MAT 186",
    name: "Statistics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "MAT 201": {
    code: "MAT 201",
    name: "Applied Mathematics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MAT 214": {
    code: "MAT 214",
    name: "Calculus II",
    credits: 1,
    prerequisites: ["MAT 215"],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "MAT 337": {
    code: "MAT 337",
    name: "Linear Algebra",
    credits: 1,
    prerequisites: ["MAT 216"],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "MAT 426": {
    code: "MAT 426",
    name: "Real Analysis",
    credits: 1,
    prerequisites: ["MAT 337"],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich", "Writing"],
    additional: [],
  },
  "MAT 434": {
    code: "MAT 434",
    name: "Abstract Algebra",
    credits: 1,
    prerequisites: ["MAT 337"],
    waysOfKnowing: ["Quantitative Reasoning"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── MUS (Music) ──────────────────────────────────────────────────────
  "MUS 100": {
    code: "MUS 100",
    name: "Music Ensemble",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 103": {
    code: "MUS 103",
    name: "Music Appreciation",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 118": {
    code: "MUS 118",
    name: "Music Theory I",
    credits: 0.5,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 130A": {
    code: "MUS 130A",
    name: "Applied Music: Voice",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 130B": {
    code: "MUS 130B",
    name: "Applied Music: Piano",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 130C": {
    code: "MUS 130C",
    name: "Applied Music: Guitar",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 130D": {
    code: "MUS 130D",
    name: "Applied Music: Strings",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 130E": {
    code: "MUS 130E",
    name: "Applied Music: Woodwinds",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 130F": {
    code: "MUS 130F",
    name: "Applied Music: Brass",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 130G": {
    code: "MUS 130G",
    name: "Applied Music: Percussion",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 130H": {
    code: "MUS 130H",
    name: "Applied Music: Organ",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 130M": {
    code: "MUS 130M",
    name: "Applied Music: Music Technology",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 131": {
    code: "MUS 131",
    name: "Chamber Music",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 132": {
    code: "MUS 132",
    name: "Jazz Ensemble",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 135": {
    code: "MUS 135",
    name: "Concert Choir",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 200": {
    code: "MUS 200",
    name: "Music of the World",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 220": {
    code: "MUS 220",
    name: "Music Theory II",
    credits: 0.5,
    prerequisites: ["MUS 118"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 221": {
    code: "MUS 221",
    name: "Music Theory III",
    credits: 0.5,
    prerequisites: ["MUS 220"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 224": {
    code: "MUS 224",
    name: "Music of the African Diaspora",
    credits: 0.5,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 320": {
    code: "MUS 320",
    name: "Music Theory IV",
    credits: 0.5,
    prerequisites: ["MUS 221"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 321": {
    code: "MUS 321",
    name: "Advanced Music Theory",
    credits: 0.5,
    prerequisites: ["MUS 320"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 324": {
    code: "MUS 324",
    name: "Music Composition",
    credits: 0.5,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 335": {
    code: "MUS 335",
    name: "Music History I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 337": {
    code: "MUS 337",
    name: "Music History II",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "MUS 400": {
    code: "MUS 400",
    name: "Music Capstone",
    credits: 0.5,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── NUR (Nursing) ────────────────────────────────────────────────────
  "NUR 110": {
    code: "NUR 110",
    name: "Introduction to Nursing",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "NUR 201": {
    code: "NUR 201",
    name: "Nursing Fundamentals Lab",
    credits: 0.5,
    prerequisites: ["NUR 110"],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "NUR 225": {
    code: "NUR 225",
    name: "Health Assessment",
    credits: 1,
    prerequisites: ["NUR 110"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "NUR 301": {
    code: "NUR 301",
    name: "Adult Health Nursing I",
    credits: 1,
    prerequisites: ["NUR 225"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "NUR 351": {
    code: "NUR 351",
    name: "Adult Health Nursing II",
    credits: 1,
    prerequisites: ["NUR 301"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "NUR 352": {
    code: "NUR 352",
    name: "Nursing Clinical",
    credits: 0.5,
    prerequisites: ["NUR 301"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "NUR 400": {
    code: "NUR 400",
    name: "Senior Nursing Practicum",
    credits: 1.5,
    prerequisites: ["NUR 351"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "NUR 448": {
    code: "NUR 448",
    name: "Community Health Nursing",
    credits: 1,
    prerequisites: ["NUR 301"],
    waysOfKnowing: ["Applied Studies"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },

  // ── PHI (Philosophy) ─────────────────────────────────────────────────
  "PHI 106": {
    code: "PHI 106",
    name: "Introduction to Philosophy",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PHI 115": {
    code: "PHI 115",
    name: "Ethics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PHI 218": {
    code: "PHI 218",
    name: "Logic",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PHI 230": {
    code: "PHI 230",
    name: "Environmental Ethics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "PHI 271": {
    code: "PHI 271",
    name: "World Philosophy",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: ["Seeking Meaning"],
    richnesses: ["Writing", "Internationally Rich"],
    additional: [],
  },
  "PHI 305": {
    code: "PHI 305",
    name: "Advanced Topics in Philosophy",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── PHY (additional courses) ─────────────────────────────────────────
  "PHY 111": {
    code: "PHY 111",
    name: "Introduction to Physics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PHY 130": {
    code: "PHY 130",
    name: "College Physics I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science", "Quantitative Reasoning"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "PHY 186": {
    code: "PHY 186",
    name: "Environmental Physics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "PHY 222": {
    code: "PHY 222",
    name: "College Physics II",
    credits: 1,
    prerequisites: ["PHY 221"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "PHY 341": {
    code: "PHY 341",
    name: "Physics Research Lab",
    credits: 0.5,
    prerequisites: ["PHY 221"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "PHY 481": {
    code: "PHY 481",
    name: "Advanced Topics in Physics I",
    credits: 1,
    prerequisites: ["PHY 340"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "PHY 482": {
    code: "PHY 482",
    name: "Advanced Topics in Physics II",
    credits: 1,
    prerequisites: ["PHY 481"],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },

  // ── PSC (Political Science) ──────────────────────────────────────────
  "PSC 100": {
    code: "PSC 100",
    name: "Introduction to Political Science",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: ["Beyond the Borders"],
    richnesses: [],
    additional: [],
  },
  "PSC 110": {
    code: "PSC 110",
    name: "American Government",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSC 175": {
    code: "PSC 175",
    name: "International Relations",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "PSC 250": {
    code: "PSC 250",
    name: "Comparative Politics",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSC 319": {
    code: "PSC 319",
    name: "Political Theory",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSC 355": {
    code: "PSC 355",
    name: "Public Policy",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSC 480": {
    code: "PSC 480",
    name: "Senior Seminar in Political Science",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── PSJ (Peace & Social Justice) ────────────────────────────────────
  "PSJ 100": {
    code: "PSJ 100",
    name: "Introduction to Peace & Social Justice",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "PSJ 103": {
    code: "PSJ 103",
    name: "Racial Justice",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "PSJ 113": {
    code: "PSJ 113",
    name: "Conflict Resolution",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: [],
  },
  "PSJ 201": {
    code: "PSJ 201",
    name: "Topics in Peace & Social Justice",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSJ 225": {
    code: "PSJ 225",
    name: "Environmental Justice",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "PSJ 305": {
    code: "PSJ 305",
    name: "Nonviolence & Social Change",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "PSJ 450": {
    code: "PSJ 450",
    name: "Senior Seminar in Peace & Social Justice",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },

  // ── PSY (additional courses) ─────────────────────────────────────────
  "PSY 217": {
    code: "PSY 217",
    name: "Social Psychology",
    credits: 1,
    prerequisites: ["PSY 100"],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── REL (Religion) ───────────────────────────────────────────────────
  "REL 105": {
    code: "REL 105",
    name: "Introduction to Religion",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Seeking Meaning"],
    richnesses: [],
    additional: [],
  },
  "REL 211": {
    code: "REL 211",
    name: "World Religions",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Seeking Meaning"],
    richnesses: [],
    additional: [],
  },
  "REL 222": {
    code: "REL 222",
    name: "Religions of Asia",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Seeking Meaning"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "REL 228": {
    code: "REL 228",
    name: "Christianity",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Seeking Meaning"],
    richnesses: [],
    additional: [],
  },
  "REL 271": {
    code: "REL 271",
    name: "Religion & Philosophy",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: ["Seeking Meaning"],
    richnesses: ["Writing", "Internationally Rich"],
    additional: [],
  },

  // ── SENS (additional courses) ────────────────────────────────────────
  "SENS 100": {
    code: "SENS 100",
    name: "Introduction to Environmental Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "SENS 225": {
    code: "SENS 225",
    name: "Environmental Justice",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "SENS 345": {
    code: "SENS 345",
    name: "Environmental Policy",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "SENS 460": {
    code: "SENS 460",
    name: "Advanced Environmental Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Natural Science"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── SOC (Sociology) ──────────────────────────────────────────────────
  "SOC 100": {
    code: "SOC 100",
    name: "Introduction to Sociology",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "SOC 110": {
    code: "SOC 110",
    name: "Social Problems",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: ["Sustainability"],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "SOC 202": {
    code: "SOC 202",
    name: "Social Inequality",
    credits: 1,
    prerequisites: ["SOC 100"],
    waysOfKnowing: ["Social Science"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "SOC 220": {
    code: "SOC 220",
    name: "Race & Ethnicity",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "SOC 300": {
    code: "SOC 300",
    name: "Global Sociology",
    credits: 1,
    prerequisites: ["SOC 100"],
    waysOfKnowing: ["Cultural & Ethnic Studies", "Social Science"],
    values: [],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "SOC 335": {
    code: "SOC 335",
    name: "Sociological Research Methods",
    credits: 1,
    prerequisites: ["SOC 100"],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },

  // ── SPN (Spanish) ────────────────────────────────────────────────────
  "SPN 101": {
    code: "SPN 101",
    name: "Elementary Spanish I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "SPN 102": {
    code: "SPN 102",
    name: "Elementary Spanish II",
    credits: 1,
    prerequisites: ["SPN 101"],
    waysOfKnowing: ["Applied Studies"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "SPN 103": {
    code: "SPN 103",
    name: "Accelerated Elementary Spanish",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "SPN 310": {
    code: "SPN 310",
    name: "Spanish for the Community",
    credits: 1,
    prerequisites: ["SPN 103"],
    waysOfKnowing: ["Applied Studies"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: ["ALE"],
  },
  "SPN 312": {
    code: "SPN 312",
    name: "Advanced Spanish Composition",
    credits: 1,
    prerequisites: ["SPN 103"],
    waysOfKnowing: ["Applied Studies"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "SPN 330": {
    code: "SPN 330",
    name: "Survey of Spanish Literature",
    credits: 1,
    prerequisites: ["SPN 103"],
    waysOfKnowing: ["Applied Studies"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "SPN 340": {
    code: "SPN 340",
    name: "Latin American Literature",
    credits: 1,
    prerequisites: ["SPN 103"],
    waysOfKnowing: ["Humanities"],
    values: ["Beyond the Borders"],
    richnesses: ["Internationally Rich"],
    additional: [],
  },

  // ── THR (Theatre) ────────────────────────────────────────────────────
  "THR 105": {
    code: "THR 105",
    name: "Introduction to Theatre",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "THR 115": {
    code: "THR 115",
    name: "Acting I",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "THR 135": {
    code: "THR 135",
    name: "Technical Theatre",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "THR 186": {
    code: "THR 186",
    name: "Theatre Production",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "THR 200": {
    code: "THR 200",
    name: "Theatre & Culture",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "THR 213": {
    code: "THR 213",
    name: "Dramatic Literature",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "THR 220": {
    code: "THR 220",
    name: "Stage Management",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: ["Quantitatively Rich"],
    additional: [],
  },
  "THR 317": {
    code: "THR 317",
    name: "Advanced Acting",
    credits: 1,
    prerequisites: ["THR 115"],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "THR 321": {
    code: "THR 321",
    name: "Directing",
    credits: 1,
    prerequisites: ["THR 115"],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "THR 327": {
    code: "THR 327",
    name: "Playwriting",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: [],
  },

  // ── WELL (Wellness / Physical Activity) ──────────────────────────────
  "WELL 150": {
    code: "WELL 150",
    name: "Foundations of Wellness",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: ["Holistic Wellness"],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 200": {
    code: "WELL 200",
    name: "Physical Fitness",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: [],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 204": {
    code: "WELL 204",
    name: "Weight Training",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: [],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 206P": {
    code: "WELL 206P",
    name: "Pilates",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 206Y": {
    code: "WELL 206Y",
    name: "Yoga",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 206Z": {
    code: "WELL 206Z",
    name: "Zumba",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 209": {
    code: "WELL 209",
    name: "Swimming",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 213": {
    code: "WELL 213",
    name: "Tennis",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 217": {
    code: "WELL 217",
    name: "Racquetball",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 218": {
    code: "WELL 218",
    name: "Volleyball",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 222": {
    code: "WELL 222",
    name: "Basketball",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 224": {
    code: "WELL 224",
    name: "Dance",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 226": {
    code: "WELL 226",
    name: "Golf",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 228": {
    code: "WELL 228",
    name: "Martial Arts",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Creative Arts"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 236": {
    code: "WELL 236",
    name: "Hiking & Outdoor Recreation",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 238": {
    code: "WELL 238",
    name: "Soccer",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },
  "WELL 242": {
    code: "WELL 242",
    name: "Cycling",
    credits: 0.25,
    prerequisites: [],
    waysOfKnowing: ["Applied Studies"],
    values: [],
    richnesses: [],
    additional: ["Physical Activity"],
  },

  // ── WGS (Women's & Gender Studies) ───────────────────────────────────
  "WGS 103": {
    code: "WGS 103",
    name: "Introduction to Women's & Gender Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "WGS 124": {
    code: "WGS 124",
    name: "Feminist Theory",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "WGS 200": {
    code: "WGS 200",
    name: "Gender & Society",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "WGS 207": {
    code: "WGS 207",
    name: "Gender & Media",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Social Science"],
    values: [],
    richnesses: [],
    additional: [],
  },
  "WGS 211": {
    code: "WGS 211",
    name: "Women in Literature",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Humanities"],
    values: ["Seeking Meaning"],
    richnesses: [],
    additional: [],
  },
  "WGS 225": {
    code: "WGS 225",
    name: "Gender & Environment",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: ["Sustainability"],
    richnesses: [],
    additional: [],
  },
  "WGS 236": {
    code: "WGS 236",
    name: "Gender & Health Equity",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: [],
    values: ["Power & Equity"],
    richnesses: [],
    additional: [],
  },
  "WGS 366": {
    code: "WGS 366",
    name: "Global Gender Issues",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: [],
    richnesses: ["Internationally Rich"],
    additional: [],
  },
  "WGS 450": {
    code: "WGS 450",
    name: "Senior Seminar in Women's & Gender Studies",
    credits: 1,
    prerequisites: [],
    waysOfKnowing: ["Cultural & Ethnic Studies"],
    values: [],
    richnesses: ["Writing"],
    additional: [],
  },
};
