// Major requirements data for Berea College
// Based on Berea College Academic Catalog (current)

import type { Course, Major, Minor } from "./types";
import { COURSE_CATALOG } from "./course-catalog";

export const MAJORS: Record<string, Major> = {
  CSC: {
    code: "CSC",
    name: "Computer and Information Science",
    degree: "B.A.",
    totalMajorCredits: 12,
    requirements: [
      {
        category: "Exploratory Distribution",
        description: "One course from upper level CSC or the approved exploratory list",
        coursesRequired: 1,
        courses: [
          "CSC 110", "CSC 111", "CSC 114", "CSC 121", "CSC 124", 
          "CSC 126", "CSC 127", "ETAD 130", "ETAD 180", "ETAD 330", 
          "ETAD 382", "ETAD 455", "ETAD 460", "PHY 221", "SENS 320"
        ],
      },
      {
        category: "Required Core Courses",
        description: "Core programming and data structures",
        coursesRequired: 3,
        courses: ["CSC 226", "CSC 236", "CSC 246"],
        mustInclude: ["CSC 226", "CSC 236", "CSC 246"],
      },
      {
        category: "Capstone",
        description: "Computing Design Practicum or Internship",
        coursesRequired: 1,
        courses: ["CSC 493", "CSC 495"],
      },
      {
        category: "Upper Level Distribution",
        description: "Four upper-level courses with at least one from each category and one at 400 level",
        coursesRequired: 4,
        minUpperLevel: 1,
        courses: ["CSC 410", "CSC 420", "CSC 426", "CSC 433", "CSC 440", "CSC 445", "CSC 412", "CSC 425", "CSC 450"],
        selectFromCategories: [
          {
            category: "Design",
            min: 1,
            courses: ["CSC 301", "CSC 330", "CSC 410", "CSC 420", "CSC 426"],
          },
          {
            category: "Foundations",
            min: 1,
            courses: ["CSC 303", "CSC 433", "CSC 440", "CSC 445"],
          },
          {
            category: "Systems",
            min: 1,
            courses: ["CSC 300", "CSC 335", "CSC 412", "CSC 425", "CSC 450"],
          },
        ],
      },
      {
        category: "Collateral - Discrete Math",
        description: "One discrete mathematics course",
        coursesRequired: 1,
        courses: ["MAT 216", "MAT 312", "MAT 415"],
      },
      {
        category: "Collateral - Electronics",
        description: "One electricity/electronics course",
        coursesRequired: 1,
        courses: ["ETAD 265", "ETAD 460"],
      },
    ],
  },
  AFR: {
    code: "AFR",
    name: "African and African American Studies",
    degree: "B.A.",
    totalMajorCredits: 12,
    requirements: [
      {
        category: "Required Core",
        description: "Choose 1",
        coursesRequired: 1,
        courses: ["AFR 165", "AFR 166"],
      },
      {
        category: "Required Foundational",
        description: "All required",
        coursesRequired: 4,
        courses: ["AFR 103", "AFR 167", "AFR 222", "AFR 350"],
        mustInclude: ["AFR 103", "AFR 167", "AFR 222", "AFR 350"],
      },
      {
        category: "Distribution",
        description: "5 courses: at least 1 from 100-level, 2 from 200-level, 2 from 300-level",
        coursesRequired: 5,
        courses: ["AFR 100", "AFR 132", "AFR 135", "AFR 136", "AFR 138", "AFR 141", "AFR 200", "AFR 201", "AFR 202", "AFR 204", "AFR 207", "AFR 212", "AFR 225", "AFR 230", "AFR 234", "AFR 238", "AFR 242", "AFR 245", "AFR 248", "AFR 249", "AFR 255", "AFR 306", "AFR 309", "AFR 356"],
      },
      {
        category: "Capstone",
        description: "Senior seminar",
        coursesRequired: 1,
        courses: ["AFR 450"],
        mustInclude: ["AFR 450"],
      },
    ],
  },
  BIO: {
    code: "BIO",
    name: "Biology",
    degree: "B.A.",
    totalMajorCredits: 14,
    requirements: [
      {
        category: "Required Core",
        description: "Core Biology courses",
        coursesRequired: 5,
        courses: ["BIO 110", "BIO 113", "BIO 114", "BIO 330", "BIO 494"],
        mustInclude: ["BIO 110", "BIO 113", "BIO 114", "BIO 330", "BIO 494"],
      },
      {
        category: "Field Course",
        description: "One field biology course",
        coursesRequired: 1,
        courses: [
          "BIO 310",
          "BIO 324",
          "BIO 327",
          "BIO 332",
          "BIO 338",
          "BIO 342",
          "BIO 344",
          "SENS 226",
        ],
      },
      {
        category: "Distribution",
        description:
          "Four additional credits, at least two must be Biology courses",
        coursesRequired: 4,
        courses: [
          "BIO 207",
          "BIO 220",
          "BIO 222",
          "BIO 306",
          "BIO 310",
          "BIO 323",
          "BIO 324",
          "BIO 325",
          "BIO 327",
          "BIO 331",
          "BIO 332",
          "BIO 338",
          "BIO 342",
          "BIO 344",
          "BIO 346",
          "BIO 441",
          "ANR 310",
          "CHM 340",
          "CHM 345",
          "CHM 440",
          "CFS 221",
          "ECO 250",
          "PHY 340",
          "PSY 212",
          "SENS 226",
        ],
      },
      {
        category: "Collateral - Chemistry",
        description: "Required chemistry sequence",
        coursesRequired: 3,
        courses: ["CHM 131", "CHM 221", "CHM 222"],
        mustInclude: ["CHM 131", "CHM 221", "CHM 222"],
      },
      {
        category: "Collateral - Math",
        description: "College Algebra with Modeling",
        coursesRequired: 1,
        courses: ["MAT 115"],
        mustInclude: ["MAT 115"],
      },
    ],
  },
  PSY: {
    code: "PSY",
    name: "Psychology",
    degree: "B.A.",
    totalMajorCredits: 11,
    requirements: [
      {
        category: "Required Core",
        description: "Core Psychology courses",
        coursesRequired: 3,
        courses: ["PSY 100", "PSY 225", "PSY 325"],
        mustInclude: ["PSY 100", "PSY 225", "PSY 325"],
      },
      {
        category: "Capstone",
        description: "Senior Research",
        coursesRequired: 1,
        courses: ["PSY 424"],
        mustInclude: ["PSY 424"],
      },
      {
        category: "Laboratory Courses",
        description: "Two laboratory courses",
        coursesRequired: 2,
        courses: [
          "PSY 207",
          "PSY 208",
          "PSY 209",
          "PSY 210",
          "PSY 212",
          "PSY 214",
          "PSY 244",
        ],
      },
      {
        category: "Distribution",
        description: "Four additional PSY courses",
        coursesRequired: 4,
        courses: [
          "PSY 207",
          "PSY 208",
          "PSY 209",
          "PSY 210",
          "PSY 212",
          "PSY 214",
          "PSY 244",
          "PSY 390",
          "PSY 490",
          "PSY 395",
          "PSY 495",
          "PSY 397",
          "PSY 497",
          "PSY 398",
          "PSY 498",
        ],
      },
      {
        category: "Science Collateral",
        description:
          "One science course (waived if PSY 212 completed)",
        coursesRequired: 1,
        courses: [
          "BIO 100",
          "BIO 110",
          "CHM 131",
          "PHY 127",
          "PHY 221",
          "PSY 212",
        ],
      },
    ],
  },
  ANR: {
    code: "ANR",
    name: "Agriculture and Natural Resources",
    degree: "B.S.",
    totalMajorCredits: 15,
    requirements: [
      {
        category: "Required Core",
        description: "Core ANR courses",
        coursesRequired: 5,
        courses: ["ANR 100", "ANR 110", "ANR 130", "ANR 240", "ANR 375"],
        mustInclude: ["ANR 100", "ANR 110", "ANR 130", "ANR 240", "ANR 375"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["ANR 495", "ANR 494"],
      },
      {
        category: "ANR Electives",
        description: "4 electives, at least 3 at 300+ level",
        coursesRequired: 4,
        courses: ["ANR 201", "ANR 290", "ANR 310", "ANR 318", "ANR 320", "ANR 334", "ANR 342", "ANR 345", "ANR 360", "ANR 395", "ANR 495"],
        minUpperLevel: 3,
      },
      {
        category: "Supporting Course",
        description: "One supporting course",
        coursesRequired: 1,
        courses: ["BIO 222", "BIO 332", "BIO 342", "BIO 344", "BUS 363", "CHM 221", "ECO 250", "ECO 347", "SENS 310", "SENS 320"],
      },
      {
        category: "Collateral",
        description: "Collateral courses",
        coursesRequired: 4,
        courses: ["MAT 115", "BUS 120", "ECO 102", "CHM 131", "SENS 100", "SENS 310"],
      },
    ],
  },
  ART: {
    code: "ART",
    name: "Art: Studio",
    degree: "B.A.",
    totalMajorCredits: 14,
    requirements: [
      {
        category: "Required Core",
        description: "Foundation courses",
        coursesRequired: 4,
        courses: ["ART 134", "ART 135", "ART 136", "ART 137"],
        mustInclude: ["ART 134", "ART 135", "ART 136", "ART 137"],
      },
      {
        category: "Capstone",
        description: "Senior capstone",
        coursesRequired: 1,
        courses: ["ART 492A", "ART 492B", "ART 492C", "ART 492D"],
      },
      {
        category: "Medium Sequence",
        description: "One medium through 4th level",
        coursesRequired: 4,
        courses: ["ART 211", "ART 311", "ART 411", "ART 216", "ART 316", "ART 416", "ART 225", "ART 325", "ART 425", "ART 230", "ART 330", "ART 430"],
      },
      {
        category: "Studio Electives",
        description: "Additional studio courses",
        coursesRequired: 2,
        courses: ["ART 211", "ART 216", "ART 225", "ART 230", "ART 311", "ART 316", "ART 325", "ART 330"],
      },
      {
        category: "Collateral Art History",
        description: "Art history courses",
        coursesRequired: 3,
        courses: ["ARH 121", "ARH 124", "ARH 255"],
        mustInclude: ["ARH 121", "ARH 124", "ARH 255"],
      },
    ],
  },
  ARH: {
    code: "ARH",
    name: "Art: Art History",
    degree: "B.A.",
    totalMajorCredits: 11,
    requirements: [
      {
        category: "Required Core",
        description: "Core art history courses",
        coursesRequired: 5,
        courses: ["ARH 121", "ARH 124", "ARH 130", "ARH 255", "ARH 340"],
        mustInclude: ["ARH 121", "ARH 124", "ARH 130", "ARH 255", "ARH 340"],
      },
      {
        category: "Capstone",
        description: "Senior capstone",
        coursesRequired: 1,
        courses: ["ARH 450", "ARH 498"],
      },
      {
        category: "Distribution",
        description: "Additional art history courses",
        coursesRequired: 3,
        courses: ["ARH 210", "ARH 230", "ARH 232", "ARH 234", "ARH 239", "ARH 242", "ARH 243", "ARH 249", "ARH 262", "ARH 263", "ARH 265", "ARH 286", "ARH 386", "ARH 486", "ARH 395", "ARH 495"],
      },
      {
        category: "Collateral Studio",
        description: "Studio art course",
        coursesRequired: 1,
        courses: ["ART 134", "ART 135", "ART 136", "ART 137"],
      },
      {
        category: "Collateral Language",
        description: "Foreign language through 103 level",
        coursesRequired: 1,
        courses: ["FRN 103", "GER 103", "SPN 103", "CHI 103", "JPN 103", "LAT 102", "GRK 202"],
      },
    ],
  },
  AST_COMP: {
    code: "AST_COMP",
    name: "Asian Studies: Comparative Asia",
    degree: "B.A.",
    totalMajorCredits: 9,
    requirements: [
      {
        category: "Language Requirement",
        description: "Language courses",
        coursesRequired: 2,
        courses: ["CHI 101", "CHI 102", "CHI 103", "JPN 101", "JPN 102", "JPN 103"],
      },
      {
        category: "Intro and Capstone",
        description: "Introduction and capstone",
        coursesRequired: 2,
        courses: ["AST 100", "AST 401"],
        mustInclude: ["AST 100", "AST 401"],
      },
      {
        category: "Comparative Asia Distribution",
        description: "Comparative Asia courses, min 3 at 200+ level",
        coursesRequired: 6,
        courses: ["ARH 130", "AST 206", "AST 229", "AST 240", "AST 243", "AST 249", "AST 260", "AST 271", "AST 324A", "AST 325A"],
        minUpperLevel: 3,
      },
      {
        category: "Methods",
        description: "Methods course",
        coursesRequired: 1,
        courses: ["AST 229", "AST 240", "AST 243"],
      },
      {
        category: "Non-Comparative Asia",
        description: "Non-comparative Asia courses",
        coursesRequired: 2,
        courses: ["AST 122", "AST 123", "AST 132", "AST 135", "AST 324C", "AST 324J", "AST 325C", "AST 325J", "CHI 101", "CHI 102", "CHI 103", "CHI 210", "JPN 101", "JPN 102", "JPN 103", "JPN 210"],
      },
    ],
  },
  AST_CHI: {
    code: "AST_CHI",
    name: "Asian Studies: Chinese Studies",
    degree: "B.A.",
    totalMajorCredits: 10,
    requirements: [
      {
        category: "Language Requirement",
        description: "Chinese language",
        coursesRequired: 2,
        courses: ["CHI 103", "CHI 210"],
        mustInclude: ["CHI 103", "CHI 210"],
      },
      {
        category: "Intro and Capstone",
        description: "Introduction and capstone",
        coursesRequired: 2,
        courses: ["AST 100", "AST 401"],
        mustInclude: ["AST 100", "AST 401"],
      },
      {
        category: "China-Related Distribution",
        description: "China-related courses, min 3 at 200+ level",
        coursesRequired: 6,
        courses: ["AST 122", "AST 132", "AST 243", "AST 324C", "AST 325C"],
        minUpperLevel: 3,
      },
      {
        category: "Methods",
        description: "Methods course",
        coursesRequired: 1,
        courses: ["AST 229", "AST 240", "AST 243"],
      },
      {
        category: "Non-China Asia",
        description: "Non-China Asia courses",
        coursesRequired: 2,
        courses: ["AST 123", "AST 135", "AST 206", "AST 249", "AST 260", "AST 271", "AST 324A", "AST 324J", "AST 325A", "AST 325J", "JPN 101", "JPN 102", "JPN 103", "JPN 210"],
      },
    ],
  },
  AST_JPN: {
    code: "AST_JPN",
    name: "Asian Studies: Japanese Studies",
    degree: "B.A.",
    totalMajorCredits: 10,
    requirements: [
      {
        category: "Language Requirement",
        description: "Japanese language",
        coursesRequired: 2,
        courses: ["JPN 101", "JPN 102", "JPN 103", "JPN 210"],
      },
      {
        category: "Intro and Capstone",
        description: "Introduction and capstone",
        coursesRequired: 2,
        courses: ["AST 100", "AST 401"],
        mustInclude: ["AST 100", "AST 401"],
      },
      {
        category: "Japan-Related Distribution",
        description: "Japan-related courses, min 3 at 200+ level",
        coursesRequired: 6,
        courses: ["JPN 103", "JPN 210", "AST 123", "AST 135", "AST 324J", "AST 325J"],
        minUpperLevel: 3,
      },
      {
        category: "Methods",
        description: "Methods course",
        coursesRequired: 1,
        courses: ["AST 229", "AST 240", "AST 243"],
      },
      {
        category: "Non-Japan Asia",
        description: "Non-Japan Asia courses",
        coursesRequired: 2,
        courses: ["ARH 130", "AST 122", "AST 132", "AST 206", "AST 229", "AST 240", "AST 243", "AST 249", "AST 260", "AST 271", "AST 324A", "AST 324C", "AST 325A", "AST 325C", "CHI 101", "CHI 102", "CHI 103", "CHI 210"],
      },
    ],
  },
  CHM_GEN: {
    code: "CHM_GEN",
    name: "Chemistry (General Concentration)",
    degree: "B.A.",
    totalMajorCredits: 17,
    requirements: [
      {
        category: "Required Core",
        description: "Core chemistry courses",
        coursesRequired: 5,
        courses: ["CHM 131", "CHM 221", "CHM 222", "CHM 311", "CHM 340", "CHM 345"],
        mustInclude: ["CHM 131", "CHM 221", "CHM 222", "CHM 311"],
      },
      {
        category: "Advanced Labs",
        description: "Advanced laboratory courses",
        coursesRequired: 4,
        courses: ["CHM 370", "CHM 371", "CHM 470", "CHM 471"],
        mustInclude: ["CHM 370", "CHM 371", "CHM 470", "CHM 471"],
      },
      {
        category: "Distribution",
        description: "Additional chemistry courses",
        coursesRequired: 2,
        courses: ["CHM 361", "CHM 362", "CHM 451", "CHM 452"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["CHM 398", "CHM 498"],
      },
      {
        category: "Collateral Math",
        description: "Mathematics courses",
        coursesRequired: 4,
        courses: ["MAT 115", "MAT 125", "MAT 135", "MAT 225"],
        mustInclude: ["MAT 115", "MAT 125", "MAT 135", "MAT 225"],
      },
      {
        category: "Collateral Physics",
        description: "Physics courses",
        coursesRequired: 2,
        courses: ["PHY 127", "PHY 128", "PHY 221", "PHY 222"],
      },
    ],
  },
  CHM_BIO: {
    code: "CHM_BIO",
    name: "Chemistry (Biochemistry Concentration)",
    degree: "B.A.",
    totalMajorCredits: 16,
    requirements: [
      {
        category: "Required Core",
        description: "Core chemistry and biology courses",
        coursesRequired: 8,
        courses: ["CHM 131", "CHM 221", "CHM 222", "CHM 311", "CHM 361", "CHM 440", "BIO 441", "CHM 340", "CHM 345"],
        mustInclude: ["CHM 131", "CHM 221", "CHM 222", "CHM 311", "CHM 361", "CHM 440", "BIO 441"],
      },
      {
        category: "Advanced Labs",
        description: "Advanced laboratory courses",
        coursesRequired: 4,
        courses: ["CHM 370", "CHM 371", "CHM 470", "CHM 471"],
        mustInclude: ["CHM 370", "CHM 371", "CHM 470", "CHM 471"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["CHM 398", "CHM 498"],
      },
      {
        category: "Collateral",
        description: "Collateral courses",
        coursesRequired: 4,
        courses: ["BIO 110", "MAT 135", "PHY 127", "PHY 128", "PHY 221", "PHY 222"],
      },
    ],
  },
  CHM_PRO: {
    code: "CHM_PRO",
    name: "Chemistry (Professional Concentration)",
    degree: "B.A.",
    totalMajorCredits: 19,
    requirements: [
      {
        category: "Required Core",
        description: "Core chemistry courses",
        coursesRequired: 8,
        courses: ["CHM 131", "CHM 221", "CHM 222", "CHM 311", "CHM 361", "CHM 362", "CHM 451", "CHM 340", "CHM 345"],
        mustInclude: ["CHM 131", "CHM 221", "CHM 222", "CHM 311", "CHM 361", "CHM 362", "CHM 451"],
      },
      {
        category: "Advanced Labs",
        description: "Advanced laboratory courses",
        coursesRequired: 4,
        courses: ["CHM 370", "CHM 371", "CHM 470", "CHM 471"],
        mustInclude: ["CHM 370", "CHM 371", "CHM 470", "CHM 471"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["CHM 398", "CHM 498"],
      },
      {
        category: "Collateral Math",
        description: "Mathematics courses",
        coursesRequired: 4,
        courses: ["MAT 115", "MAT 125", "MAT 135", "MAT 225"],
        mustInclude: ["MAT 115", "MAT 125", "MAT 135", "MAT 225"],
      },
      {
        category: "Collateral Physics",
        description: "Physics courses",
        coursesRequired: 2,
        courses: ["PHY 127", "PHY 128", "PHY 221", "PHY 222"],
      },
    ],
  },
  CFS_CD: {
    code: "CFS_CD",
    name: "Child and Family Studies: Child Development",
    degree: "B.A.",
    totalMajorCredits: 12,
    requirements: [
      {
        category: "Required Core",
        description: "Core courses",
        coursesRequired: 4,
        courses: ["CFS 130", "CFS 145", "CFS 207", "CFS 221"],
        mustInclude: ["CFS 130", "CFS 145", "CFS 207", "CFS 221"],
      },
      {
        category: "Capstone",
        description: "Capstone courses",
        coursesRequired: 2,
        courses: ["CFS 441", "CFS 480"],
        mustInclude: ["CFS 441", "CFS 480"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, must include 1 from CFS 313/315/356",
        coursesRequired: 4,
        courses: ["CFS 210", "CFS 245", "CFS 313", "CFS 315", "CFS 317", "CFS 353", "CFS 356", "CFS 360"],
      },
    ],
  },
  CFS_FS: {
    code: "CFS_FS",
    name: "Child and Family Studies: Family Studies",
    degree: "B.A.",
    totalMajorCredits: 11,
    requirements: [
      {
        category: "Required Core",
        description: "Core courses",
        coursesRequired: 4,
        courses: ["CFS 130", "CFS 145", "CFS 207", "CFS 221"],
        mustInclude: ["CFS 130", "CFS 145", "CFS 207", "CFS 221"],
      },
      {
        category: "Capstone",
        description: "Capstone courses",
        coursesRequired: 2,
        courses: ["CFS 441", "CFS 480"],
        mustInclude: ["CFS 441", "CFS 480"],
      },
      {
        category: "Collateral",
        description: "Collateral course",
        coursesRequired: 1,
        courses: ["SOC 100", "PSY 100"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, must include 1 from CFS 317/362/366",
        coursesRequired: 4,
        courses: ["CFS 201", "CFS 231", "CFS 237", "CFS 238", "CFS 245", "CFS 317", "CFS 350", "CFS 362", "CFS 366"],
      },
    ],
  },
  CFS_NFS: {
    code: "CFS_NFS",
    name: "Child and Family Studies: Nutrition and Food Studies",
    degree: "B.A.",
    totalMajorCredits: 10,
    requirements: [
      {
        category: "Required Core",
        description: "Core courses",
        coursesRequired: 4,
        courses: ["CFS 130", "CFS 145", "CFS 207", "CFS 221"],
        mustInclude: ["CFS 130", "CFS 145", "CFS 207", "CFS 221"],
      },
      {
        category: "Capstone",
        description: "Capstone courses",
        coursesRequired: 2,
        courses: ["CFS 441", "CFS 480"],
        mustInclude: ["CFS 441", "CFS 480"],
      },
      {
        category: "Concentration Required",
        description: "Required concentration courses",
        coursesRequired: 3,
        courses: ["CFS 103", "CFS 115", "CFS 334"],
        mustInclude: ["CFS 103", "CFS 115", "CFS 334"],
      },
      {
        category: "Concentration Elective",
        description: "Elective concentration course",
        coursesRequired: 1,
        courses: ["CFS 209", "CFS 245", "CFS 300", "CFS 318", "CFS 395", "CFS 495"],
      },
    ],
  },
  COM: {
    code: "COM",
    name: "Communication",
    degree: "B.A.",
    totalMajorCredits: 9,
    requirements: [
      {
        category: "Required Core",
        description: "Core communication courses",
        coursesRequired: 3,
        courses: ["COM 100", "COM 220", "COM 410"],
        mustInclude: ["COM 100", "COM 220", "COM 410"],
      },
      {
        category: "Group 1 - Cultural Identity",
        description: "Cultural identity course",
        coursesRequired: 1,
        courses: ["COM 112", "COM 113", "COM 204", "COM 206", "COM 207", "COM 305", "COM 310"],
      },
      {
        category: "Group 2 - Strategic Communication",
        description: "Strategic communication course",
        coursesRequired: 1,
        courses: ["COM 201", "COM 211", "COM 302", "COM 303", "COM 311", "COM 312", "COM 314", "COM 315"],
      },
      {
        category: "Additional Distribution",
        description: "Additional courses from either group, at least 1 at 300-level",
        coursesRequired: 2,
        courses: ["COM 112", "COM 113", "COM 204", "COM 206", "COM 207", "COM 305", "COM 310", "COM 201", "COM 211", "COM 302", "COM 303", "COM 311", "COM 312", "COM 314", "COM 315"],
        minUpperLevel: 1,
      },
    ],
  },
  ECO: {
    code: "ECO",
    name: "Economics",
    degree: "B.A.",
    totalMajorCredits: 13,
    requirements: [
      {
        category: "Required Core",
        description: "Core economics courses",
        coursesRequired: 4,
        courses: ["ECO 101", "ECO 102", "ECO 250", "PSC 235", "MAT 438", "ECO 350"],
        mustInclude: ["ECO 101", "ECO 102", "ECO 350"],
      },
      {
        category: "Theory Courses",
        description: "Theory courses",
        coursesRequired: 3,
        courses: ["ECO 301", "ECO 302", "HIS 224", "HIS 229", "PSC 220", "PSC 250"],
        mustInclude: ["ECO 301", "ECO 302"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 3 at ECO 200+ level",
        coursesRequired: 4,
        courses: ["ECO 248", "ECO 305", "ECO 332", "ECO 341", "ECO 347", "ECO 357", "ECO 360", "ECO 370", "PSC 210", "PSC 355"],
        minUpperLevel: 3,
      },
      {
        category: "Collateral",
        description: "Collateral mathematics",
        coursesRequired: 2,
        courses: ["MAT 115", "MAT 135"],
        mustInclude: ["MAT 115", "MAT 135"],
      },
    ],
  },
  ECO_QUANT: {
    code: "ECO_QUANT",
    name: "Quantitative Economics",
    degree: "B.S.",
    totalMajorCredits: 14,
    requirements: [
      {
        category: "Required Core",
        description: "Core economics courses",
        coursesRequired: 7,
        courses: ["ECO 101", "ECO 102", "ECO 301", "ECO 302", "ECO 350", "ECO 250", "MAT 438", "ECO 401", "ECO 402"],
        mustInclude: ["ECO 101", "ECO 102", "ECO 301", "ECO 302", "ECO 350"],
      },
      {
        category: "Distribution",
        description: "Distribution courses at ECO 200+ level",
        coursesRequired: 5,
        courses: ["ECO 248", "ECO 305", "ECO 332", "ECO 341", "ECO 347", "ECO 357", "ECO 360", "ECO 370"],
        minUpperLevel: 5,
      },
      {
        category: "Collateral",
        description: "Collateral mathematics",
        coursesRequired: 1,
        courses: ["MAT 135"],
        mustInclude: ["MAT 135"],
      },
    ],
  },
  BUS: {
    code: "BUS",
    name: "Business Administration",
    degree: "B.S.",
    totalMajorCredits: 16,
    requirements: [
      {
        category: "Required Core",
        description: "Core business courses",
        coursesRequired: 8,
        courses: ["BUS 114", "BUS 120", "BUS 130", "BUS 240", "BUS 315", "BUS 363", "BUS 366", "BUS 475"],
        mustInclude: ["BUS 114", "BUS 120", "BUS 130", "BUS 240", "BUS 315", "BUS 363", "BUS 366", "BUS 475"],
      },
      {
        category: "Collateral",
        description: "Collateral courses",
        coursesRequired: 4,
        courses: ["ECO 101", "ECO 102", "ECO 250", "MAT 115", "MAT 125", "MAT 135"],
      },
      {
        category: "Concentration - Accounting",
        description: "Accounting concentration",
        coursesRequired: 4,
        courses: ["BUS 323", "BUS 324", "BUS 326", "BUS 327"],
      },
      {
        category: "Concentration - Finance",
        description: "Finance concentration",
        coursesRequired: 4,
        courses: ["ECO 332", "BUS 346", "BUS 368", "ECO 357"],
      },
      {
        category: "Concentration - Management",
        description: "Management concentration",
        coursesRequired: 4,
        courses: ["BUS 345", "BUS 364", "BUS 221", "BUS 324", "BUS 371", "COM 302", "PSY 210", "SOC 348"],
      },
      {
        category: "Concentration - Marketing",
        description: "Marketing concentration",
        coursesRequired: 4,
        courses: ["BUS 257", "BUS 367", "BUS 221", "BUS 328", "BUS 371", "COM 312", "COM 315"],
      },
    ],
  },
  EDS: {
    code: "EDS",
    name: "Education Studies",
    degree: "B.A.",
    totalMajorCredits: 9,
    requirements: [
      {
        category: "Required Core",
        description: "Core education courses",
        coursesRequired: 5,
        courses: ["EDS 150", "EDS 227", "EDS 228", "EDS 349", "EDS 490", "EDS 495"],
        mustInclude: ["EDS 150", "EDS 227", "EDS 228", "EDS 349"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 4,
        courses: ["EDS 225", "EDS 230", "EDS 235", "EDS 285", "EDS 295", "EDS 300", "EDS 330", "EDS 340", "EDS 345", "CFS 207", "CFS 315", "CFS 350", "CFS 366", "PSY 208", "SOC 215", "THR 218"],
      },
    ],
  },
  ETAD: {
    code: "ETAD",
    name: "Engineering Technologies and Applied Design (General)",
    degree: "B.S.",
    totalMajorCredits: 11,
    requirements: [
      {
        category: "Required Core",
        description: "Core ETAD courses",
        coursesRequired: 6,
        courses: ["ETAD 130", "ETAD 140", "ETAD 180", "ETAD 245", "ETAD 265", "ETAD 275"],
        mustInclude: ["ETAD 130", "ETAD 140", "ETAD 180", "ETAD 245", "ETAD 265", "ETAD 275"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["ETAD 488"],
        mustInclude: ["ETAD 488"],
      },
      {
        category: "Advanced Distribution",
        description: "Advanced courses at 300/400 level",
        coursesRequired: 3,
        courses: ["ETAD 330", "ETAD 340", "ETAD 345", "ETAD 352", "ETAD 382", "ETAD 455", "ETAD 460"],
        minUpperLevel: 3,
      },
      {
        category: "Collateral Math",
        description: "Mathematics course",
        coursesRequired: 1,
        courses: ["MAT 105", "MAT 115", "MAT 125", "MAT 135"],
      },
    ],
  },
  ETAD_MGMT: {
    code: "ETAD_MGMT",
    name: "Engineering Technologies and Applied Design (Technology Management)",
    degree: "B.S.",
    totalMajorCredits: 14,
    requirements: [
      {
        category: "Required Core",
        description: "Core ETAD courses",
        coursesRequired: 7,
        courses: ["ETAD 130", "ETAD 140", "ETAD 180", "ETAD 245", "ETAD 265", "ETAD 275", "ETAD 488"],
        mustInclude: ["ETAD 130", "ETAD 140", "ETAD 180", "ETAD 245", "ETAD 265", "ETAD 275", "ETAD 488"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 3,
        courses: ["ETAD 330", "ETAD 352", "ETAD 455"],
      },
      {
        category: "Collateral Math",
        description: "Mathematics course",
        coursesRequired: 1,
        courses: ["MAT 115"],
        mustInclude: ["MAT 115"],
      },
      {
        category: "Collateral Business",
        description: "Business courses",
        coursesRequired: 3,
        courses: ["BUS 120", "BUS 240", "BUS 315", "BUS 363", "BUS 364", "ECO 101", "ECO 102", "ECO 250"],
      },
    ],
  },
  ENG: {
    code: "ENG",
    name: "English",
    degree: "B.A.",
    totalMajorCredits: 9,
    requirements: [
      {
        category: "Required Core",
        description: "Core English courses",
        coursesRequired: 4,
        courses: ["ENG 200", "ENG 270", "ENG 470"],
        mustInclude: ["ENG 270", "ENG 470"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["ENG 485"],
        mustInclude: ["ENG 485"],
      },
      {
        category: "Literature Distribution",
        description: "Literature courses, at least 2 at 300-level, from at least 2 categories",
        coursesRequired: 3,
        courses: ["ENG 205", "ENG 305", "ENG 210", "ENG 310", "ENG 225", "ENG 325", "ENG 240", "ENG 340", "ENG 250", "ENG 350", "ENG 260", "ENG 360"],
        minUpperLevel: 2,
      },
      {
        category: "Language or Foreign Language",
        description: "Language course",
        coursesRequired: 1,
        courses: ["ENG 280", "ENG 380", "FRN 103", "GER 103", "SPN 103"],
      },
      {
        category: "Additional ENG",
        description: "Additional English course",
        coursesRequired: 1,
        courses: ["ENG 205", "ENG 210", "ENG 225", "ENG 240", "ENG 250", "ENG 270", "ENG 280", "ENG 282", "ENG 305", "ENG 310", "ENG 325", "ENG 340", "ENG 380"],
      },
    ],
  },
  FRN: {
    code: "FRN",
    name: "French",
    degree: "B.A.",
    totalMajorCredits: 9,
    requirements: [
      {
        category: "Language Foundation",
        description: "French language foundation",
        coursesRequired: 1,
        courses: ["FRN 101", "FRN 102", "FRN 103"],
      },
      {
        category: "Upper-Level French",
        description: "Upper-level French courses",
        coursesRequired: 7,
        courses: ["FRN 200", "FRN 210", "FRN 220", "FRN 300", "FRN 310", "FRN 320", "FRN 330", "FRN 395", "FRN 495"],
        minUpperLevel: 7,
      },
      {
        category: "Collateral",
        description: "Collateral language courses",
        coursesRequired: 2,
        courses: ["ENG 387", "GER 103", "SPN 103", "CHI 103", "JPN 103"],
      },
    ],
  },
  SPN: {
    code: "SPN",
    name: "Spanish",
    degree: "B.A.",
    totalMajorCredits: 9,
    requirements: [
      {
        category: "Required History Course",
        description: "Spanish history course",
        coursesRequired: 1,
        courses: ["SPN 140"],
        mustInclude: ["SPN 140"],
      },
      {
        category: "Upper-Level Spanish",
        description: "Upper-level Spanish courses",
        coursesRequired: 7,
        courses: ["SPN 200", "SPN 210", "SPN 220", "SPN 310", "SPN 312", "SPN 315", "SPN 320", "SPN 330", "SPN 395", "SPN 495"],
        minUpperLevel: 7,
      },
      {
        category: "Collateral Language",
        description: "Collateral language courses",
        coursesRequired: 1,
        courses: ["FRN 103", "GER 103", "CHI 103", "JPN 103"],
      },
    ],
  },
  GER: {
    code: "GER",
    name: "German",
    degree: "B.A.",
    totalMajorCredits: 9,
    requirements: [
      {
        category: "Language Foundation",
        description: "German language foundation",
        coursesRequired: 1,
        courses: ["GER 101", "GER 102", "GER 103"],
      },
      {
        category: "Upper-Level German",
        description: "Upper-level German courses",
        coursesRequired: 7,
        courses: ["GER 200", "GER 210", "GER 220", "GER 300", "GER 310", "GER 320", "GER 395", "GER 495"],
        minUpperLevel: 7,
      },
      {
        category: "Collateral",
        description: "Collateral language courses",
        coursesRequired: 2,
        courses: ["ENG 387", "FRN 103", "SPN 103", "CHI 103", "JPN 103"],
      },
    ],
  },
  HHP: {
    code: "HHP",
    name: "Health and Human Performance",
    degree: "B.A.",
    totalMajorCredits: 12,
    requirements: [
      {
        category: "Required Core",
        description: "Core HHP courses",
        coursesRequired: 6,
        courses: ["HHP 125", "HHP 264", "HHP 315", "HHP 345", "HHP 350", "HHP 492"],
        mustInclude: ["HHP 125", "HHP 264", "HHP 315", "HHP 345", "HHP 350", "HHP 492"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 4,
        courses: ["HHP 245", "HHP 246", "HHP 247", "HHP 250", "HHP 254", "HHP 260", "HHP 261", "HHP 262", "HHP 263", "HHP 265", "HHP 280", "HHP 360"],
      },
      {
        category: "Collateral",
        description: "Collateral courses",
        coursesRequired: 2,
        courses: ["BIO 201", "HLT 200"],
        mustInclude: ["BIO 201", "HLT 200"],
      },
    ],
  },
  HLT: {
    code: "HLT",
    name: "Health Studies",
    degree: "B.A.",
    totalMajorCredits: 15,
    requirements: [
      {
        category: "Required Core",
        description: "Core health courses",
        coursesRequired: 4,
        courses: ["HLT 200", "HLT 227", "HLT 300", "HLT 400"],
        mustInclude: ["HLT 200", "HLT 227", "HLT 300", "HLT 400"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 3,
        courses: ["HLT 111", "HLT 203", "HLT 205", "HLT 210", "HLT 224", "HLT 236", "SOC 200", "HLT 395", "HLT 495"],
      },
      {
        category: "Collateral",
        description: "Collateral courses",
        coursesRequired: 7,
        courses: ["BIO 201", "CFS 221", "HHP 262", "HHP 264", "MAT 104", "PSY 100", "SENS 100"],
        mustInclude: ["BIO 201", "CFS 221", "HHP 262", "HHP 264", "PSY 100", "SENS 100"],
      },
    ],
  },
  HIS: {
    code: "HIS",
    name: "History",
    degree: "B.A.",
    totalMajorCredits: 10,
    requirements: [
      {
        category: "Required Core",
        description: "Core history courses",
        coursesRequired: 2,
        courses: ["HIS 200", "HIS 406"],
        mustInclude: ["HIS 200", "HIS 406"],
      },
      {
        category: "American Area",
        description: "American history courses, at least 1 African-American",
        coursesRequired: 2,
        courses: ["HIS 132", "HIS 161", "HIS 162", "HIS 201", "HIS 250", "HIS 310", "HIS 355", "HIS 165", "HIS 242", "HIS 245", "HIS 309", "HIS 356"],
      },
      {
        category: "Regional History",
        description: "Regional history from 2+ areas",
        coursesRequired: 3,
        courses: ["HIS 103", "HIS 122", "HIS 123", "HIS 324A", "HIS 324C", "HIS 324J", "HIS 112", "HIS 124", "HIS 128", "HIS 129", "HIS 130", "HIS 131", "HIS 140", "HIS 244", "HIS 246", "HIS 303", "HIS 311", "HIS 335", "HIS 133", "HIS 134", "HIS 175"],
        selectFromCategories: [
          {
            category: "African",
            min: 1,
            courses: ["HIS 103"],
          },
          {
            category: "Asian",
            min: 1,
            courses: ["HIS 122", "HIS 123", "HIS 324A", "HIS 324C", "HIS 324J"],
          },
          {
            category: "European",
            min: 1,
            courses: ["HIS 112", "HIS 124", "HIS 128", "HIS 129", "HIS 130", "HIS 131", "HIS 140", "HIS 244", "HIS 246", "HIS 303", "HIS 311", "HIS 335"],
          },
          {
            category: "Middle Eastern",
            min: 1,
            courses: ["HIS 133", "HIS 134", "HIS 175"],
          },
        ],
      },
      {
        category: "Global History",
        description: "Global history course",
        coursesRequired: 1,
        courses: ["HIS 126", "HIS 127", "HIS 229", "HIS 243", "HIS 309", "HIS 320"],
      },
      {
        category: "Pre-1700 Content",
        description: "Pre-1700 history courses",
        coursesRequired: 2,
        courses: ["HIS 112", "HIS 124", "HIS 126", "HIS 128", "HIS 129", "HIS 130", "HIS 243", "HIS 303", "HIS 311"],
      },
      {
        category: "Collateral Language",
        description: "Foreign language course",
        coursesRequired: 1,
        courses: ["FRN 103", "GER 103", "SPN 103", "CHI 103", "JPN 103", "LAT 102", "GRK 202"],
      },
    ],
  },
  MAT: {
    code: "MAT",
    name: "Mathematics",
    degree: "B.A.",
    totalMajorCredits: 10,
    requirements: [
      {
        category: "Required Core",
        description: "Core mathematics courses",
        coursesRequired: 5,
        courses: ["MAT 135", "MAT 214", "MAT 225", "MAT 315", "MAT 330"],
        mustInclude: ["MAT 135", "MAT 214", "MAT 225", "MAT 315", "MAT 330"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["MAT 426", "MAT 492"],
      },
      {
        category: "Distribution",
        description: "Distribution courses covering Theoretical/Applied/Analysis/Nonanalysis categories",
        coursesRequired: 3,
        courses: ["MAT 321", "MAT 432", "MAT 434", "MAT 436", "MAT 311", "MAT 312", "MAT 433", "MAT 438", "MAT 337", "MAT 433", "MAT 434", "MAT 435", "MAT 438", "MAT 311", "MAT 312", "MAT 321", "MAT 415", "MAT 432", "MAT 436"],
        selectFromCategories: [
          {
            category: "Theoretical",
            min: 1,
            courses: ["MAT 321", "MAT 432", "MAT 434", "MAT 436"],
          },
          {
            category: "Applied",
            min: 1,
            courses: ["MAT 311", "MAT 312", "MAT 433", "MAT 438"],
          },
          {
            category: "Analysis",
            min: 1,
            courses: ["MAT 337", "MAT 433", "MAT 434", "MAT 435", "MAT 438"],
          },
          {
            category: "Nonanalysis",
            min: 1,
            courses: ["MAT 311", "MAT 312", "MAT 321", "MAT 415", "MAT 432", "MAT 436"],
          },
        ],
      },
      {
        category: "Collateral CSC",
        description: "Computer science course",
        coursesRequired: 1,
        courses: ["CSC 111", "CSC 114", "CSC 124", "CSC 126", "CSC 226", "CSC 236"],
      },
    ],
  },
  MUS: {
    code: "MUS",
    name: "Music",
    degree: "B.A.",
    totalMajorCredits: 11,
    requirements: [
      {
        category: "Theory",
        description: "Theory courses (8 half-credit courses = 4 credits)",
        coursesRequired: 8,
        courses: ["MUS 220", "MUS 221", "MUS 222", "MUS 223", "MUS 320", "MUS 321", "MUS 322", "MUS 323"],
        mustInclude: ["MUS 220", "MUS 221", "MUS 222", "MUS 223", "MUS 320", "MUS 321", "MUS 322", "MUS 323"],
      },
      {
        category: "Music History",
        description: "Music history courses",
        coursesRequired: 3,
        courses: ["MUS 115", "MUS 330", "MUS 331"],
        mustInclude: ["MUS 115", "MUS 330", "MUS 331"],
      },
      {
        category: "Applied Music",
        description: "Applied music courses (2+ credits minimum)",
        coursesRequired: 2,
        courses: ["MUA 105", "MUA 115", "MUA 125", "MUA 135", "MUA 205", "MUA 215", "MUA 225", "MUA 235", "MUA 305", "MUA 315", "MUA 325", "MUA 335", "MUA 405", "MUA 415", "MUA 425", "MUA 435"],
      },
      {
        category: "Ensemble",
        description: "Ensemble courses (1.5 credits, 6 terms)",
        coursesRequired: 6,
        courses: ["MUS 130A", "MUS 130B", "MUS 130C", "MUS 130D", "MUS 130E", "MUS 130F", "MUS 130G", "MUS 130H", "MUS 130K", "MUS 130M", "MUS 131"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["MUS 400"],
        mustInclude: ["MUS 400"],
      },
    ],
  },
  NUR: {
    code: "NUR",
    name: "Nursing",
    degree: "B.S.",
    totalMajorCredits: 18,
    requirements: [
      {
        category: "Core Nursing",
        description: "Core nursing courses",
        coursesRequired: 13,
        courses: ["NUR 110", "NUR 201", "NUR 225", "NUR 226", "NUR 230", "NUR 301", "NUR 350", "NUR 351", "NUR 352", "NUR 355", "NUR 400", "NUR 448", "NUR 449"],
        mustInclude: ["NUR 110", "NUR 201", "NUR 225", "NUR 226", "NUR 230", "NUR 301", "NUR 350", "NUR 351", "NUR 352", "NUR 355", "NUR 400", "NUR 448", "NUR 449"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["NUR 450"],
        mustInclude: ["NUR 450"],
      },
      {
        category: "Collateral Biology",
        description: "Biology courses",
        coursesRequired: 4,
        courses: ["BIO 201", "BIO 202", "BIO 207", "BIO 222"],
        mustInclude: ["BIO 201", "BIO 202", "BIO 207", "BIO 222"],
      },
      {
        category: "Collateral Other",
        description: "Other collateral courses",
        coursesRequired: 3,
        courses: ["CFS 221", "CHM 113", "PSY 100"],
        mustInclude: ["CFS 221", "PSY 100"],
      },
    ],
  },
  PSJ: {
    code: "PSJ",
    name: "Peace and Social Justice Studies",
    degree: "B.A.",
    totalMajorCredits: 9,
    requirements: [
      {
        category: "Required Core",
        description: "Core PSJ courses",
        coursesRequired: 4,
        courses: ["PSJ 100", "PSJ 201", "PSJ 205", "PSJ 218", "PSJ 305"],
        mustInclude: ["PSJ 100", "PSJ 218", "PSJ 305"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["PSJ 450"],
        mustInclude: ["PSJ 450"],
      },
      {
        category: "Research Methods",
        description: "Research methods course",
        coursesRequired: 1,
        courses: ["PSJ 300", "SOC 335"],
      },
      {
        category: "Building Peace",
        description: "Building peace course",
        coursesRequired: 1,
        courses: ["APS 215", "COM 206", "COM 207", "ECO 370", "HIS 175", "LES 215", "PSC 250", "PSC 351", "PSC 355", "PSJ 112", "PSJ 113", "PSJ 212", "PSJ 301", "PSJ 302", "SOC 110", "SOC 341"],
      },
      {
        category: "Social Justice",
        description: "Social justice course",
        coursesRequired: 1,
        courses: ["AFR 201", "AFR 250", "ANR 318", "APS 229", "APS 330", "AST 229", "CFS 350", "CFS 362", "ECO 248", "PHI 104", "PHI 244", "PSJ 103", "PSJ 200", "PSJ 210", "PSJ 225", "PSJ 303", "REL 235", "SOC 223", "WGS 124", "WGS 206"],
      },
    ],
  },
  PHI: {
    code: "PHI",
    name: "Philosophy",
    degree: "B.A.",
    totalMajorCredits: 10,
    requirements: [
      {
        category: "Required Core",
        description: "Core philosophy courses",
        coursesRequired: 5,
        courses: ["PHI 305", "PHI 310", "PHI 315", "PHI 214", "PHI 106", "PHI 218", "PHI 380"],
        mustInclude: ["PHI 305", "PHI 214", "PHI 380"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["PHI 480"],
        mustInclude: ["PHI 480"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 2 above 100-level",
        coursesRequired: 3,
        courses: ["PHI 104", "PHI 106", "PHI 215", "PHI 218", "PHI 230", "PHI 241", "PHI 244", "PHI 261", "PHI 305", "PHI 310", "PHI 315", "PHI 380"],
        minUpperLevel: 2,
      },
    ],
  },
  PHY: {
    code: "PHY",
    name: "Physics",
    degree: "B.A.",
    totalMajorCredits: 10,
    requirements: [
      {
        category: "Required Core",
        description: "Core physics courses",
        coursesRequired: 4,
        courses: ["PHY 221", "PHY 222", "PHY 320", "PHY 365"],
        mustInclude: ["PHY 221", "PHY 222", "PHY 320", "PHY 365"],
      },
      {
        category: "Theory Courses",
        description: "Theory courses",
        coursesRequired: 3,
        courses: ["PHY 460", "PHY 481", "PHY 482"],
        mustInclude: ["PHY 460", "PHY 481", "PHY 482"],
      },
      {
        category: "Advanced Lab",
        description: "Advanced laboratory course",
        coursesRequired: 1,
        courses: ["PHY 341"],
        mustInclude: ["PHY 341"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["PHY 492", "PHY 495"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 1 at 300-level",
        coursesRequired: 2,
        courses: ["PHY 111", "PHY 130", "PHY 321", "PHY 335", "PHY 340", "PHY 365", "PHY 460", "PHY 481", "PHY 482", "PHY 485"],
        minUpperLevel: 1,
      },
      {
        category: "Collateral Math",
        description: "Mathematics courses",
        coursesRequired: 4,
        courses: ["MAT 135", "MAT 225", "MAT 330", "MAT 337"],
        mustInclude: ["MAT 135", "MAT 225", "MAT 330", "MAT 337"],
      },
    ],
  },
  PHY_ENG: {
    code: "PHY_ENG",
    name: "Engineering Physics",
    degree: "B.S.",
    totalMajorCredits: 16,
    requirements: [
      {
        category: "Required Core",
        description: "Core physics courses",
        coursesRequired: 8,
        courses: ["PHY 130", "PHY 221", "PHY 222", "PHY 320", "PHY 341", "PHY 365", "PHY 460", "PHY 481"],
        mustInclude: ["PHY 130", "PHY 221", "PHY 222", "PHY 320", "PHY 341", "PHY 365", "PHY 460", "PHY 481"],
      },
      {
        category: "Design Distribution",
        description: "Design courses (choose one pair)",
        coursesRequired: 2,
        courses: ["ETAD 130", "ETAD 330", "ETAD 265", "ETAD 460"],
      },
      {
        category: "Additional Distribution",
        description: "Additional distribution course",
        coursesRequired: 1,
        courses: ["PHY 321", "PHY 335", "PHY 340", "PHY 482", "PHY 485", "CHM 311", "MAT 433", "SENS 310"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["PHY 492", "PHY 495"],
      },
      {
        category: "Collateral",
        description: "Collateral courses",
        coursesRequired: 5,
        courses: ["MAT 135", "MAT 225", "MAT 330", "MAT 337", "CHM 131"],
        mustInclude: ["MAT 135", "MAT 225", "MAT 330", "MAT 337", "CHM 131"],
      },
    ],
  },
  PSC: {
    code: "PSC",
    name: "Political Science",
    degree: "B.A.",
    totalMajorCredits: 10,
    requirements: [
      {
        category: "Required Core",
        description: "Core political science courses",
        coursesRequired: 5,
        courses: ["PSC 100", "PSC 110", "PSC 220", "PSC 235", "PSC 250"],
        mustInclude: ["PSC 100", "PSC 110", "PSC 220", "PSC 235", "PSC 250"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["PSC 480"],
        mustInclude: ["PSC 480"],
      },
      {
        category: "American Government",
        description: "American government course",
        coursesRequired: 1,
        courses: ["PSC 314", "PSC 317", "PSC 319", "PSC 322", "PSC 330", "PSC 212"],
      },
      {
        category: "International/Comparative",
        description: "International or comparative course",
        coursesRequired: 1,
        courses: ["PSC 351", "PSC 355", "PSC 360"],
      },
      {
        category: "Additional Distribution",
        description: "Additional courses at 200-400 level",
        coursesRequired: 2,
        courses: ["PSC 210", "PSC 212", "PSC 314", "PSC 317", "PSC 319", "PSC 322", "PSC 330", "PSC 351", "PSC 355", "PSC 360"],
        minUpperLevel: 2,
      },
    ],
  },
  REL: {
    code: "REL",
    name: "Religion",
    degree: "B.A.",
    totalMajorCredits: 8,
    requirements: [
      {
        category: "Required Core",
        description: "Core religion courses",
        coursesRequired: 3,
        courses: ["REL 100", "REL 302", "REL 480"],
        mustInclude: ["REL 100", "REL 302", "REL 480"],
      },
      {
        category: "Historical Studies Track",
        description: "Historical studies track course",
        coursesRequired: 1,
        courses: ["REL 105", "REL 107", "REL 136", "REL 224", "REL 238", "REL 240", "REL 250", "REL 260", "ARH 232", "ARH 242", "HIS 355"],
      },
      {
        category: "Cultural Studies Track",
        description: "Cultural studies track course",
        coursesRequired: 1,
        courses: ["REL 204", "REL 211", "REL 222", "REL 228", "REL 242", "AFR 234", "ARH 210", "ARH 230", "ARH 249", "AST 132", "AST 135", "AST 206", "CHI 103", "GRK 202", "HEB 103", "JPN 103", "LAT 102"],
      },
      {
        category: "Normative Studies Track",
        description: "Normative studies track course",
        coursesRequired: 1,
        courses: ["REL 109", "REL 201", "REL 212", "REL 225", "REL 235", "REL 271", "REL 281", "AFR 225", "AST 240", "PHI 104", "PHI 214", "PHI 215", "PSJ 100", "PSJ 113", "PSJ 210", "PSJ 218"],
      },
      {
        category: "Additional Track Electives",
        description: "Additional track electives",
        coursesRequired: 2,
        courses: ["REL 105", "REL 107", "REL 109", "REL 136", "REL 201", "REL 204", "REL 211", "REL 212", "REL 222", "REL 224", "REL 225", "REL 228", "REL 235", "REL 238", "REL 240", "REL 242", "REL 250", "REL 255", "REL 260", "REL 271", "REL 281"],
      },
    ],
  },
  SOC: {
    code: "SOC",
    name: "Sociology",
    degree: "B.A.",
    totalMajorCredits: 10,
    requirements: [
      {
        category: "Required Core",
        description: "Core sociology courses",
        coursesRequired: 5,
        courses: ["SOC 100", "SOC 220", "SOC 335", "SOC 350", "SOC 436"],
        mustInclude: ["SOC 100", "SOC 220", "SOC 335", "SOC 350", "SOC 436"],
      },
      {
        category: "Distribution",
        description: "Additional sociology courses",
        coursesRequired: 5,
        courses: ["SOC 110", "SOC 200", "SOC 202", "SOC 210", "SOC 212", "SOC 215", "SOC 220", "SOC 223", "SOC 300", "SOC 325", "SOC 330", "SOC 341", "SOC 345", "SOC 348", "SOC 461"],
      },
    ],
  },
  SENS: {
    code: "SENS",
    name: "Environmental Science",
    degree: "B.A.",
    totalMajorCredits: 11,
    requirements: [
      {
        category: "Introductory Core",
        description: "Introductory core courses",
        coursesRequired: 4,
        courses: ["SENS 100", "BIO 110", "CHM 131", "ANR 130", "BIO 114", "GEO 101"],
      },
      {
        category: "Advanced Core",
        description: "Advanced core courses",
        coursesRequired: 5,
        courses: ["ANR 240", "SENS 310", "BIO 346", "GEO 320", "CHM 221", "CHM 311"],
        mustInclude: ["ANR 240", "SENS 310", "BIO 346", "GEO 320"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 1 SENS or GEO",
        coursesRequired: 2,
        courses: ["ANR 342", "SENS 310", "ANR 328", "BIO 327", "BIO 332", "BIO 338", "BIO 344", "BIO 346", "GEO 200"],
      },
      {
        category: "Collateral Methods",
        description: "Methods collateral course",
        coursesRequired: 1,
        courses: ["ECO 250", "HLT 400", "MAT 135"],
      },
      {
        category: "Collateral Policy",
        description: "Policy collateral course",
        coursesRequired: 1,
        courses: ["ECO 370", "SENS 225", "AFR 225"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["SENS 460", "SENS 395", "SENS 495"],
      },
    ],
  },
  THR: {
    code: "THR",
    name: "Theatre",
    degree: "B.A.",
    totalMajorCredits: 11,
    requirements: [
      {
        category: "Required Core",
        description: "Core theatre courses",
        coursesRequired: 5,
        courses: ["THR 105", "THR 115", "THR 124", "THR 213", "THR 400"],
        mustInclude: ["THR 105", "THR 115", "THR 124", "THR 213", "THR 400"],
      },
      {
        category: "Practicum",
        description: "Practicum courses (5 at 0.25 credit each)",
        coursesRequired: 5,
        courses: ["THR 300", "THR 301", "THR 302", "THR 303", "THR 304"],
        mustInclude: ["THR 300", "THR 301", "THR 302", "THR 303", "THR 304"],
      },
      {
        category: "Seminars",
        description: "Seminar courses",
        coursesRequired: 3,
        courses: ["THR 220", "THR 308", "THR 321"],
        mustInclude: ["THR 220", "THR 308", "THR 321"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["THR 135", "THR 202", "THR 218", "THR 227", "THR 232", "THR 233", "THR 317", "THR 331", "THR 332"],
      },
    ],
  },
  WGS: {
    code: "WGS",
    name: "Women's, Gender, and Sexuality Studies",
    degree: "B.A.",
    totalMajorCredits: 10,
    requirements: [
      {
        category: "Required Core",
        description: "Core WGS courses",
        coursesRequired: 4,
        courses: ["WGS 124", "WGS 200", "WGS 206", "WGS 208"],
        mustInclude: ["WGS 124", "WGS 200", "WGS 206", "WGS 208"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["WGS 450"],
        mustInclude: ["WGS 450"],
      },
      {
        category: "Research Methods Collateral",
        description: "Research methods collateral course",
        coursesRequired: 1,
        courses: ["ENG 270", "HIS 200", "PSC 235", "PSJ 300", "SOC 335"],
      },
      {
        category: "Women's Studies",
        description: "Women's studies course",
        coursesRequired: 1,
        courses: ["WGS 103", "WGS 135", "WGS 202", "WGS 230", "WGS 232", "WGS 236", "WGS 243", "WGS 310", "WGS 325"],
      },
      {
        category: "Sexuality Studies",
        description: "Sexuality studies course",
        coursesRequired: 1,
        courses: ["WGS 103", "WGS 111", "WGS 201", "WGS 232", "WGS 233"],
      },
      {
        category: "Race Studies",
        description: "Race studies course",
        coursesRequired: 1,
        courses: ["WGS 103", "WGS 135", "WGS 202", "WGS 204", "WGS 207", "WGS 232", "WGS 240", "WGS 366", "AFR 204", "AFR 242", "AFR 250", "ARH 230", "AST 229", "PSJ 200"],
      },
      {
        category: "Activism Studies",
        description: "Activism studies course",
        coursesRequired: 1,
        courses: ["APS 229", "ECO 370", "PSJ 100", "PSJ 205", "PSJ 210", "PSJ 218", "PSJ 301", "PSJ 305", "SENS 100", "SOC 341", "WGS 103", "WGS 202", "WGS 225", "WGS 233"],
      },
    ],
  },
};

export const MINORS: Record<string, Minor> = {
  ANR_MINOR: {
    code: "ANR_MINOR",
    name: "Agriculture and Natural Resources",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required",
        description: "Required ANR course",
        coursesRequired: 1,
        courses: ["ANR 100"],
        mustInclude: ["ANR 100"],
      },
      {
        category: "ANR Electives",
        description: "ANR elective courses",
        coursesRequired: 5,
        courses: ["ANR 110", "ANR 130", "ANR 201", "ANR 240", "ANR 290", "ANR 310", "ANR 318", "ANR 320", "ANR 334", "ANR 342", "ANR 345", "ANR 360", "ANR 375", "ANR 395", "ANR 495"],
      },
    ],
  },
  APS_MINOR: {
    code: "APS_MINOR",
    name: "Appalachian Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required Appalachian studies courses",
        coursesRequired: 3,
        courses: ["APS 121", "APS 132", "APS 229"],
        mustInclude: ["APS 121", "APS 132", "APS 229"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["APS 140", "APS 210", "APS 213", "APS 215", "APS 220", "APS 224", "APS 225", "APS 230", "APS 330"],
      },
    ],
  },
  ART_STUDIO_MINOR: {
    code: "ART_STUDIO_MINOR",
    name: "Art Studio",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Core",
        description: "Required art studio courses",
        coursesRequired: 4,
        courses: ["ART 134", "ART 135", "ART 136", "ART 137"],
        mustInclude: ["ART 134", "ART 135", "ART 136", "ART 137"],
      },
      {
        category: "Studio Distribution",
        description: "Studio distribution courses at 200-level or above",
        coursesRequired: 2,
        courses: ["ART 211", "ART 216", "ART 225", "ART 230", "ART 311", "ART 316", "ART 325", "ART 330", "ART 411", "ART 416", "ART 425", "ART 430"],
        minUpperLevel: 2,
      },
    ],
  },
  ARH_MINOR: {
    code: "ARH_MINOR",
    name: "Art History",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Core",
        description: "Core art history courses",
        coursesRequired: 2,
        courses: ["ARH 121", "ARH 124", "ARH 340"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 2 at 200-level+, at least 1 non-Western",
        coursesRequired: 3,
        courses: ["ARH 121", "ARH 124", "ARH 130", "ARH 210", "ARH 230", "ARH 232", "ARH 234", "ARH 239", "ARH 242", "ARH 243", "ARH 249", "ARH 262", "ARH 263", "ARH 265", "ARH 286", "ARH 386", "ARH 486", "ARH 395", "ARH 495"],
        minUpperLevel: 2,
      },
    ],
  },
  AST_MINOR: {
    code: "AST_MINOR",
    name: "Asian Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Intro",
        description: "Required introduction course",
        coursesRequired: 1,
        courses: ["AST 100"],
        mustInclude: ["AST 100"],
      },
      {
        category: "Methods",
        description: "Methods course",
        coursesRequired: 1,
        courses: ["AST 229", "AST 240", "AST 243"],
      },
      {
        category: "Electives",
        description: "Elective courses",
        coursesRequired: 3,
        courses: ["AST 100", "AST 122", "AST 123", "AST 132", "AST 135", "AST 206", "AST 229", "AST 240", "AST 243", "AST 249", "AST 260", "AST 271", "AST 324A", "AST 324C", "AST 324J", "AST 325A", "AST 325C", "AST 325J"],
      },
    ],
  },
  CHM_MINOR: {
    code: "CHM_MINOR",
    name: "Chemistry",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required chemistry courses",
        coursesRequired: 5,
        courses: ["CHM 131", "CHM 221", "CHM 222", "CHM 311", "CHM 361", "CHM 362"],
      },
      {
        category: "Collateral",
        description: "Collateral courses",
        coursesRequired: 2,
        courses: ["MAT 135", "PHY 127", "PHY 221"],
      },
    ],
  },
  GEO_MINOR: {
    code: "GEO_MINOR",
    name: "Geology",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required",
        description: "Required geology course",
        coursesRequired: 1,
        courses: ["GEO 101"],
        mustInclude: ["GEO 101"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 2 GEO at 200+ level",
        coursesRequired: 4,
        courses: ["GEO 101", "GEO 200", "GEO 320", "ANR 240", "CHM 311", "CHM 361", "CHM 451", "PHY 365", "PHY 485"],
        minUpperLevel: 2,
      },
    ],
  },
  ENV_MINOR: {
    code: "ENV_MINOR",
    name: "Environmental Science",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Core",
        description: "Required core courses",
        coursesRequired: 3,
        courses: ["GEO 101", "BIO 110", "CHM 131", "BIO 310", "GEO 320"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 3,
        courses: ["ANR 130", "ANR 240", "ANR 342", "BIO 222", "BIO 344", "CHM 221", "CHM 311", "GEO 200", "GEO 320"],
      },
    ],
  },
  CFS_MINOR: {
    code: "CFS_MINOR",
    name: "Child and Family Studies",
    totalMinorCredits: 11,
    requirements: [
      {
        category: "Required Core",
        description: "Required core courses",
        coursesRequired: 4,
        courses: ["CFS 130", "CFS 145", "CFS 207", "CFS 221"],
        mustInclude: ["CFS 130", "CFS 145", "CFS 207", "CFS 221"],
      },
      {
        category: "Child Development",
        description: "Child development course",
        coursesRequired: 1,
        courses: ["CFS 210", "CFS 313", "CFS 315", "CFS 353", "CFS 356"],
      },
      {
        category: "Nutrition/Food Studies",
        description: "Nutrition/food studies course",
        coursesRequired: 1,
        courses: ["CFS 103", "CFS 115", "CFS 209", "CFS 300", "CFS 318"],
      },
      {
        category: "Family Studies",
        description: "Family studies course",
        coursesRequired: 1,
        courses: ["CFS 201", "CFS 237", "CFS 238", "CFS 245", "CFS 317", "CFS 350", "CFS 362", "CFS 366"],
      },
    ],
  },
  COM_MINOR: {
    code: "COM_MINOR",
    name: "Communication",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required communication courses",
        coursesRequired: 2,
        courses: ["COM 100", "COM 220"],
        mustInclude: ["COM 100", "COM 220"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 2 COM courses",
        coursesRequired: 3,
        courses: ["BUS 257", "ENG 284", "ENG 380", "ETAD 180", "ETAD 382", "PHI 106", "PSY 210", "SOC 220", "THR 227", "COM 112", "COM 113", "COM 204", "COM 206", "COM 207", "COM 211", "COM 302", "COM 303", "COM 305", "COM 310", "COM 311", "COM 312", "COM 314", "COM 315"],
      },
    ],
  },
  ECO_MINOR: {
    code: "ECO_MINOR",
    name: "Economics",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required economics courses",
        coursesRequired: 3,
        courses: ["ECO 101", "ECO 102", "ECO 250"],
        mustInclude: ["ECO 101", "ECO 102", "ECO 250"],
      },
      {
        category: "Distribution",
        description: "Distribution courses at ECO 200+ level",
        coursesRequired: 2,
        courses: ["ECO 248", "ECO 301", "ECO 302", "ECO 305", "ECO 332", "ECO 341", "ECO 347", "ECO 350", "ECO 357", "ECO 360", "ECO 370"],
        minUpperLevel: 2,
      },
    ],
  },
  BUS_MINOR: {
    code: "BUS_MINOR",
    name: "Business Administration",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required business courses",
        coursesRequired: 3,
        courses: ["BUS 120", "BUS 315", "ECO 101", "ECO 102"],
      },
      {
        category: "Distribution",
        description: "Distribution courses at BUS 200+ level",
        coursesRequired: 2,
        courses: ["BUS 130", "BUS 221", "BUS 240", "BUS 257", "BUS 315", "BUS 323", "BUS 324", "BUS 326", "BUS 327", "BUS 328", "BUS 345", "BUS 346", "BUS 363", "BUS 364", "BUS 366", "BUS 367", "BUS 368", "BUS 371"],
        minUpperLevel: 2,
      },
    ],
  },
  ENG_MINOR: {
    code: "ENG_MINOR",
    name: "English",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Core",
        description: "Core English course",
        coursesRequired: 1,
        courses: ["ENG 110", "ENG 124", "ENG 270"],
      },
      {
        category: "Distribution",
        description: "Distribution courses at 200+ level, at least 1 at 300-level",
        coursesRequired: 4,
        courses: ["ENG 200", "ENG 205", "ENG 210", "ENG 225", "ENG 240", "ENG 250", "ENG 270", "ENG 280", "ENG 305", "ENG 310", "ENG 325", "ENG 340", "ENG 350"],
        minUpperLevel: 1,
      },
    ],
  },
  CW_MINOR: {
    code: "CW_MINOR",
    name: "Creative Writing",
    totalMinorCredits: 4,
    requirements: [
      {
        category: "Required",
        description: "Required creative writing course",
        coursesRequired: 1,
        courses: ["ENG 124"],
        mustInclude: ["ENG 124"],
      },
      {
        category: "Creative Writing Workshops",
        description: "Creative writing workshops (choose 3 of 4)",
        coursesRequired: 3,
        courses: ["ENG 282F", "ENG 282NF", "ENG 282P", "ENG 282E"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["ENG 382"],
        mustInclude: ["ENG 382"],
      },
    ],
  },
  AFR_MINOR: {
    code: "AFR_MINOR",
    name: "African American Studies",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Intro",
        description: "Required introduction course",
        coursesRequired: 1,
        courses: ["AFR 222"],
        mustInclude: ["AFR 222"],
      },
      {
        category: "Core",
        description: "Core courses",
        coursesRequired: 1,
        courses: ["AFR 103", "AFR 165", "AFR 166", "AFR 167"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 4,
        courses: ["AFR 100", "AFR 132", "AFR 135", "AFR 136", "AFR 138", "AFR 141", "AFR 200", "AFR 201", "AFR 202", "AFR 204", "AFR 207", "AFR 212", "AFR 225", "AFR 230", "AFR 234", "AFR 238", "AFR 242", "AFR 245", "AFR 248", "AFR 249", "AFR 255", "AFR 306", "AFR 309", "AFR 356"],
      },
    ],
  },
  FRN_MINOR: {
    code: "FRN_MINOR",
    name: "French",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Core",
        description: "Required French course",
        coursesRequired: 1,
        courses: ["FRN 103"],
        mustInclude: ["FRN 103"],
      },
      {
        category: "Upper-Level French",
        description: "Upper-level French courses",
        coursesRequired: 4,
        courses: ["FRN 200", "FRN 210", "FRN 220", "FRN 300", "FRN 310", "FRN 320", "FRN 330", "FRN 395", "FRN 495"],
        minUpperLevel: 4,
      },
    ],
  },
  SPN_MINOR: {
    code: "SPN_MINOR",
    name: "Spanish",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Core",
        description: "Required Spanish course",
        coursesRequired: 1,
        courses: ["SPN 103"],
        mustInclude: ["SPN 103"],
      },
      {
        category: "Upper-Level Spanish",
        description: "Upper-level Spanish courses at 300-level",
        coursesRequired: 4,
        courses: ["SPN 310", "SPN 312", "SPN 315", "SPN 320", "SPN 330", "SPN 340", "SPN 395", "SPN 495"],
        minUpperLevel: 4,
      },
    ],
  },
  GER_MINOR: {
    code: "GER_MINOR",
    name: "German",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Core",
        description: "Required German course",
        coursesRequired: 1,
        courses: ["GER 103"],
        mustInclude: ["GER 103"],
      },
      {
        category: "Upper-Level German",
        description: "Upper-level German courses",
        coursesRequired: 4,
        courses: ["GER 200", "GER 210", "GER 220", "GER 300", "GER 310", "GER 320", "GER 395", "GER 495"],
        minUpperLevel: 4,
      },
    ],
  },
  CLS_MINOR: {
    code: "CLS_MINOR",
    name: "Classical Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Core",
        description: "Core classical studies course",
        coursesRequired: 1,
        courses: ["LAT 102", "GRK 202"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 4,
        courses: ["CLS 110", "CLS 117", "CLS 129", "CLS 222", "ARH 232", "PHI 305"],
      },
    ],
  },
  DANCE_MINOR: {
    code: "DANCE_MINOR",
    name: "Dance",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required",
        description: "Required dance course",
        coursesRequired: 1,
        courses: ["HHP 245"],
        mustInclude: ["HHP 245"],
      },
      {
        category: "Activity Course",
        description: "Activity course",
        coursesRequired: 1,
        courses: ["WELL 204", "WELL 206P", "WELL 206Y", "WELL 206Z", "WELL 215", "WELL 216", "WELL 224", "WELL 227", "WELL 228", "WELL 229"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 3,
        courses: ["HHP 248", "HHP 249", "HHP 305", "WELL 204", "WELL 205", "WELL 224", "WELL 227", "WELL 230", "WELL 233", "WELL 334", "WELL 434"],
      },
    ],
  },
  HLT_MINOR: {
    code: "HLT_MINOR",
    name: "Health Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required health courses",
        coursesRequired: 2,
        courses: ["HLT 200", "HLT 227"],
        mustInclude: ["HLT 200", "HLT 227"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["HHP 262", "CFS 221", "HLT 111", "HLT 203", "HLT 205", "HLT 210", "HLT 224", "HLT 236", "HLT 300", "SOC 200"],
      },
      {
        category: "Additional",
        description: "Additional course",
        coursesRequired: 1,
        courses: ["HHP 262", "CFS 221", "HLT 111", "HLT 203", "HLT 205", "HLT 210", "HLT 224", "HLT 236", "HLT 300", "HLT 395", "SOC 200"],
      },
    ],
  },
  HIS_MINOR: {
    code: "HIS_MINOR",
    name: "History",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required history course",
        coursesRequired: 1,
        courses: ["HIS 200"],
        mustInclude: ["HIS 200"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 4,
        courses: ["HIS 103", "HIS 112", "HIS 122", "HIS 123", "HIS 124", "HIS 126", "HIS 127", "HIS 128", "HIS 129", "HIS 130", "HIS 131", "HIS 132", "HIS 133", "HIS 134", "HIS 140", "HIS 161", "HIS 162", "HIS 165", "HIS 175", "HIS 201", "HIS 224", "HIS 229", "HIS 242", "HIS 245", "HIS 246", "HIS 250", "HIS 303", "HIS 309", "HIS 310", "HIS 311", "HIS 320", "HIS 324A", "HIS 324C", "HIS 324J", "HIS 335", "HIS 355", "HIS 356"],
      },
    ],
  },
  MAT_MINOR: {
    code: "MAT_MINOR",
    name: "Mathematics",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required mathematics courses",
        coursesRequired: 3,
        courses: ["MAT 135", "MAT 225", "MAT 214", "MAT 315"],
        mustInclude: ["MAT 135", "MAT 225"],
      },
      {
        category: "Advanced Distribution",
        description: "Advanced mathematics courses at MAT 310+ level",
        coursesRequired: 2,
        courses: ["MAT 311", "MAT 312", "MAT 315", "MAT 321", "MAT 330", "MAT 337", "MAT 415", "MAT 432", "MAT 433", "MAT 434", "MAT 435", "MAT 436", "MAT 438"],
        minUpperLevel: 2,
      },
    ],
  },
  MUS_MINOR: {
    code: "MUS_MINOR",
    name: "Music",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Core Literature",
        description: "Core music literature course",
        coursesRequired: 1,
        courses: ["MUS 115", "MUS 331"],
      },
      {
        category: "Theory Core",
        description: "Theory core courses",
        coursesRequired: 2,
        courses: ["MUS 220", "MUS 221", "MUS 222", "MUS 223"],
        mustInclude: ["MUS 220", "MUS 221", "MUS 222", "MUS 223"],
      },
      {
        category: "Applied Music",
        description: "Applied music courses",
        coursesRequired: 2,
        courses: ["MUA 105", "MUA 115", "MUA 125", "MUA 135", "MUA 205", "MUA 215", "MUA 225", "MUA 235", "MUA 305", "MUA 315", "MUA 325", "MUA 335", "MUA 405", "MUA 415", "MUA 425", "MUA 435"],
      },
      {
        category: "Ensemble",
        description: "Ensemble courses",
        coursesRequired: 1,
        courses: ["MUS 130A", "MUS 130B", "MUS 130C", "MUS 130D", "MUS 130E", "MUS 130F", "MUS 130G", "MUS 130H", "MUS 130K", "MUS 130M", "MUS 131"],
      },
      {
        category: "Additional",
        description: "Additional music course",
        coursesRequired: 1,
        courses: ["MUS 106", "MUS 115", "MUS 118", "MUS 224", "MUS 234", "MUS 320", "MUS 321", "MUS 322", "MUS 323", "MUS 324", "MUS 330", "MUS 331"],
      },
    ],
  },
  TRAD_MUS_MINOR: {
    code: "TRAD_MUS_MINOR",
    name: "Traditional Music",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Core Music",
        description: "Core traditional music course",
        coursesRequired: 1,
        courses: ["MUS 224", "MUS 106", "MUS 234"],
      },
      {
        category: "Theory Foundations",
        description: "Theory foundations courses",
        coursesRequired: 2,
        courses: ["MUS 118A", "MUS 324"],
        mustInclude: ["MUS 118A", "MUS 324"],
      },
      {
        category: "Applied Lessons",
        description: "Applied lessons courses",
        coursesRequired: 2,
        courses: ["MUA 105", "MUA 106", "MUA 107", "MUA 108", "MUA 325", "MUA 326", "MUA 327", "MUA 328", "MUA 335", "MUA 336", "MUA 337", "MUA 338", "MUA 340", "MUA 345", "MUA 346", "MUA 347", "MUA 348", "MUA 400"],
      },
      {
        category: "Ensemble",
        description: "Ensemble course",
        coursesRequired: 1,
        courses: ["MUS 130F", "MUS 130H", "MUS 130K", "MUS 130M", "MUS 135"],
      },
      {
        category: "Elective",
        description: "Elective course",
        coursesRequired: 1,
        courses: ["MUS 106", "MUS 115", "MUS 118", "MUS 224", "MUS 234", "MUS 324", "MUS 330", "MUS 331"],
      },
    ],
  },
  PHI_MINOR: {
    code: "PHI_MINOR",
    name: "Philosophy",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Logic",
        description: "Logic course",
        coursesRequired: 1,
        courses: ["PHI 106", "PHI 218"],
      },
      {
        category: "History of Philosophy",
        description: "History of philosophy course",
        coursesRequired: 1,
        courses: ["PHI 305", "PHI 310", "PHI 315"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 1 above 100 level",
        coursesRequired: 3,
        courses: ["PHI 104", "PHI 106", "PHI 214", "PHI 215", "PHI 218", "PHI 230", "PHI 241", "PHI 244", "PHI 261", "PHI 305", "PHI 310", "PHI 315", "PHI 380"],
        minUpperLevel: 1,
      },
    ],
  },
  PHY_MINOR: {
    code: "PHY_MINOR",
    name: "Physics",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required physics courses",
        coursesRequired: 3,
        courses: ["PHY 221", "PHY 222", "PHY 320"],
        mustInclude: ["PHY 221", "PHY 222", "PHY 320"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["PHY 111", "PHY 130", "PHY 321", "PHY 335", "PHY 365", "PHY 460", "PHY 481", "PHY 482", "PHY 485"],
      },
    ],
  },
  PSC_MINOR: {
    code: "PSC_MINOR",
    name: "Political Science",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Core",
        description: "Required political science courses",
        coursesRequired: 4,
        courses: ["PSC 100", "PSC 110", "PSC 220", "PSC 250"],
        mustInclude: ["PSC 100", "PSC 110", "PSC 220", "PSC 250"],
      },
      {
        category: "Distribution",
        description: "Distribution courses at 200-400 level",
        coursesRequired: 2,
        courses: ["PSC 210", "PSC 212", "PSC 314", "PSC 317", "PSC 319", "PSC 322", "PSC 330", "PSC 351", "PSC 355", "PSC 360"],
        minUpperLevel: 2,
      },
    ],
  },
  REL_MINOR: {
    code: "REL_MINOR",
    name: "Religion",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required religion course",
        coursesRequired: 1,
        courses: ["REL 100"],
        mustInclude: ["REL 100"],
      },
      {
        category: "Religion Department Courses",
        description: "Religion department courses, at least 1 at 200-level, at least 1 at 300-level",
        coursesRequired: 2,
        courses: ["REL 105", "REL 107", "REL 109", "REL 136", "REL 201", "REL 204", "REL 211", "REL 212", "REL 222", "REL 224", "REL 225", "REL 228", "REL 235", "REL 238", "REL 240", "REL 242", "REL 250", "REL 255", "REL 260", "REL 271", "REL 281", "REL 302", "REL 480"],
        minUpperLevel: 2,
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["REL 105", "REL 107", "REL 109", "REL 136", "REL 201", "REL 204", "REL 211", "REL 212", "REL 222", "REL 224", "REL 225", "REL 228", "REL 235", "REL 238", "REL 240", "REL 242", "REL 250", "REL 255", "REL 260", "REL 271", "REL 281"],
      },
    ],
  },
  SOC_MINOR: {
    code: "SOC_MINOR",
    name: "Sociology",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Core",
        description: "Required sociology courses",
        coursesRequired: 2,
        courses: ["SOC 100", "SOC 335"],
        mustInclude: ["SOC 100", "SOC 335"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 4,
        courses: ["SOC 110", "SOC 200", "SOC 202", "SOC 210", "SOC 212", "SOC 215", "SOC 220", "SOC 223", "SOC 300", "SOC 325", "SOC 330", "SOC 341", "SOC 345", "SOC 348", "SOC 350", "SOC 461"],
      },
    ],
  },
  SENS_MINOR: {
    code: "SENS_MINOR",
    name: "Sustainability and Environmental Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required core course",
        coursesRequired: 1,
        courses: ["SENS 100"],
        mustInclude: ["SENS 100"],
      },
      {
        category: "SENS Upper-Level",
        description: "Upper-level SENS courses",
        coursesRequired: 2,
        courses: ["SENS 215", "SENS 225", "SENS 310", "SENS 320", "SENS 340", "SENS 345", "SENS 370", "SENS 395", "SENS 460", "SENS 495"],
        minUpperLevel: 2,
      },
      {
        category: "Natural Science Group",
        description: "Natural science group course",
        coursesRequired: 1,
        courses: ["ANR 130", "ANR 240", "ANR 360", "BIO 110", "BIO 114", "BIO 342", "BIO 344", "CHM 131", "SENS 310"],
      },
      {
        category: "Social Justice/Economics Group",
        description: "Social justice/economics group course",
        coursesRequired: 1,
        courses: ["APS 215", "APS 225", "APS 229", "CFS 145", "ECO 102", "ECO 341", "ECO 370", "PHI 104", "PHI 230", "PSC 250", "SENS 320", "SENS 340", "SENS 345", "SOC 110"],
      },
    ],
  },
  THR_MINOR: {
    code: "THR_MINOR",
    name: "Theatre",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required theatre course",
        coursesRequired: 1,
        courses: ["THR 105"],
        mustInclude: ["THR 105"],
      },
      {
        category: "Core Choice",
        description: "Core choice course",
        coursesRequired: 1,
        courses: ["THR 115", "THR 124", "THR 213"],
      },
      {
        category: "Electives",
        description: "Elective courses, at least 2 at 200+ level",
        coursesRequired: 3,
        courses: ["THR 115", "THR 124", "THR 135", "THR 202", "THR 213", "THR 218", "THR 227", "THR 232", "THR 233", "THR 300", "THR 301", "THR 302", "THR 303", "THR 304", "THR 308", "THR 317", "THR 321", "THR 331", "THR 332"],
        minUpperLevel: 2,
      },
    ],
  },
  WGS_MINOR: {
    code: "WGS_MINOR",
    name: "Women's, Gender, and Sexuality Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required WGS courses",
        coursesRequired: 2,
        courses: ["WGS 124", "WGS 200"],
        mustInclude: ["WGS 124", "WGS 200"],
      },
      {
        category: "Women Concentration",
        description: "Women concentration course",
        coursesRequired: 1,
        courses: ["WGS 103", "WGS 135", "WGS 202", "WGS 230", "WGS 232", "WGS 236", "WGS 243", "WGS 310", "WGS 325"],
      },
      {
        category: "Sexuality Concentration",
        description: "Sexuality concentration course",
        coursesRequired: 1,
        courses: ["WGS 103", "WGS 111", "WGS 201", "WGS 232", "WGS 233"],
      },
      {
        category: "Race or Activism",
        description: "Race or activism course",
        coursesRequired: 1,
        courses: ["APS 229", "ECO 370", "PSJ 100", "PSJ 205", "PSJ 210", "WGS 103", "WGS 202", "WGS 204", "WGS 207", "WGS 225", "WGS 233", "WGS 240", "WGS 366", "AFR 204", "AFR 242", "AFR 250", "PSJ 200"],
      },
    ],
  },
  FILM_MINOR: {
    code: "FILM_MINOR",
    name: "Film Production",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required film courses",
        coursesRequired: 3,
        courses: ["THR 135", "THR 331", "THR 332"],
        mustInclude: ["THR 135", "THR 331", "THR 332"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["ETAD 180", "ETAD 202", "THR 202", "THR 220", "THR 317"],
      },
    ],
  },
  CCE_MINOR: {
    code: "CCE_MINOR",
    name: "Community and Civic Engagement",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Core",
        description: "Required core courses",
        coursesRequired: 2,
        courses: ["SOC 212", "PSC 212", "PSJ 212", "GST 425"],
      },
      {
        category: "Power and Inequality",
        description: "Power and inequality course",
        coursesRequired: 1,
        courses: ["AFR 204", "APS 132", "APS 200", "APS 215", "APS 225", "APS 229", "CFS 318", "CFS 350", "CFS 362", "ECO 248", "EDS 150", "EDS 349", "HIS 309", "HLT 210", "HLT 236", "PHI 244", "PSJ 100", "SENS 100", "SOC 100", "SOC 110", "SOC 202", "SOC 215", "SOC 223", "WGS 124", "WGS 200", "WGS 208"],
      },
      {
        category: "Community and Identity",
        description: "Community and identity course",
        coursesRequired: 1,
        courses: ["AFR 135", "AFR 165", "AFR 230", "AFR 245", "APS 100", "APS 121", "APS 140", "APS 224", "ARH 230", "ARH 239", "ARH 243", "CFS 201", "CFS 209", "CFS 231", "CFS 356", "HLT 111", "PHI 261", "PSJ 103", "PSJ 200", "PSJ 210", "SOC 330", "WGS 206", "WGS 233"],
      },
      {
        category: "Civic Literacy",
        description: "Civic literacy course",
        coursesRequired: 1,
        courses: ["PSC 100", "PSC 110"],
      },
      {
        category: "Civic Skills",
        description: "Civic skills course",
        coursesRequired: 1,
        courses: ["CFS 245", "COM 100", "COM 112", "COM 113", "COM 305", "COM 310", "HLT 203", "HLT 300", "PHI 104", "PHI 214", "PHI 241", "PSJ 200", "PSJ 205", "PSJ 301", "PSJ 305"],
      },
    ],
  },
  DM_MINOR: {
    code: "DM_MINOR",
    name: "Digital Media",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Survey Courses",
        description: "Survey courses",
        coursesRequired: 2,
        courses: ["COM 211", "CSC 111", "CSC 121", "ETAD 180", "THR 135"],
      },
      {
        category: "Production Courses",
        description: "Production courses",
        coursesRequired: 2,
        courses: ["COM 311", "ETAD 202", "ETAD 382", "THR 331", "THR 332"],
      },
      {
        category: "400-Level Course",
        description: "400-level course",
        coursesRequired: 1,
        courses: ["COM 498", "COM 495", "COM 490", "COM 497"],
      },
    ],
  },
  EM_MINOR: {
    code: "EM_MINOR",
    name: "Electronic Music",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Applied Composition",
        description: "Applied composition course",
        coursesRequired: 1,
        courses: ["MUA 105", "MUA 106", "MUA 107", "MUA 108", "MUA 325", "MUA 326", "MUA 327", "MUA 328"],
      },
      {
        category: "Ensemble",
        description: "Ensemble course",
        coursesRequired: 1,
        courses: ["MUS 130A", "MUS 130B", "MUS 130C", "MUS 130D", "MUS 130E", "MUS 130F"],
      },
      {
        category: "Required Courses",
        description: "Required courses",
        coursesRequired: 3,
        courses: ["MUS 324", "COM 104", "ETAD 265"],
        mustInclude: ["MUS 324", "COM 104", "ETAD 265"],
      },
      {
        category: "Computer Science",
        description: "Computer science course",
        coursesRequired: 1,
        courses: ["CSC 110", "CSC 111", "CSC 114", "CSC 121", "CSC 124", "CSC 126", "CSC 127", "CSC 226", "CSC 236"],
      },
    ],
  },
  FRM_MINOR: {
    code: "FRM_MINOR",
    name: "Forest Resource Management",
    totalMinorCredits: 7,
    requirements: [
      {
        category: "Core Knowledge",
        description: "Core knowledge courses",
        coursesRequired: 2,
        courses: ["BIO 344", "ANR 360"],
        mustInclude: ["BIO 344", "ANR 360"],
      },
      {
        category: "Foundation Courses",
        description: "Foundation courses",
        coursesRequired: 3,
        courses: ["BIO 110", "ANR 130", "BIO 114", "ANR 240"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["ANR 342", "SENS 310", "SENS 320", "BIO 327", "BIO 332", "BIO 342", "ECO 102", "ETAD 140", "ETAD 340", "ANR 375", "ECO 370"],
      },
    ],
  },
  LES_MINOR: {
    code: "LES_MINOR",
    name: "Law, Ethics, and Society",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required core course",
        coursesRequired: 1,
        courses: ["LES 215"],
        mustInclude: ["LES 215"],
      },
      {
        category: "Structures of Law",
        description: "Structures of law course",
        coursesRequired: 1,
        courses: ["BUS 240", "CFS 350", "PSC 100", "PSC 110", "PSC 314", "PSC 317"],
      },
      {
        category: "Law and Ethics",
        description: "Law and ethics course",
        coursesRequired: 1,
        courses: ["AFR 225", "PHI 104"],
      },
      {
        category: "Additional",
        description: "Additional courses",
        coursesRequired: 2,
        courses: ["LES 370", "LES 371", "PHI 106", "PSJ 113", "SOC 215", "BUS 240", "CFS 350", "PSC 100", "PSC 110", "PSC 314", "PSC 317", "AFR 225", "PHI 104"],
      },
    ],
  },
  MT_MINOR: {
    code: "MT_MINOR",
    name: "Musical Theatre",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required core courses",
        coursesRequired: 5,
        courses: ["THR 105", "THR 115", "HHP 229", "HHP 230", "MUS 200", "MUS 103"],
        mustInclude: ["THR 105", "THR 115", "HHP 229", "HHP 230", "MUS 103"],
      },
      {
        category: "Electives",
        description: "Elective courses to reach 5 total",
        coursesRequired: 0,
        courses: ["AFR 138", "MUS 100", "MUS 130A", "MUS 130C", "MUS 131", "THR 202", "THR 220", "THR 300", "THR 302", "THR 317", "WELL 206Y", "WELL 224", "WELL 227", "WELL 229", "WELL 230"],
      },
    ],
  },
  BJ_MINOR: {
    code: "BJ_MINOR",
    name: "Broadcast Journalism",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Core",
        description: "Required core courses",
        coursesRequired: 3,
        courses: ["COM 211", "COM 212", "COM 398", "COM 395"],
        mustInclude: ["COM 211", "COM 212"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 1 Production Focus + 1 at 300-level",
        coursesRequired: 3,
        courses: ["COM 104", "COM 105", "COM 204", "COM 303", "COM 311", "COM 314", "COM 315", "COM 395", "COM 495", "ETAD 180", "ETAD 202", "THR 115", "THR 135", "THR 227", "THR 331"],
        minUpperLevel: 1,
      },
    ],
  },
};

export const AVAILABLE_MAJORS = [
  { code: "CSC", name: "Computer and Information Science", degree: "B.A." },
  { code: "AFR", name: "African and African American Studies", degree: "B.A." },
  { code: "BIO", name: "Biology", degree: "B.A." },
  { code: "PSY", name: "Psychology", degree: "B.A." },
  { code: "ANR", name: "Agriculture and Natural Resources", degree: "B.S." },
  { code: "ART", name: "Art: Studio", degree: "B.A." },
  { code: "ARH", name: "Art: Art History", degree: "B.A." },
  { code: "AST_COMP", name: "Asian Studies: Comparative Asia", degree: "B.A." },
  { code: "AST_CHI", name: "Asian Studies: Chinese Studies", degree: "B.A." },
  { code: "AST_JPN", name: "Asian Studies: Japanese Studies", degree: "B.A." },
  { code: "CHM_GEN", name: "Chemistry (General Concentration)", degree: "B.A." },
  { code: "CHM_BIO", name: "Chemistry (Biochemistry Concentration)", degree: "B.A." },
  { code: "CHM_PRO", name: "Chemistry (Professional Concentration)", degree: "B.A." },
  { code: "CFS_CD", name: "Child and Family Studies: Child Development", degree: "B.A." },
  { code: "CFS_FS", name: "Child and Family Studies: Family Studies", degree: "B.A." },
  { code: "CFS_NFS", name: "Child and Family Studies: Nutrition and Food Studies", degree: "B.A." },
  { code: "COM", name: "Communication", degree: "B.A." },
  { code: "ECO", name: "Economics", degree: "B.A." },
  { code: "ECO_QUANT", name: "Quantitative Economics", degree: "B.S." },
  { code: "BUS", name: "Business Administration", degree: "B.S." },
  { code: "EDS", name: "Education Studies", degree: "B.A." },
  { code: "ETAD", name: "Engineering Technologies and Applied Design (General)", degree: "B.S." },
  { code: "ETAD_MGMT", name: "Engineering Technologies and Applied Design (Technology Management)", degree: "B.S." },
  { code: "ENG", name: "English", degree: "B.A." },
  { code: "FRN", name: "French", degree: "B.A." },
  { code: "SPN", name: "Spanish", degree: "B.A." },
  { code: "GER", name: "German", degree: "B.A." },
  { code: "HHP", name: "Health and Human Performance", degree: "B.A." },
  { code: "HLT", name: "Health Studies", degree: "B.A." },
  { code: "HIS", name: "History", degree: "B.A." },
  { code: "MAT", name: "Mathematics", degree: "B.A." },
  { code: "MUS", name: "Music", degree: "B.A." },
  { code: "NUR", name: "Nursing", degree: "B.S." },
  { code: "PSJ", name: "Peace and Social Justice Studies", degree: "B.A." },
  { code: "PHI", name: "Philosophy", degree: "B.A." },
  { code: "PHY", name: "Physics", degree: "B.A." },
  { code: "PHY_ENG", name: "Engineering Physics", degree: "B.S." },
  { code: "PSC", name: "Political Science", degree: "B.A." },
  { code: "REL", name: "Religion", degree: "B.A." },
  { code: "SOC", name: "Sociology", degree: "B.A." },
  { code: "SENS", name: "Environmental Science", degree: "B.A." },
  { code: "THR", name: "Theatre", degree: "B.A." },
  { code: "WGS", name: "Women's, Gender, and Sexuality Studies", degree: "B.A." },
];
