// Major requirements data for Berea College
// Based on provided requirements

import type { Course, Major } from "./types";
import { COURSE_CATALOG } from "./course-catalog";

export const MAJORS: Record<string, Major> = {
  CSC: {
    code: "CSC",
    name: "Computer and Information Science",
    degree: "B.A.",
    totalMajorCredits: 12,
    requirements: [
      {
        category: "Exploratory Distribution",
        description: "One course from upper level CSC or approved list",
        coursesRequired: 1,
        courses: [
          "CSC 110",
          "CSC 111",
          "CSC 114",
          "CSC 121",
          "CSC 124",
          "CSC 126",
          "CSC 127",
          "PHY 221",
          "SENS 320",
        ],
      },
      {
        category: "Required Core Courses",
        description: "Core programming and data structures",
        coursesRequired: 3,
        courses: ["CSC 226", "CSC 236", "CSC 246"],
        mustInclude: ["CSC 226", "CSC 236", "CSC 246"],
      },
      {
        category: "Capstone",
        description: "Capstone course (CSC 493 or CSC 495)",
        coursesRequired: 1,
        courses: ["CSC 493", "CSC 495"],
      },
      {
        category: "Upper Level Distribution",
        description:
          "Four upper-level courses with at least one from each category and one at 400 level",
        coursesRequired: 4,
        courses: [
          "CSC 301",
          "CSC 330",
          "CSC 410",
          "CSC 420",
          "CSC 426",
          "CSC 303",
          "CSC 433",
          "CSC 440",
          "CSC 445",
          "CSC 300",
          "CSC 335",
          "CSC 412",
          "CSC 425",
          "CSC 450",
        ],
        minUpperLevel: 1,
        selectFromCategories: [
          {
            category: "Design",
            min: 1,
            courses: ["CSC 301", "CSC 330", "CSC 410", "CSC 420", "CSC 426"],
          },
          {
            category: "Foundations",
            min: 1,
            courses: ["CSC 303", "CSC 433", "CSC 440", "CSC 445"],
          },
          {
            category: "Systems",
            min: 1,
            courses: ["CSC 300", "CSC 335", "CSC 412", "CSC 425", "CSC 450"],
          },
        ],
      },
      {
        category: "Collateral - Discrete Math",
        description: "One discrete mathematics course",
        coursesRequired: 1,
        courses: ["MAT 216", "MAT 312", "MAT 415"],
      },
      {
        category: "Collateral - Electronics",
        description: "One electricity/electronics course",
        coursesRequired: 1,
        courses: ["PHY 221", "PHY 127"],
      },
    ],
  },

  AFR: {
    code: "AFR",
    name: "African and African American Studies",
    degree: "B.A.",
    totalMajorCredits: 9,
    requirements: [
      {
        category: "Required Core Courses",
        description: "Core AFR courses",
        coursesRequired: 4,
        courses: ["AFR 103", "AFR 165", "AFR 222", "AFR 350"],
        mustInclude: ["AFR 103", "AFR 165", "AFR 222", "AFR 350"],
      },
      {
        category: "Capstone",
        description: "Senior seminar",
        coursesRequired: 1,
        courses: ["AFR 450"],
        mustInclude: ["AFR 450"],
      },
      {
        category: "Distribution - Social Science",
        description: "At least one from Social Science area",
        coursesRequired: 1,
        courses: [
          "AFR 132",
          "AFR 200",
          "AFR 201",
          "AFR 202",
          "AFR 204",
          "AFR 225",
          "AFR 242",
          "AFR 245",
          "AFR 255",
          "AFR 356",
        ],
      },
      {
        category: "Distribution - Humanities",
        description: "At least one from Humanities area",
        coursesRequired: 1,
        courses: [
          "AFR 100",
          "AFR 135",
          "AFR 136",
          "AFR 138",
          "AFR 141",
          "AFR 212",
          "AFR 230",
          "AFR 234",
          "AFR 238",
        ],
      },
      {
        category: "Additional AFR Courses",
        description: "Two additional AFR courses",
        coursesRequired: 2,
        courses: [
          "AFR 100",
          "AFR 132",
          "AFR 135",
          "AFR 136",
          "AFR 138",
          "AFR 141",
          "AFR 200",
          "AFR 201",
          "AFR 202",
          "AFR 204",
          "AFR 212",
          "AFR 225",
          "AFR 230",
          "AFR 234",
          "AFR 238",
          "AFR 242",
          "AFR 245",
          "AFR 255",
          "AFR 356",
        ],
      },
    ],
  },

  BIO: {
    code: "BIO",
    name: "Biology",
    degree: "B.A.",
    totalMajorCredits: 14,
    requirements: [
      {
        category: "Required Core Courses",
        description: "Core Biology courses",
        coursesRequired: 5,
        courses: ["BIO 110", "BIO 113", "BIO 114", "BIO 330", "BIO 494"],
        mustInclude: ["BIO 110", "BIO 113", "BIO 114", "BIO 330", "BIO 494"],
      },
      {
        category: "Field Course",
        description: "One field biology course",
        coursesRequired: 1,
        courses: [
          "BIO 310",
          "BIO 324",
          "BIO 327",
          "BIO 332",
          "BIO 338",
          "BIO 342",
          "BIO 344",
          "SENS 226",
        ],
      },
      {
        category: "Distribution",
        description:
          "Four additional credits, at least two must be Biology courses",
        coursesRequired: 4,
        courses: [
          "BIO 207",
          "BIO 220",
          "BIO 222",
          "BIO 306",
          "BIO 310",
          "BIO 323",
          "BIO 324",
          "BIO 325",
          "BIO 327",
          "BIO 331",
          "BIO 332",
          "BIO 338",
          "BIO 342",
          "BIO 344",
          "BIO 346",
          "BIO 441",
          "ANR 310",
          "CHM 340",
          "CHM 345",
          "CHM 440",
          "CFS 221",
          "ECO 250",
          "PHY 340",
          "PSY 212",
          "SENS 226",
        ],
      },
      {
        category: "Collateral - Chemistry",
        description: "Required chemistry sequence",
        coursesRequired: 3,
        courses: ["CHM 131", "CHM 221", "CHM 222"],
        mustInclude: ["CHM 131", "CHM 221", "CHM 222"],
      },
      {
        category: "Collateral - Math",
        description: "College Algebra with Modeling",
        coursesRequired: 1,
        courses: ["MAT 115"],
        mustInclude: ["MAT 115"],
      },
    ],
  },

  PSY: {
    code: "PSY",
    name: "Psychology",
    degree: "B.A.",
    totalMajorCredits: 11,
    requirements: [
      {
        category: "Required Core Courses",
        description: "Core Psychology courses",
        coursesRequired: 3,
        courses: ["PSY 100", "PSY 225", "PSY 325"],
        mustInclude: ["PSY 100", "PSY 225", "PSY 325"],
      },
      {
        category: "Capstone",
        description: "Senior Research",
        coursesRequired: 1,
        courses: ["PSY 424"],
        mustInclude: ["PSY 424"],
      },
      {
        category: "Laboratory Courses",
        description: "Two laboratory courses",
        coursesRequired: 2,
        courses: [
          "PSY 207",
          "PSY 208",
          "PSY 209",
          "PSY 210",
          "PSY 212",
          "PSY 214",
          "PSY 244",
        ],
      },
      {
        category: "Distribution",
        description: "Four additional PSY courses",
        coursesRequired: 4,
        courses: [
          "PSY 207",
          "PSY 208",
          "PSY 209",
          "PSY 210",
          "PSY 212",
          "PSY 214",
          "PSY 244",
          "PSY 390",
          "PSY 490",
          "PSY 395",
          "PSY 495",
          "PSY 397",
          "PSY 497",
          "PSY 398",
          "PSY 498",
        ],
      },
      {
        category: "Science Collateral",
        description:
          "One science course (waived if PSY 212 completed)",
        coursesRequired: 1,
        courses: [
          "BIO 100",
          "BIO 110",
          "CHM 131",
          "PHY 127",
          "PHY 221",
          "PSY 212",
        ],
      },
    ],
  },
};

// List of available majors for UI
export const AVAILABLE_MAJORS = [
  { code: "CSC", name: "Computer and Information Science", degree: "B.A." },
  { code: "AFR", name: "African and African American Studies", degree: "B.A." },
  { code: "BIO", name: "Biology", degree: "B.A." },
  { code: "PSY", name: "Psychology", degree: "B.A." },
];
