// Major requirements data for Berea College
// Based on provided requirements

import type { Major } from "./types";

export const MAJORS: Record<string, Major> = {
  CSC: {
    code: "CSC",
    name: "Computer and Information Science",
    degree: "B.A.",
    totalMajorCredits: 12,
    requirements: [
      {
        category: "Exploratory Distribution",
        description: "One course from upper level CSC or approved list",
        coursesRequired: 1,
        courses: [
          "CSC 110",
          "CSC 111",
          "CSC 114",
          "CSC 121",
          "CSC 124",
          "CSC 126",
          "CSC 127",
          "ETAD 130",
          "ETAD 180",
          "ETAD 330",
          "ETAD 382",
          "ETAD 455",
          "ETAD 460",
          "PHY 221",
          "SENS 320",
        ],
      },
      {
        category: "Required Core Courses",
        description: "Core programming and data structures",
        coursesRequired: 3,
        courses: ["CSC 226", "CSC 236", "CSC 246"],
        mustInclude: ["CSC 226", "CSC 236", "CSC 246"],
      },
      {
        category: "Capstone",
        description: "Capstone course (CSC 493 or CSC 495)",
        coursesRequired: 1,
        courses: ["CSC 493", "CSC 495"],
      },
      {
        category: "Upper Level Distribution",
        description:
          "Four upper-level courses with at least one from each category and one at 400 level",
        coursesRequired: 4,
        courses: [
          "CSC 301",
          "CSC 330",
          "CSC 410",
          "CSC 420",
          "CSC 426",
          "CSC 303",
          "CSC 433",
          "CSC 440",
          "CSC 445",
          "CSC 300",
          "CSC 335",
          "CSC 412",
          "CSC 425",
          "CSC 450",
        ],
        minUpperLevel: 1,
        selectFromCategories: [
          {
            category: "Design",
            min: 1,
            courses: ["CSC 301", "CSC 330", "CSC 410", "CSC 420", "CSC 426"],
          },
          {
            category: "Foundations",
            min: 1,
            courses: ["CSC 303", "CSC 433", "CSC 440", "CSC 445"],
          },
          {
            category: "Systems",
            min: 1,
            courses: ["CSC 300", "CSC 335", "CSC 412", "CSC 425", "CSC 450"],
          },
        ],
      },
      {
        category: "Collateral - Discrete Math",
        description: "One discrete mathematics course",
        coursesRequired: 1,
        courses: ["MAT 216", "MAT 312", "MAT 415"],
      },
      {
        category: "Collateral - Electronics",
        description: "One electricity/electronics course",
        coursesRequired: 1,
        courses: ["ETAD 265", "ETAD 460"],
      },
    ],
  },

  ETAD: {
    code: "ETAD",
    name: "Engineering Technologies and Applied Design",
    degree: "B.S.",
    totalMajorCredits: 11,
    requirements: [
      {
        category: "Required Core Courses",
        description: "Core ETAD courses",
        coursesRequired: 6,
        courses: [
          "ETAD 130",
          "ETAD 140",
          "ETAD 180",
          "ETAD 245",
          "ETAD 265",
          "ETAD 275",
        ],
        mustInclude: [
          "ETAD 130",
          "ETAD 140",
          "ETAD 180",
          "ETAD 245",
          "ETAD 265",
          "ETAD 275",
        ],
      },
      {
        category: "Capstone",
        description: "Research in Technology",
        coursesRequired: 1,
        courses: ["ETAD 488"],
        mustInclude: ["ETAD 488"],
      },
      {
        category: "Advanced Distribution",
        description: "Three 300 or 400 level ETAD courses",
        coursesRequired: 3,
        courses: [
          "ETAD 330",
          "ETAD 382",
          "ETAD 455",
          "ETAD 460",
          "ETAD 470",
          "ETAD 480",
        ],
      },
      {
        category: "Collateral - Math",
        description: "MAT 105 or higher level math",
        coursesRequired: 1,
        courses: ["MAT 105", "MAT 115", "MAT 135", "MAT 216", "MAT 225"],
      },
    ],
  },

  AFR: {
    code: "AFR",
    name: "African and African American Studies",
    degree: "B.A.",
    totalMajorCredits: 9,
    requirements: [
      {
        category: "Required Core Courses",
        description: "Core AFR courses",
        coursesRequired: 4,
        courses: ["AFR 103", "AFR 165", "AFR 222", "AFR 350"],
        mustInclude: ["AFR 103", "AFR 165", "AFR 222", "AFR 350"],
      },
      {
        category: "Capstone",
        description: "Senior seminar",
        coursesRequired: 1,
        courses: ["AFR 450"],
        mustInclude: ["AFR 450"],
      },
      {
        category: "Distribution - Social Science",
        description: "At least one from Social Science area",
        coursesRequired: 1,
        courses: [
          "AFR 132",
          "AFR 200",
          "AFR 201",
          "AFR 202",
          "AFR 204",
          "AFR 225",
          "AFR 242",
          "AFR 245",
          "AFR 255",
          "AFR 356",
        ],
      },
      {
        category: "Distribution - Humanities",
        description: "At least one from Humanities area",
        coursesRequired: 1,
        courses: [
          "AFR 100",
          "AFR 135",
          "AFR 136",
          "AFR 138",
          "AFR 141",
          "AFR 212",
          "AFR 230",
          "AFR 234",
          "AFR 238",
        ],
      },
      {
        category: "Additional AFR Courses",
        description: "Two additional AFR courses",
        coursesRequired: 2,
        courses: [
          "AFR 100",
          "AFR 132",
          "AFR 135",
          "AFR 136",
          "AFR 138",
          "AFR 141",
          "AFR 200",
          "AFR 201",
          "AFR 202",
          "AFR 204",
          "AFR 212",
          "AFR 225",
          "AFR 230",
          "AFR 234",
          "AFR 238",
          "AFR 242",
          "AFR 245",
          "AFR 255",
          "AFR 356",
        ],
      },
    ],
  },

  BIO: {
    code: "BIO",
    name: "Biology",
    degree: "B.A.",
    totalMajorCredits: 14,
    requirements: [
      {
        category: "Required Core Courses",
        description: "Core Biology courses",
        coursesRequired: 5,
        courses: ["BIO 110", "BIO 113", "BIO 114", "BIO 330", "BIO 494"],
        mustInclude: ["BIO 110", "BIO 113", "BIO 114", "BIO 330", "BIO 494"],
      },
      {
        category: "Field Course",
        description: "One field biology course",
        coursesRequired: 1,
        courses: [
          "BIO 310",
          "BIO 324",
          "BIO 327",
          "BIO 332",
          "BIO 338",
          "BIO 342",
          "BIO 344",
          "SENS 226",
        ],
      },
      {
        category: "Distribution",
        description:
          "Four additional credits, at least two must be Biology courses",
        coursesRequired: 4,
        courses: [
          "BIO 207",
          "BIO 220",
          "BIO 222",
          "BIO 306",
          "BIO 310",
          "BIO 323",
          "BIO 324",
          "BIO 325",
          "BIO 327",
          "BIO 331",
          "BIO 332",
          "BIO 338",
          "BIO 342",
          "BIO 344",
          "BIO 346",
          "BIO 441",
          "ANR 310",
          "CHM 340",
          "CHM 345",
          "CHM 440",
          "CFS 221",
          "ECO 250",
          "PHY 340",
          "PSY 212",
          "SENS 226",
        ],
      },
      {
        category: "Collateral - Chemistry",
        description: "Required chemistry sequence",
        coursesRequired: 3,
        courses: ["CHM 131", "CHM 221", "CHM 222"],
        mustInclude: ["CHM 131", "CHM 221", "CHM 222"],
      },
      {
        category: "Collateral - Math",
        description: "College Algebra with Modeling",
        coursesRequired: 1,
        courses: ["MAT 115"],
        mustInclude: ["MAT 115"],
      },
    ],
  },

  PSY: {
    code: "PSY",
    name: "Psychology",
    degree: "B.A.",
    totalMajorCredits: 11,
    requirements: [
      {
        category: "Required Core Courses",
        description: "Core Psychology courses",
        coursesRequired: 3,
        courses: ["PSY 100", "PSY 225", "PSY 325"],
        mustInclude: ["PSY 100", "PSY 225", "PSY 325"],
      },
      {
        category: "Capstone",
        description: "Senior Research",
        coursesRequired: 1,
        courses: ["PSY 424"],
        mustInclude: ["PSY 424"],
      },
      {
        category: "Laboratory Courses",
        description: "Two laboratory courses",
        coursesRequired: 2,
        courses: [
          "PSY 207",
          "PSY 208",
          "PSY 209",
          "PSY 210",
          "PSY 212",
          "PSY 214",
          "PSY 244",
        ],
      },
      {
        category: "Distribution",
        description: "Four additional PSY courses",
        coursesRequired: 4,
        courses: [
          "PSY 207",
          "PSY 208",
          "PSY 209",
          "PSY 210",
          "PSY 212",
          "PSY 214",
          "PSY 244",
          "PSY 390",
          "PSY 490",
          "PSY 395",
          "PSY 495",
          "PSY 397",
          "PSY 497",
          "PSY 398",
          "PSY 498",
        ],
      },
      {
        category: "Science Collateral",
        description:
          "One science course (waived if PSY 212 completed)",
        coursesRequired: 1,
        courses: [
          "BIO 100",
          "BIO 110",
          "CHM 131",
          "PHY 127",
          "PHY 221",
          "PSY 212",
        ],
      },
    ],
  },
};

// Course catalog with GEM attributes
export const COURSE_CATALOG: Record<
  string,
  {
    code: string;
    name: string;
    credits: number;
    prerequisites?: string[];
  }
> = {
  // CSC Courses
  "CSC 110": {
    code: "CSC 110",
    name: "Craft of Computing",
    credits: 1,
  },
  "CSC 111": {
    code: "CSC 111",
    name: "Storytelling-Comp Animation",
    credits: 1,
  },
  "CSC 114": {
    code: "CSC 114",
    name: "Business App & Programming",
    credits: 1,
  },
  "CSC 121": {
    code: "CSC 121",
    name: "Introduction to Game Design",
    credits: 1,
  },
  "CSC 124": {
    code: "CSC 124",
    name: "Building Better Apps",
    credits: 1,
  },
  "CSC 126": { code: "CSC 126", name: "Intro to Robotics", credits: 1 },
  "CSC 127": { code: "CSC 127", name: "Intro to Web Design", credits: 1 },
  "CSC 226": {
    code: "CSC 226",
    name: "Software Design & Implement",
    credits: 1,
  },
  "CSC 236": { code: "CSC 236", name: "Data Structures", credits: 1 },
  "CSC 246": {
    code: "CSC 246",
    name: "Scalable Algorithms & Objects",
    credits: 1,
    prerequisites: ["CSC 236"],
  },
  "CSC 300": { code: "CSC 300", name: "Embedded Systems", credits: 1 },
  "CSC 301": {
    code: "CSC 301",
    name: "Human-Centered Computing",
    credits: 1,
  },
  "CSC 303": { code: "CSC 303", name: "Theory of Computation", credits: 1 },
  "CSC 330": { code: "CSC 330", name: "Database Systems", credits: 1 },
  "CSC 335": { code: "CSC 335", name: "Computer Organization", credits: 1 },
  "CSC 410": {
    code: "CSC 410",
    name: "Computational Intelligence",
    credits: 1,
  },
  "CSC 412": { code: "CSC 412", name: "Networking", credits: 1 },
  "CSC 420": { code: "CSC 420", name: "Programming Languages", credits: 1 },
  "CSC 425": { code: "CSC 425", name: "Operating Systems & VMs", credits: 1 },
  "CSC 426": {
    code: "CSC 426",
    name: "Open Source Software Engineering",
    credits: 1,
  },
  "CSC 433": { code: "CSC 433", name: "Numerical Analysis", credits: 1 },
  "CSC 440": {
    code: "CSC 440",
    name: "Design & Analysis of Algorithms",
    credits: 1,
  },
  "CSC 445": {
    code: "CSC 445",
    name: "Computational Complexity & Modeling",
    credits: 1,
  },
  "CSC 450": { code: "CSC 450", name: "Computer Security", credits: 1 },
  "CSC 493": {
    code: "CSC 493",
    name: "Computing Design Practicum",
    credits: 1,
  },
  "CSC 495": { code: "CSC 495", name: "Internship", credits: 1 },

  // ETAD Courses
  "ETAD 130": { code: "ETAD 130", name: "Design and Documentation", credits: 1 },
  "ETAD 140": {
    code: "ETAD 140",
    name: "Design Production in Woods",
    credits: 1,
  },
  "ETAD 180": { code: "ETAD 180", name: "Graphic Com and Design", credits: 1 },
  "ETAD 245": {
    code: "ETAD 245",
    name: "Materials/Processing/Testing",
    credits: 1,
  },
  "ETAD 265": {
    code: "ETAD 265",
    name: "Electricity and Electronics",
    credits: 1,
  },
  "ETAD 275": {
    code: "ETAD 275",
    name: "Power and Energy Technology",
    credits: 1,
  },
  "ETAD 330": {
    code: "ETAD 330",
    name: "Advanced Design & Prototyping",
    credits: 1,
  },
  "ETAD 382": {
    code: "ETAD 382",
    name: "Studio in Graphic Design",
    credits: 1,
  },
  "ETAD 455": {
    code: "ETAD 455",
    name: "Computer Integrated Manufacturing",
    credits: 1,
  },
  "ETAD 460": {
    code: "ETAD 460",
    name: "Electronic System Design",
    credits: 1,
  },
  "ETAD 488": { code: "ETAD 488", name: "Research in Technology", credits: 1 },

  // Math Courses
  "MAT 105": { code: "MAT 105", name: "Intro to Discrete Math", credits: 1 },
  "MAT 115": {
    code: "MAT 115",
    name: "College Algebra with Modeling",
    credits: 1,
  },
  "MAT 135": { code: "MAT 135", name: "Calculus I", credits: 1 },
  "MAT 216": { code: "MAT 216", name: "Discrete Mathematics", credits: 1 },
  "MAT 225": { code: "MAT 225", name: "Calculus II", credits: 1 },
  "MAT 312": { code: "MAT 312", name: "Operations Research", credits: 1 },
  "MAT 415": { code: "MAT 415", name: "Combinatorics", credits: 1 },

  // Biology Courses
  "BIO 100": { code: "BIO 100", name: "Introduction to Biology", credits: 1 },
  "BIO 110": { code: "BIO 110", name: "Modern Biology", credits: 1 },
  "BIO 113": { code: "BIO 113", name: "Experimental Zoology", credits: 1 },
  "BIO 114": { code: "BIO 114", name: "Botany", credits: 1 },
  "BIO 207": {
    code: "BIO 207",
    name: "Pathophysiology: Altered Health",
    credits: 1,
  },
  "BIO 220": {
    code: "BIO 220",
    name: "Comparative Vertebrate Anatomy",
    credits: 1,
  },
  "BIO 222": { code: "BIO 222", name: "Microbiology", credits: 1 },
  "BIO 306": {
    code: "BIO 306",
    name: "Histology and Histotechnique",
    credits: 1,
  },
  "BIO 310": { code: "BIO 310", name: "Ecology", credits: 1 },
  "BIO 323": { code: "BIO 323", name: "Principles of Physiology", credits: 1 },
  "BIO 324": { code: "BIO 324", name: "Parasitology", credits: 1 },
  "BIO 325": { code: "BIO 325", name: "Neurobiology", credits: 1 },
  "BIO 327": { code: "BIO 327", name: "Herpetology", credits: 1 },
  "BIO 330": { code: "BIO 330", name: "Genetics", credits: 1 },
  "BIO 331": { code: "BIO 331", name: "Developmental Biology", credits: 1 },
  "BIO 332": { code: "BIO 332", name: "Mammalogy", credits: 1 },
  "BIO 338": { code: "BIO 338", name: "Ornithology", credits: 1 },
  "BIO 342": { code: "BIO 342", name: "Field Botany", credits: 1 },
  "BIO 344": { code: "BIO 344", name: "Dendrology & Forest Ecology", credits: 1 },
  "BIO 346": { code: "BIO 346", name: "Conservation Biology", credits: 1 },
  "BIO 441": {
    code: "BIO 441",
    name: "Cell and Molecular Biology",
    credits: 1,
  },
  "BIO 494": { code: "BIO 494", name: "Evolution", credits: 1 },

  // Chemistry Courses
  "CHM 131": {
    code: "CHM 131",
    name: "Accelerated General Chemistry",
    credits: 1,
  },
  "CHM 221": { code: "CHM 221", name: "Organic Chemistry I", credits: 1 },
  "CHM 222": { code: "CHM 222", name: "Organic Chemistry II", credits: 1 },
  "CHM 340": { code: "CHM 340", name: "Biochemistry I", credits: 1 },
  "CHM 345": {
    code: "CHM 345",
    name: "Introduction to Biochemistry",
    credits: 1,
  },
  "CHM 440": { code: "CHM 440", name: "Biochemistry II", credits: 1 },

  // Psychology Courses
  "PSY 100": { code: "PSY 100", name: "General Psychology", credits: 1 },
  "PSY 207": {
    code: "PSY 207",
    name: "Principles of Learning w/ Lab",
    credits: 1,
  },
  "PSY 208": {
    code: "PSY 208",
    name: "Cognitive Psychology with Lab",
    credits: 1,
  },
  "PSY 209": { code: "PSY 209", name: "Social Psychology w/ Lab", credits: 1 },
  "PSY 210": { code: "PSY 210", name: "Ind/Org Psychology with Lab", credits: 1 },
  "PSY 212": {
    code: "PSY 212",
    name: "Behavioral Neuroscience w/ Lab",
    credits: 1,
  },
  "PSY 214": { code: "PSY 214", name: "Ethology with Lab", credits: 1 },
  "PSY 225": {
    code: "PSY 225",
    name: "Stats & Research Methods I",
    credits: 1,
  },
  "PSY 244": {
    code: "PSY 244",
    name: "Developmental Psychology with Lab",
    credits: 1,
  },
  "PSY 325": {
    code: "PSY 325",
    name: "Stats & Research Methods II",
    credits: 1,
  },
  "PSY 424": { code: "PSY 424", name: "Senior Research", credits: 1 },

  // African American Studies Courses
  "AFR 100": {
    code: "AFR 100",
    name: "Models & Mentors for Success",
    credits: 1,
  },
  "AFR 103": { code: "AFR 103", name: "Survey of African History", credits: 1 },
  "AFR 132": { code: "AFR 132", name: "Intro to Race in America", credits: 1 },
  "AFR 135": { code: "AFR 135", name: "African-Amer Women Writers", credits: 1 },
  "AFR 136": { code: "AFR 136", name: "African Traditional Religion", credits: 1 },
  "AFR 138": { code: "AFR 138", name: "Black Music Ensemble", credits: 0.25 },
  "AFR 141": { code: "AFR 141", name: "African-American Literature", credits: 1 },
  "AFR 165": {
    code: "AFR 165",
    name: "Intro to African-Amer History",
    credits: 1,
  },
  "AFR 200": { code: "AFR 200", name: "Readings in Black Psychology", credits: 1 },
  "AFR 201": { code: "AFR 201", name: "Food/Agriculture Africa", credits: 1 },
  "AFR 202": {
    code: "AFR 202",
    name: "Women African-Amer Politics",
    credits: 1,
  },
  "AFR 204": {
    code: "AFR 204",
    name: "African Amer Intellectual Thought",
    credits: 1,
  },
  "AFR 212": {
    code: "AFR 212",
    name: "Literature of Caribbean Women",
    credits: 1,
  },
  "AFR 222": {
    code: "AFR 222",
    name: "Intro to African-American Studies",
    credits: 1,
  },
  "AFR 225": { code: "AFR 225", name: "Environmental Justice", credits: 1 },
  "AFR 230": { code: "AFR 230", name: "African Amer in Appalachia", credits: 1 },
  "AFR 234": { code: "AFR 234", name: "African-Amer Music: Overview", credits: 1 },
  "AFR 238": {
    code: "AFR 238",
    name: "African Amer Religious Traditions",
    credits: 1,
  },
  "AFR 242": { code: "AFR 242", name: "African American Cinema", credits: 1 },
  "AFR 245": { code: "AFR 245", name: "Black Urban History", credits: 1 },
  "AFR 255": { code: "AFR 255", name: "Readings Moorish History", credits: 1 },
  "AFR 350": { code: "AFR 350", name: "Sem in Afr & Afr-Amer Studies", credits: 1 },
  "AFR 356": { code: "AFR 356", name: "Sem African-Amer History", credits: 1 },
  "AFR 450": {
    code: "AFR 450",
    name: "Sem in Afr & Afr-Amer Studies II",
    credits: 1,
  },

  // Physics
  "PHY 127": { code: "PHY 127", name: "General Physics I", credits: 1 },
  "PHY 221": { code: "PHY 221", name: "Intro Physics I with Calculus", credits: 1 },
  "PHY 340": { code: "PHY 340", name: "Biophysics", credits: 1 },

  // Other
  "SENS 226": { code: "SENS 226", name: "Coral Reef Ecosystems", credits: 1 },
  "SENS 320": { code: "SENS 320", name: "Intro to GIS", credits: 1 },
  "ANR 310": { code: "ANR 310", name: "Nutritional Studies", credits: 1 },
  "CFS 221": { code: "CFS 221", name: "Fundamentals of Nutrition", credits: 1 },
  "ECO 250": { code: "ECO 250", name: "Applied Statistics", credits: 1 },
};

// List of available majors for UI
export const AVAILABLE_MAJORS = [
  { code: "CSC", name: "Computer and Information Science", degree: "B.A." },
  {
    code: "ETAD",
    name: "Engineering Technologies and Applied Design",
    degree: "B.S.",
  },
  { code: "AFR", name: "African and African American Studies", degree: "B.A." },
  { code: "BIO", name: "Biology", degree: "B.A." },
  { code: "PSY", name: "Psychology", degree: "B.A." },
];
