import type { Minor } from "./types";

export const MINORS: Record<string, Minor> = {
  AFR: {
    code: "AFR",
    name: "African and African American Studies",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Intro",
        description: "Required introduction course",
        coursesRequired: 1,
        courses: ["AFR 222"],
        mustInclude: ["AFR 222"],
      },
      {
        category: "Core",
        description: "Core courses",
        coursesRequired: 1,
        courses: ["AFR 103", "AFR 165", "AFR 166", "AFR 167"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 4,
        courses: ["AFR 100", "AFR 132", "AFR 135", "AFR 136", "AFR 138", "AFR 141", "AFR 200", "AFR 201", "AFR 202", "AFR 204", "AFR 207", "AFR 212", "AFR 225", "AFR 230", "AFR 234", "AFR 238", "AFR 242", "AFR 245", "AFR 248", "AFR 249", "AFR 255", "AFR 306", "AFR 309", "AFR 356"],
      },
    ],
  },
  ANR: {
    code: "ANR",
    name: "Agriculture and Natural Resources",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required",
        description: "Required ANR course",
        coursesRequired: 1,
        courses: ["ANR 100"],
        mustInclude: ["ANR 100"],
      },
      {
        category: "ANR Electives",
        description: "ANR elective courses",
        coursesRequired: 5,
        courses: ["ANR 110", "ANR 130", "ANR 201", "ANR 240", "ANR 290", "ANR 310", "ANR 318", "ANR 320", "ANR 334", "ANR 342", "ANR 345", "ANR 360", "ANR 375", "ANR 395", "ANR 495"],
      },
    ],
  },
  APS: {
    code: "APS",
    name: "Appalachian Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required Appalachian studies courses",
        coursesRequired: 3,
        courses: ["APS 121", "APS 132", "APS 229"],
        mustInclude: ["APS 121", "APS 132", "APS 229"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["APS 140", "APS 210", "APS 213", "APS 215", "APS 220", "APS 224", "APS 225", "APS 230", "APS 330"],
      },
    ],
  },
  ARH: {
    code: "ARH",
    name: "Art: History",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Core",
        description: "Core art history courses",
        coursesRequired: 2,
        courses: ["ARH 121", "ARH 124", "ARH 340"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 2 at 200-level+, at least 1 non-Western",
        coursesRequired: 3,
        courses: ["ARH 121", "ARH 124", "ARH 130", "ARH 210", "ARH 230", "ARH 232", "ARH 234", "ARH 239", "ARH 242", "ARH 243", "ARH 249", "ARH 262", "ARH 263", "ARH 265", "ARH 286", "ARH 386", "ARH 486", "ARH 395", "ARH 495"],
        minUpperLevel: 2,
      },
    ],
  },
  ART_STUDIO: {
    code: "ART_STUDIO",
    name: "Art: Studio",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Core",
        description: "Required art studio courses",
        coursesRequired: 4,
        courses: ["ART 134", "ART 135", "ART 136", "ART 137"],
        mustInclude: ["ART 134", "ART 135", "ART 136", "ART 137"],
      },
      {
        category: "Studio Distribution",
        description: "Studio distribution courses at 200-level or above",
        coursesRequired: 2,
        courses: ["ART 211", "ART 216", "ART 225", "ART 230", "ART 311", "ART 316", "ART 325", "ART 330", "ART 411", "ART 416", "ART 425", "ART 430"],
        minUpperLevel: 2,
      },
    ],
  },
  AST: {
    code: "AST",
    name: "Asian Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Intro",
        description: "Required introduction course",
        coursesRequired: 1,
        courses: ["AST 100"],
        mustInclude: ["AST 100"],
      },
      {
        category: "Methods",
        description: "Methods course",
        coursesRequired: 1,
        courses: ["AST 229", "AST 240", "AST 243"],
      },
      {
        category: "Electives",
        description: "Elective courses",
        coursesRequired: 3,
        courses: ["AST 100", "AST 122", "AST 123", "AST 132", "AST 135", "AST 206", "AST 229", "AST 240", "AST 243", "AST 249", "AST 260", "AST 271", "AST 324A", "AST 324C", "AST 324J", "AST 325A", "AST 325C", "AST 325J"],
      },
    ],
  },
  BIO: {
    code: "BIO",
    name: "Biology",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Core biology sequence",
        coursesRequired: 2,
        courses: ["BIO 110", "BIO 113"],
        mustInclude: ["BIO 110", "BIO 113"],
      },
      {
        category: "Distribution",
        description: "Three additional BIO courses",
        coursesRequired: 3,
        courses: ["BIO 114", "BIO 207", "BIO 220", "BIO 222", "BIO 306", "BIO 323", "BIO 324", "BIO 325", "BIO 327", "BIO 330", "BIO 331", "BIO 332", "BIO 338"],
      },
    ],
  },
  BJ: {
    code: "BJ",
    name: "Broadcast Journalism",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Core",
        description: "Required core courses",
        coursesRequired: 3,
        courses: ["COM 211", "COM 212", "COM 398", "COM 395"],
        mustInclude: ["COM 211", "COM 212"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 1 Production Focus + 1 at 300-level",
        coursesRequired: 3,
        courses: ["COM 104", "COM 105", "COM 204", "COM 303", "COM 311", "COM 314", "COM 315", "COM 395", "COM 495", "ETAD 180", "ETAD 202", "THR 115", "THR 135", "THR 227", "THR 331"],
        minUpperLevel: 1,
      },
    ],
  },
  BUS: {
    code: "BUS",
    name: "Business Administration",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required business courses",
        coursesRequired: 3,
        courses: ["BUS 120", "BUS 315", "ECO 101", "ECO 102"],
      },
      {
        category: "Distribution",
        description: "Distribution courses at BUS 200+ level",
        coursesRequired: 2,
        courses: ["BUS 130", "BUS 221", "BUS 240", "BUS 257", "BUS 315", "BUS 323", "BUS 324", "BUS 326", "BUS 327", "BUS 328", "BUS 345", "BUS 346", "BUS 363", "BUS 364", "BUS 366", "BUS 367", "BUS 368", "BUS 371"],
        minUpperLevel: 2,
      },
    ],
  },
  CFS: {
    code: "CFS",
    name: "Child and Family Studies",
    totalMinorCredits: 11,
    requirements: [
      {
        category: "Required Core",
        description: "Required core courses",
        coursesRequired: 4,
        courses: ["CFS 130", "CFS 145", "CFS 207", "CFS 221"],
        mustInclude: ["CFS 130", "CFS 145", "CFS 207", "CFS 221"],
      },
      {
        category: "Child Development",
        description: "Child development course",
        coursesRequired: 1,
        courses: ["CFS 210", "CFS 313", "CFS 315", "CFS 353", "CFS 356"],
      },
      {
        category: "Nutrition/Food Studies",
        description: "Nutrition/food studies course",
        coursesRequired: 1,
        courses: ["CFS 103", "CFS 115", "CFS 209", "CFS 300", "CFS 318"],
      },
      {
        category: "Family Studies",
        description: "Family studies course",
        coursesRequired: 1,
        courses: ["CFS 201", "CFS 237", "CFS 238", "CFS 245", "CFS 317", "CFS 350", "CFS 362", "CFS 366"],
      },
    ],
  },
  CHM: {
    code: "CHM",
    name: "Chemistry",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required chemistry courses",
        coursesRequired: 5,
        courses: ["CHM 131", "CHM 221", "CHM 222", "CHM 311", "CHM 361", "CHM 362"],
      },
      {
        category: "Collateral",
        description: "Collateral courses",
        coursesRequired: 2,
        courses: ["MAT 135", "PHY 127", "PHY 221"],
      },
    ],
  },
  CLS: {
    code: "CLS",
    name: "Classical Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Core",
        description: "Core classical studies course",
        coursesRequired: 1,
        courses: ["LAT 102", "GRK 202"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 4,
        courses: ["CLS 110", "CLS 117", "CLS 129", "CLS 222", "ARH 232", "PHI 305"],
      },
    ],
  },
  COM: {
    code: "COM",
    name: "Communication",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required communication courses",
        coursesRequired: 2,
        courses: ["COM 100", "COM 220"],
        mustInclude: ["COM 100", "COM 220"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 2 COM courses",
        coursesRequired: 3,
        courses: ["BUS 257", "ENG 284", "ENG 380", "ETAD 180", "ETAD 382", "PHI 106", "PSY 210", "SOC 220", "THR 227", "COM 112", "COM 113", "COM 204", "COM 206", "COM 207", "COM 211", "COM 302", "COM 303", "COM 305", "COM 310", "COM 311", "COM 312", "COM 314", "COM 315"],
      },
    ],
  },
  CCE: {
    code: "CCE",
    name: "Community and Civic Engagement",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Core",
        description: "Required core courses",
        coursesRequired: 2,
        courses: ["SOC 212", "PSC 212", "PSJ 212", "GST 425"],
      },
      {
        category: "Power and Inequality",
        description: "Power and inequality course",
        coursesRequired: 1,
        courses: ["AFR 204", "APS 132", "APS 200", "APS 215", "APS 225", "APS 229", "CFS 318", "CFS 350", "CFS 362", "ECO 248", "EDS 150", "EDS 349", "HIS 309", "HLT 210", "HLT 236", "PHI 244", "PSJ 100", "SENS 100", "SOC 100", "SOC 110", "SOC 202", "SOC 215", "SOC 223", "WGS 124", "WGS 200", "WGS 208"],
      },
      {
        category: "Community and Identity",
        description: "Community and identity course",
        coursesRequired: 1,
        courses: ["AFR 135", "AFR 165", "AFR 230", "AFR 245", "APS 100", "APS 121", "APS 140", "APS 224", "ARH 230", "ARH 239", "ARH 243", "CFS 201", "CFS 209", "CFS 231", "CFS 356", "HLT 111", "PHI 261", "PSJ 103", "PSJ 200", "PSJ 210", "SOC 330", "WGS 206", "WGS 233"],
      },
      {
        category: "Civic Literacy",
        description: "Civic literacy course",
        coursesRequired: 1,
        courses: ["PSC 100", "PSC 110"],
      },
      {
        category: "Civic Skills",
        description: "Civic skills course",
        coursesRequired: 1,
        courses: ["CFS 245", "COM 100", "COM 112", "COM 113", "COM 305", "COM 310", "HLT 203", "HLT 300", "PHI 104", "PHI 214", "PHI 241", "PSJ 200", "PSJ 205", "PSJ 301", "PSJ 305"],
      },
    ],
  },
  CSC: {
    code: "CSC",
    name: "Computer and Information Science",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Core programming sequence",
        coursesRequired: 2,
        courses: ["CSC 226", "CSC 236"],
        mustInclude: ["CSC 226", "CSC 236"],
      },
      {
        category: "Upper Level",
        description: "Three upper-level CSC courses",
        coursesRequired: 3,
        courses: ["CSC 246", "CSC 300", "CSC 301", "CSC 303", "CSC 330", "CSC 335", "CSC 410", "CSC 412", "CSC 420", "CSC 425", "CSC 440", "CSC 445", "CSC 450"],
      },
    ],
  },
  CW: {
    code: "CW",
    name: "Creative Writing",
    totalMinorCredits: 4,
    requirements: [
      {
        category: "Required",
        description: "Required creative writing course",
        coursesRequired: 1,
        courses: ["ENG 124"],
        mustInclude: ["ENG 124"],
      },
      {
        category: "Creative Writing Workshops",
        description: "Creative writing workshops (choose 3 of 4)",
        coursesRequired: 3,
        courses: ["ENG 282F", "ENG 282NF", "ENG 282P", "ENG 282E"],
      },
      {
        category: "Capstone",
        description: "Capstone course",
        coursesRequired: 1,
        courses: ["ENG 382"],
        mustInclude: ["ENG 382"],
      },
    ],
  },
  DANCE: {
    code: "DANCE",
    name: "Dance",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required",
        description: "Required dance course",
        coursesRequired: 1,
        courses: ["HHP 245"],
        mustInclude: ["HHP 245"],
      },
      {
        category: "Activity Course",
        description: "Activity course",
        coursesRequired: 1,
        courses: ["WELL 204", "WELL 206P", "WELL 206Y", "WELL 206Z", "WELL 215", "WELL 216", "WELL 224", "WELL 227", "WELL 228", "WELL 229"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 3,
        courses: ["HHP 248", "HHP 249", "HHP 305", "WELL 204", "WELL 205", "WELL 224", "WELL 227", "WELL 230", "WELL 233", "WELL 334", "WELL 434"],
      },
    ],
  },
  DM: {
    code: "DM",
    name: "Digital Media",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Survey Courses",
        description: "Survey courses",
        coursesRequired: 2,
        courses: ["COM 211", "CSC 111", "CSC 121", "ETAD 180", "THR 135"],
      },
      {
        category: "Production Courses",
        description: "Production courses",
        coursesRequired: 2,
        courses: ["COM 311", "ETAD 202", "ETAD 382", "THR 331", "THR 332"],
      },
      {
        category: "400-Level Course",
        description: "400-level course",
        coursesRequired: 1,
        courses: ["COM 498", "COM 495", "COM 490", "COM 497"],
      },
    ],
  },
  ECO: {
    code: "ECO",
    name: "Economics",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required economics courses",
        coursesRequired: 3,
        courses: ["ECO 101", "ECO 102", "ECO 250"],
        mustInclude: ["ECO 101", "ECO 102", "ECO 250"],
      },
      {
        category: "Distribution",
        description: "Distribution courses at ECO 200+ level",
        coursesRequired: 2,
        courses: ["ECO 248", "ECO 301", "ECO 302", "ECO 305", "ECO 332", "ECO 341", "ECO 347", "ECO 350", "ECO 357", "ECO 360", "ECO 370"],
        minUpperLevel: 2,
      },
    ],
  },
  ENG: {
    code: "ENG",
    name: "English",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Core",
        description: "Core English course",
        coursesRequired: 1,
        courses: ["ENG 110", "ENG 124", "ENG 270"],
      },
      {
        category: "Distribution",
        description: "Distribution courses at 200+ level, at least 1 at 300-level",
        coursesRequired: 4,
        courses: ["ENG 200", "ENG 205", "ENG 210", "ENG 225", "ENG 240", "ENG 250", "ENG 270", "ENG 280", "ENG 305", "ENG 310", "ENG 325", "ENG 340", "ENG 350"],
        minUpperLevel: 1,
      },
    ],
  },
  ENV_SCI: {
    code: "ENV_SCI",
    name: "Environmental Science",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Core",
        description: "Required core courses",
        coursesRequired: 3,
        courses: ["GEO 101", "BIO 110", "CHM 131", "BIO 310", "GEO 320"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 3,
        courses: ["ANR 130", "ANR 240", "ANR 342", "BIO 222", "BIO 344", "CHM 221", "CHM 311", "GEO 200", "GEO 320"],
      },
    ],
  },
  FILM: {
    code: "FILM",
    name: "Film Production",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required film courses",
        coursesRequired: 3,
        courses: ["THR 135", "THR 331", "THR 332"],
        mustInclude: ["THR 135", "THR 331", "THR 332"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["ETAD 180", "ETAD 202", "THR 202", "THR 220", "THR 317"],
      },
    ],
  },
  FRM: {
    code: "FRM",
    name: "Forest Resource Management",
    totalMinorCredits: 7,
    requirements: [
      {
        category: "Core Knowledge",
        description: "Core knowledge courses",
        coursesRequired: 2,
        courses: ["BIO 344", "ANR 360"],
        mustInclude: ["BIO 344", "ANR 360"],
      },
      {
        category: "Foundation Courses",
        description: "Foundation courses",
        coursesRequired: 3,
        courses: ["BIO 110", "ANR 130", "BIO 114", "ANR 240"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["ANR 342", "SENS 310", "SENS 320", "BIO 327", "BIO 332", "BIO 342", "ECO 102", "ETAD 140", "ETAD 340", "ANR 375", "ECO 370"],
      },
    ],
  },
  FRN: {
    code: "FRN",
    name: "French",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Core",
        description: "Required French course",
        coursesRequired: 1,
        courses: ["FRN 103"],
        mustInclude: ["FRN 103"],
      },
      {
        category: "Upper-Level French",
        description: "Upper-level French courses",
        coursesRequired: 4,
        courses: ["FRN 200", "FRN 210", "FRN 220", "FRN 300", "FRN 310", "FRN 320", "FRN 330", "FRN 395", "FRN 495"],
        minUpperLevel: 4,
      },
    ],
  },
  GEO: {
    code: "GEO",
    name: "Geology",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required",
        description: "Required geology course",
        coursesRequired: 1,
        courses: ["GEO 101"],
        mustInclude: ["GEO 101"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 2 GEO at 200+ level",
        coursesRequired: 4,
        courses: ["GEO 101", "GEO 200", "GEO 320", "ANR 240", "CHM 311", "CHM 361", "CHM 451", "PHY 365", "PHY 485"],
        minUpperLevel: 2,
      },
    ],
  },
  GER: {
    code: "GER",
    name: "German",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Core",
        description: "Required German course",
        coursesRequired: 1,
        courses: ["GER 103"],
        mustInclude: ["GER 103"],
      },
      {
        category: "Upper-Level German",
        description: "Upper-level German courses",
        coursesRequired: 4,
        courses: ["GER 200", "GER 210", "GER 220", "GER 300", "GER 310", "GER 320", "GER 395", "GER 495"],
        minUpperLevel: 4,
      },
    ],
  },
  HIS: {
    code: "HIS",
    name: "History",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required history course",
        coursesRequired: 1,
        courses: ["HIS 200"],
        mustInclude: ["HIS 200"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 4,
        courses: ["HIS 103", "HIS 112", "HIS 122", "HIS 123", "HIS 124", "HIS 126", "HIS 127", "HIS 128", "HIS 129", "HIS 130", "HIS 131", "HIS 132", "HIS 133", "HIS 134", "HIS 140", "HIS 161", "HIS 162", "HIS 165", "HIS 175", "HIS 201", "HIS 224", "HIS 229", "HIS 242", "HIS 245", "HIS 246", "HIS 250", "HIS 303", "HIS 309", "HIS 310", "HIS 311", "HIS 320", "HIS 324A", "HIS 324C", "HIS 324J", "HIS 335", "HIS 355", "HIS 356"],
      },
    ],
  },
  HLT: {
    code: "HLT",
    name: "Health Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required health courses",
        coursesRequired: 2,
        courses: ["HLT 200", "HLT 227"],
        mustInclude: ["HLT 200", "HLT 227"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["HHP 262", "CFS 221", "HLT 111", "HLT 203", "HLT 205", "HLT 210", "HLT 224", "HLT 236", "HLT 300", "SOC 200"],
      },
      {
        category: "Additional",
        description: "Additional course",
        coursesRequired: 1,
        courses: ["HHP 262", "CFS 221", "HLT 111", "HLT 203", "HLT 205", "HLT 210", "HLT 224", "HLT 236", "HLT 300", "HLT 395", "SOC 200"],
      },
    ],
  },
  LES: {
    code: "LES",
    name: "Law, Ethics and Society",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required core course",
        coursesRequired: 1,
        courses: ["LES 215"],
        mustInclude: ["LES 215"],
      },
      {
        category: "Structures of Law",
        description: "Structures of law course",
        coursesRequired: 1,
        courses: ["BUS 240", "CFS 350", "PSC 100", "PSC 110", "PSC 314", "PSC 317"],
      },
      {
        category: "Law and Ethics",
        description: "Law and ethics course",
        coursesRequired: 1,
        courses: ["AFR 225", "PHI 104"],
      },
      {
        category: "Additional",
        description: "Additional courses",
        coursesRequired: 2,
        courses: ["LES 370", "LES 371", "PHI 106", "PSJ 113", "SOC 215", "BUS 240", "CFS 350", "PSC 100", "PSC 110", "PSC 314", "PSC 317", "AFR 225", "PHI 104"],
      },
    ],
  },
  MAT: {
    code: "MAT",
    name: "Mathematics",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required mathematics courses",
        coursesRequired: 3,
        courses: ["MAT 135", "MAT 225", "MAT 214", "MAT 315"],
        mustInclude: ["MAT 135", "MAT 225"],
      },
      {
        category: "Advanced Distribution",
        description: "Advanced mathematics courses at MAT 310+ level",
        coursesRequired: 2,
        courses: ["MAT 311", "MAT 312", "MAT 315", "MAT 321", "MAT 330", "MAT 337", "MAT 415", "MAT 432", "MAT 433", "MAT 434", "MAT 435", "MAT 436", "MAT 438"],
        minUpperLevel: 2,
      },
    ],
  },
  MUS: {
    code: "MUS",
    name: "Music",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Core Literature",
        description: "Core music literature course",
        coursesRequired: 1,
        courses: ["MUS 115", "MUS 331"],
      },
      {
        category: "Theory Core",
        description: "Theory core courses",
        coursesRequired: 2,
        courses: ["MUS 220", "MUS 221", "MUS 222", "MUS 223"],
        mustInclude: ["MUS 220", "MUS 221", "MUS 222", "MUS 223"],
      },
      {
        category: "Applied Music",
        description: "Applied music courses",
        coursesRequired: 2,
        courses: ["MUA 105", "MUA 115", "MUA 125", "MUA 135", "MUA 205", "MUA 215", "MUA 225", "MUA 235", "MUA 305", "MUA 315", "MUA 325", "MUA 335", "MUA 405", "MUA 415", "MUA 425", "MUA 435"],
      },
      {
        category: "Ensemble",
        description: "Ensemble courses",
        coursesRequired: 1,
        courses: ["MUS 130A", "MUS 130B", "MUS 130C", "MUS 130D", "MUS 130E", "MUS 130F", "MUS 130G", "MUS 130H", "MUS 130K", "MUS 130M", "MUS 131"],
      },
      {
        category: "Additional",
        description: "Additional music course",
        coursesRequired: 1,
        courses: ["MUS 106", "MUS 115", "MUS 118", "MUS 224", "MUS 234", "MUS 320", "MUS 321", "MUS 322", "MUS 323", "MUS 324", "MUS 330", "MUS 331"],
      },
    ],
  },
  PHI: {
    code: "PHI",
    name: "Philosophy",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Logic",
        description: "Logic course",
        coursesRequired: 1,
        courses: ["PHI 106", "PHI 218"],
      },
      {
        category: "History of Philosophy",
        description: "History of philosophy course",
        coursesRequired: 1,
        courses: ["PHI 305", "PHI 310", "PHI 315"],
      },
      {
        category: "Distribution",
        description: "Distribution courses, at least 1 above 100 level",
        coursesRequired: 3,
        courses: ["PHI 104", "PHI 106", "PHI 214", "PHI 215", "PHI 218", "PHI 230", "PHI 241", "PHI 244", "PHI 261", "PHI 305", "PHI 310", "PHI 315", "PHI 380"],
        minUpperLevel: 1,
      },
    ],
  },
  PHY: {
    code: "PHY",
    name: "Physics",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required physics courses",
        coursesRequired: 3,
        courses: ["PHY 221", "PHY 222", "PHY 320"],
        mustInclude: ["PHY 221", "PHY 222", "PHY 320"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["PHY 111", "PHY 130", "PHY 321", "PHY 335", "PHY 365", "PHY 460", "PHY 481", "PHY 482", "PHY 485"],
      },
    ],
  },
  PSC: {
    code: "PSC",
    name: "Political Science",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Core",
        description: "Required political science courses",
        coursesRequired: 4,
        courses: ["PSC 100", "PSC 110", "PSC 220", "PSC 250"],
        mustInclude: ["PSC 100", "PSC 110", "PSC 220", "PSC 250"],
      },
      {
        category: "Distribution",
        description: "Distribution courses at 200-400 level",
        coursesRequired: 2,
        courses: ["PSC 210", "PSC 212", "PSC 314", "PSC 317", "PSC 319", "PSC 322", "PSC 330", "PSC 351", "PSC 355", "PSC 360"],
        minUpperLevel: 2,
      },
    ],
  },
  PSJ: {
    code: "PSJ",
    name: "Peace and Social Justice Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Foundations of peace and justice",
        coursesRequired: 2,
        courses: ["PSJ 100", "PSJ 200"],
      },
      {
        category: "Distribution",
        description: "Three courses from PSJ or approved list",
        coursesRequired: 3,
        courses: ["PSJ 210", "PSJ 220", "PSJ 300", "PSJ 310", "PSJ 400", "SOC 200", "AFR 103", "WGS 200"],
      },
    ],
  },
  REL: {
    code: "REL",
    name: "Studies of Religion and Spirituality",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required religion course",
        coursesRequired: 1,
        courses: ["REL 100"],
        mustInclude: ["REL 100"],
      },
      {
        category: "Religion Department Courses",
        description: "Religion department courses, at least 1 at 200-level, at least 1 at 300-level",
        coursesRequired: 2,
        courses: ["REL 105", "REL 107", "REL 109", "REL 136", "REL 201", "REL 204", "REL 211", "REL 212", "REL 222", "REL 224", "REL 225", "REL 228", "REL 235", "REL 238", "REL 240", "REL 242", "REL 250", "REL 255", "REL 260", "REL 271", "REL 281", "REL 302", "REL 480"],
        minUpperLevel: 2,
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 2,
        courses: ["REL 105", "REL 107", "REL 109", "REL 136", "REL 201", "REL 204", "REL 211", "REL 212", "REL 222", "REL 224", "REL 225", "REL 228", "REL 235", "REL 238", "REL 240", "REL 242", "REL 250", "REL 255", "REL 260", "REL 271", "REL 281"],
      },
    ],
  },
  SOC: {
    code: "SOC",
    name: "Sociology",
    totalMinorCredits: 6,
    requirements: [
      {
        category: "Required Core",
        description: "Required sociology courses",
        coursesRequired: 2,
        courses: ["SOC 100", "SOC 335"],
        mustInclude: ["SOC 100", "SOC 335"],
      },
      {
        category: "Distribution",
        description: "Distribution courses",
        coursesRequired: 4,
        courses: ["SOC 110", "SOC 200", "SOC 202", "SOC 210", "SOC 212", "SOC 215", "SOC 220", "SOC 223", "SOC 300", "SOC 325", "SOC 330", "SOC 341", "SOC 345", "SOC 348", "SOC 350", "SOC 461"],
      },
    ],
  },
  SPN: {
    code: "SPN",
    name: "Spanish",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Core",
        description: "Required Spanish course",
        coursesRequired: 1,
        courses: ["SPN 103"],
        mustInclude: ["SPN 103"],
      },
      {
        category: "Upper-Level Spanish",
        description: "Upper-level Spanish courses at 300-level",
        coursesRequired: 4,
        courses: ["SPN 310", "SPN 312", "SPN 315", "SPN 320", "SPN 330", "SPN 340", "SPN 395", "SPN 495"],
        minUpperLevel: 4,
      },
    ],
  },
  SENS_SUS: {
    code: "SENS_SUS",
    name: "Sustainability and Environmental Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required core course",
        coursesRequired: 1,
        courses: ["SENS 100"],
        mustInclude: ["SENS 100"],
      },
      {
        category: "SENS Upper-Level",
        description: "Upper-level SENS courses",
        coursesRequired: 2,
        courses: ["SENS 215", "SENS 225", "SENS 310", "SENS 320", "SENS 340", "SENS 345", "SENS 370", "SENS 395", "SENS 460", "SENS 495"],
        minUpperLevel: 2,
      },
      {
        category: "Natural Science Group",
        description: "Natural science group course",
        coursesRequired: 1,
        courses: ["ANR 130", "ANR 240", "ANR 360", "BIO 110", "BIO 114", "BIO 342", "BIO 344", "CHM 131", "SENS 310"],
      },
      {
        category: "Social Justice/Economics Group",
        description: "Social justice/economics group course",
        coursesRequired: 1,
        courses: ["APS 215", "APS 225", "APS 229", "CFS 145", "ECO 102", "ECO 341", "ECO 370", "PHI 104", "PHI 230", "PSC 250", "SENS 320", "SENS 340", "SENS 345", "SOC 110"],
      },
    ],
  },
  THR: {
    code: "THR",
    name: "Theatre",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required theatre course",
        coursesRequired: 1,
        courses: ["THR 105"],
        mustInclude: ["THR 105"],
      },
      {
        category: "Core Choice",
        description: "Core choice course",
        coursesRequired: 1,
        courses: ["THR 115", "THR 124", "THR 213"],
      },
      {
        category: "Electives",
        description: "Elective courses, at least 2 at 200+ level",
        coursesRequired: 3,
        courses: ["THR 115", "THR 124", "THR 135", "THR 202", "THR 213", "THR 218", "THR 227", "THR 232", "THR 233", "THR 300", "THR 301", "THR 302", "THR 303", "THR 304", "THR 308", "THR 317", "THR 321", "THR 331", "THR 332"],
        minUpperLevel: 2,
      },
    ],
  },
  WGS: {
    code: "WGS",
    name: "Women and Gender Studies",
    totalMinorCredits: 5,
    requirements: [
      {
        category: "Required Core",
        description: "Required WGS courses",
        coursesRequired: 2,
        courses: ["WGS 124", "WGS 200"],
        mustInclude: ["WGS 124", "WGS 200"],
      },
      {
        category: "Women Concentration",
        description: "Women concentration course",
        coursesRequired: 1,
        courses: ["WGS 103", "WGS 135", "WGS 202", "WGS 230", "WGS 232", "WGS 236", "WGS 243", "WGS 310", "WGS 325"],
      },
      {
        category: "Sexuality Concentration",
        description: "Sexuality concentration course",
        coursesRequired: 1,
        courses: ["WGS 103", "WGS 111", "WGS 201", "WGS 232", "WGS 233"],
      },
      {
        category: "Race or Activism",
        description: "Race or activism course",
        coursesRequired: 1,
        courses: ["APS 229", "ECO 370", "PSJ 100", "PSJ 205", "PSJ 210", "WGS 103", "WGS 202", "WGS 204", "WGS 207", "WGS 225", "WGS 233", "WGS 240", "WGS 366", "AFR 204", "AFR 242", "AFR 250", "PSJ 200"],
      },
    ],
  },
};

export const AVAILABLE_MINORS = Object.values(MINORS).sort((a, b) => a.name.localeCompare(b.name));
