// The .prisma-seed client is regenerated by `prisma generate` in both local
// (SQLite) and production (PostgreSQL on Vercel) environments.  By importing
// from here instead of "@prisma/client" we avoid the stale locked DLL that
// VS Code's Prisma extension holds open during development.
import { PrismaClient } from "../.prisma-seed";

const globalForPrisma = global as unknown as { prisma: PrismaClient };

export const prisma =
  globalForPrisma.prisma ||
  new PrismaClient({
    log: process.env.NODE_ENV === "development" ? ["query"] : [],
  });

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
