// Rebuilds lib/course-schedule-data.ts from all 4 JSON semester files.
// Offering pattern: offeredFall = in F25 OR F26; offeredSpring = in S25 OR S26
// Index: 0=Fall26, 1=Spr27, 2=Fall27, 3=Spr28, 4=Fall28, 5=Spr29, 6=Fall29, 7=Spr30
// Run: npx tsx scripts/rebuild-schedule.ts
import * as fs from "fs";
import * as path from "path";

const JSON_FILES = {
  s25: "data/course-catalog/berea_spring2025_courses.json",
  f25: "data/course-catalog/berea_fall2025_courses.json",
  s26: "data/course-catalog/berea_spring2026_courses.json",
  f26: "data/course-catalog/berea_courses_with_perspectives-fall-26.json",
};

const offeredFall = new Set<string>();
const offeredSpring = new Set<string>();

function loadSemester(file: string, season: "fall" | "spring") {
  const raw = JSON.parse(fs.readFileSync(path.resolve(file), "utf8"));
  for (const c of raw) {
    const code = `${c.subject} ${c.courseNumber}`;
    if (season === "fall") offeredFall.add(code);
    else offeredSpring.add(code);
  }
}

loadSemester(JSON_FILES.f25, "fall");
loadSemester(JSON_FILES.f26, "fall");
loadSemester(JSON_FILES.s25, "spring");
loadSemester(JSON_FILES.s26, "spring");

// Union of all courses across all 4 files
const allCodes = new Set([...offeredFall, ...offeredSpring]);
console.log(`Total unique courses: ${allCodes.size}`);
console.log(`Offered in a Fall: ${offeredFall.size}`);
console.log(`Offered in a Spring: ${offeredSpring.size}`);

// Sort codes for readability
const sorted = [...allCodes].sort((a, b) => a.localeCompare(b));

// Build schedule: [F26, S27, F27, S28, F28, S29, F29, S30]
const lines = sorted.map(code => {
  const f = offeredFall.has(code) ? 1 : 0;
  const s = offeredSpring.has(code) ? 1 : 0;
  // idx: 0=F26, 1=S27, 2=F27, 3=S28, 4=F28, 5=S29, 6=F29, 7=S30
  const arr = [f, s, f, s, f, s, f, s];
  return `  "${code}": [${arr.join(", ")}],`;
});

const header = `// Auto-generated by scripts/rebuild-schedule.ts — do not edit manually
// Source: 4 official Berea JSON semester files (S25, F25, S26, F26)
// Index: 0=Fall26, 1=Spr27, 2=Fall27, 3=Spr28, 4=Fall28, 5=Spr29, 6=Fall29, 7=Spr30
// 1 = offered, 0 = not offered
// Offering pattern: Fall slots use F25/F26 data; Spring slots use S25/S26 data

export const COURSE_SCHEDULE: Record<string, number[]> = {
`;

const footer = `};

export function isCourseAvailable(code: string, semesterIndex: number): boolean {
  const schedule = COURSE_SCHEDULE[code];
  if (!schedule) return true; // assume available if no data
  return schedule[semesterIndex] === 1;
}

export function nextAvailableSemester(code: string, fromIndex: number): number {
  const schedule = COURSE_SCHEDULE[code];
  if (!schedule) return fromIndex;
  for (let i = fromIndex; i < schedule.length; i++) {
    if (schedule[i] === 1) return i;
  }
  return -1; // not available in remaining semesters
}
`;

const result = header + lines.join("\n") + "\n};\n" + footer.slice(footer.indexOf("\nexport function"));
fs.writeFileSync(path.resolve("lib/course-schedule-data.ts"), result, "utf8");
console.log(`Written ${sorted.length} courses to lib/course-schedule-data.ts`);
